src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Id</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>DCC</fullName>
        <active>true</active>
        <label>DCC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
</CustomObject>

src/objects/InstitutionDcc__c.object
<CustomObject>
    <fields>
        <fullName>DCC_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCC Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>InstitutionDccs (DCC Id)</relationshipLabel>
        <relationshipName>InstitutionDccs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>InstitutionDccs (Institution Id)</relationshipLabel>
        <relationshipName>InstitutionDccs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InstitutionDcc</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>InstitutionDcc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InstitutionDccs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/InstitutionTrialDcc__c.object
<CustomObject>
    <fields>
        <fullName>DCC_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCC Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>InstitutionTrialDccs (DCC Id)</relationshipLabel>
        <relationshipName>InstitutionTrialDccs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Id__c</fullName>
        <label>Institution Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>InstitutionTrialDccs</relationshipLabel>
        <relationshipName>InstitutionTrialDccs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>InstitutionTrialDccs</relationshipLabel>
        <relationshipName>InstitutionTrialDccs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InstitutionTrialDcc</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InstitutionTrialDccs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MRI_Volume__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>MRI Volumes</relationshipLabel>
        <relationshipName>MRI_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial Patient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>MRI Volumes CRF</relationshipLabel>
        <relationshipName>MRI_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRI Volume</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>MRI Volume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRI Volumes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <formula>TRIM(LEFT( First_Name__c , 1) ) &amp; &apos;&apos; &amp;  TRIM( LEFT( Middle_Name__c , 1) ) &amp; &apos;&apos; &amp;  TRIM( LEFT( Last_Name__c , 1) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initials</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institute_Text__c</fullName>
        <label>Institute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <label>Medical Record Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>mrn__c</fullName>
        <label>mrn</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HIPPA_Consent_Date__c</fullName>
        <label>HIPPA Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IRB_Approval_Date__c</fullName>
        <label>IRB Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <label>Initials</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution_Id__c</fullName>
        <formula>Patient__r.Institution__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Screening_Informed_Consent_Date__c</fullName>
        <label>Screening Informed Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is need for SignAndSubmit button which is using this id for approval.</description>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>ACRIN_6693_MRS_Participant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ACRIN 6693 MRS Participant?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <description>This formula field display MRN as a related list of trial patient.</description>
        <formula>Patient_Id__r.Medical_Record_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Medical Record Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBeforeDeleteOnRegistration.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBeforeDeleteOnRegistration {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
        List<User> thisUser = [ select u.Id , u.IsActive from User u where profile.Name = 'System Administrator' and IsActive = true];
        System.runAs (thisUser[0]){
            
            Account inst1 = new Account(); //inst
            
            List<Account> lstAccount1 = [Select a.RecordType.Name, a.RecordTypeId, a.Id From Account a where RecordType.Name = 'Institution'];
            
            Account dcc1 = new Account(); // inst or dcc
            
            List<Account> lstAccount2 = [Select a.Name ,a.RecordType.Name, a.RecordTypeId, a.Id From Account a where RecordType.Name = 'DCC'];
            
            if(!(lstAccount1.isEmpty() && lstAccount2.isEmpty())){
                
            inst1 = lstAccount1[0];
            dcc1 =  lstAccount2[0];
                
            Site__c site1 = new Site__c();
            site1.Name = 'test site1';
            site1.Type__c = 'test type';
            site1.Institute__c = inst1.Id;
            insert site1;
            
            InstitutionDcc__c instDCC1 = new InstitutionDcc__c();
            instDCC1.DCC_Id__c = dcc1.Id;
            instDCC1.Institution_Id__c = inst1.Id;
            insert instDCC1;
            
            Trial__c trial1 = new Trial__c();
            trial1.Name='test Trial 1';
            //trial1.InstitutionDcc__c = instDCC1.Id;
            insert trial1; 
            
            InstitutionTrialDcc__c instTrialDcc = new InstitutionTrialDcc__c();
            instTrialDcc.DCC_Id__c = dcc1.Id;
            instTrialDcc.Institution_Id__c = inst1.Id;
            instTrialDcc.Trial_Id__c = trial1.Id;
            insert instTrialDcc;
            
            Group grp1 = new Group();
            grp1.Name = dcc1.Name;
            insert grp1;
            
            GroupMember gMember1 = new GroupMember();
            gMember1.UserOrGroupId = UserInfo.getUserId();
            gMember1.GroupId = grp1.Id;
            insert gMember1;
            
            Patient_Custom__c pc = new Patient_Custom__c();
            pc.First_Name__c = 'test';
            pc.Last_Name__c = 'test2';
            pc.Gender__c = 'Male';
            pc.Birthdate__c = date.newInstance(1988, 7, 7);
            pc.Race__c = 'White';
            pc.Ethnicity__c = 'Not Hispanic or Latino';
            pc.Institution__c = inst1.Id;
            pc.Medical_Record_Number__c = '3434';
            insert pc;
            
            List<Patient_Custom__c> lstPatient = [Select p.Initials__c, p.Last_Name__c, p.Institute_Text__c, p.First_Name__c From Patient_Custom__c p where Id = : pc.Id];
            
            Registration__c reg1 = new Registration__c();
            reg1.Patient__c = pc.Id;
            reg1.First_Name__c = lstPatient[0].First_Name__c;
            reg1.Last_Name__c = lstPatient[0].Last_Name__c;
            reg1.Gender__c = pc.Gender__c;
            reg1.Registration_Date__c = system.today();
            reg1.Trial__c = trial1.Id;
          //  reg1.MRN__c = '3535';
            reg1.Initials__c = lstPatient[0].Initials__c;
            reg1.Ethnicity__c = pc.Ethnicity__c;
            reg1.Race__c =  pc.Race__c;
            reg1.Institution__c = inst1.Id;
            reg1.Site__c = site1.Id;
            reg1.IRB_Approval_Date__c = date.newInstance(2008, 7, 7); 
            reg1.Screening_Informed_Consent_Date__c = date.newInstance(2009, 7, 7);
            reg1.HIPPA_Consent_Date__c = date.newInstance(2011, 7, 7);
        //  reg1.ACRIN_6693_MRS_Participant__c = 'Yes';
            insert reg1; 
            
            Registration__c reg2 = [select TrialPatient__c from Registration__c where Id =:reg1.Id order by LastModifiedDate desc limit 1];
            
            MRI_Volume__c mri = new MRI_Volume__c();
            mri.TrialPatient__c = reg2.TrialPatient__c;
            mri.MRI_Scan_Date__c = date.newInstance(2012, 7, 7);
            mri.MRI_Volume_in_cm3__c = 2.3;
            mri.Longest_Diameter_Of_Index_Lesion_in_cm__c = 2.4;
            mri.Time_Point__c = 'Pre-Treatment';
            insert mri;
            
            delete reg1;
            }
        }
    }
}