src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Id</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Agent__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Dose_Unit__c</fullName>
        <label>Dose Unit</label>
        <picklist>
            <picklistValues>
                <fullName>mg/m2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AUC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>mg/kg</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 weeks</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Dose_Unit__c</fullName>
        <label>Total Dose Unit</label>
        <picklist>
            <picklistValues>
                <fullName>mg</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chemo_Regimen_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Chemo Regimen Agents</relationshipLabel>
        <relationshipName>Chemo_Regimen_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chemo_Regimen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chemo Regimen</label>
        <referenceTo>Chemo_Regimen__c</referenceTo>
        <relationshipLabel>Chemo Regimen Agents</relationshipLabel>
        <relationshipName>Chemo_Regimen_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chemo Regimen Agent</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chemo Regimen Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chemo_Summary_Form__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Chemo Summary Forms</relationshipLabel>
        <relationshipName>Chemo_Summary_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chemo Summary Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chemo Summary Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chemo_Therapy_Regimen__c.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Chemo Therapy Regimens</relationshipLabel>
        <relationshipName>Chemo_Therapy_Regimens</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chemo_Treatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chemo Treatment</label>
        <referenceTo>Chemo_Treatment__c</referenceTo>
        <relationshipLabel>Chemo Therapy Regimens</relationshipLabel>
        <relationshipName>Chemo_Therapy_Regimens</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chemo Therapy Regimen</label>
    <nameField>
        <label>Chemo Therapy Regims Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chemo Therapy Regimens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chemo_Treatment__c.object
<CustomObject>
    <fields>
        <fullName>Cycle_number__c</fullName>
        <label>Cycle number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_therapy__c</fullName>
        <label>Date of therapy</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Did_patient_go_off_study_treatment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Did patient go off study treatment?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_height__c</fullName>
        <label>Patient height</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient_weight__c</fullName>
        <label>Patient weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Chemo Treatments</relationshipLabel>
        <relationshipName>Chemo_Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chemo Treatment</label>
    <nameField>
        <label>Chemo Treatment CRF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chemo Treatments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ChemoSummaryRegimenDetail__c.object
<CustomObject>
    <fields>
        <fullName>Chemo_Regimen__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chemo Regimen</label>
        <referenceTo>Chemo_Regimen__c</referenceTo>
        <relationshipLabel>ChemoSummaryRegimenDetail</relationshipLabel>
        <relationshipName>ChemoSummaryRegimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ChemoSummaryRegimenDetail</label>
    <nameField>
        <label>ChemoSummaryRegimenDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChemoSummaryRegimenDetail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestRegimenAgentController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestRegimenAgentController {

    @isTest static void myUnitTest() {
        
        Profile SiteProp = [ Select p.UserType, p.Name, (Select u.IsActive, u.Id From Users u where IsActive = true) From Profile p where Name = 'Site User'];
        List<User> lstSiteUser = SiteProp.Users;     
        System.runAs ( lstSiteUser[0] ) {
            
            Account insAcc = new Account();

            List<Account> lstAccount = [select Id from Account limit 1]; 
            
            if(!lstAccount.isEmpty()){
                
            insAcc = lstAccount[0];           // newly added logic to overcome the error of "setup and nonsetup" object
            
            Agent__c agent = new Agent__c();
            agent.Display_Order__c = 100;
            agent.Dose_Unit__c = 'mg';
            agent.Frequency__c = 'weekly';
            agent.Name = 'Paclitaxcel';
            agent.Total_Dose_Unit__c = 'mg';
            insert agent;
            
            Chemo_Regimen__c chemoRegimen = new Chemo_Regimen__c();
            chemoRegimen.Name = 'Taxane';
            insert chemoRegimen;
            
            Chemo_Regimen_Agent__c chemoRegimenAgent = new Chemo_Regimen_Agent__c();
            chemoRegimenAgent.Agent__c = agent.Id;
            chemoRegimenAgent.Chemo_Regimen__c = chemoRegimen.Id;
            insert chemoRegimenAgent;
            
            Patient_Custom__c p = new Patient_Custom__c();
            p.Birthdate__c = date.newInstance(1950, 08, 05);
            p.Institution__c = insAcc.Id;
            p.Last_Name__c = 'test'; // patient
            p.Gender__c = 'Male';
            p.Race__c = 'White';
            p.Ethnicity__c = 'Not Hispanic or Latino';
            insert p;
            
            Trial__c trial1 = new Trial__c();
            trial1.Name='test Trial 1';
            insert trial1;  
                
            TrialPatient__c tp = new TrialPatient__c();
            tp.Patient_Id__c = p.Id;
            tp.Trial_Id__c = trial1.Id;
            insert tp;
            
            Chemo_Treatment__c chemoTreatment_cycle1 = new Chemo_Treatment__c();
            chemoTreatment_cycle1.TrialPatient__c = tp.Id;
            chemoTreatment_cycle1.Cycle_number__c = 1;
            chemoTreatment_cycle1.Date_of_therapy__c = system.today();
            chemoTreatment_cycle1.Did_patient_go_off_study_treatment__c = true;
            chemoTreatment_cycle1.Patient_height__c = 12;
            chemoTreatment_cycle1.Patient_weight__c = 12;
            chemoTreatment_cycle1.Status__c = 'Completed';
            insert chemoTreatment_cycle1;
            
            Chemo_Treatment__c chemoTreatment_cycle2 = new Chemo_Treatment__c();
            chemoTreatment_cycle2.TrialPatient__c = tp.Id;
            chemoTreatment_cycle2.Cycle_number__c = 1;
            chemoTreatment_cycle2.Date_of_therapy__c = system.today();
            chemoTreatment_cycle2.Did_patient_go_off_study_treatment__c = true;
            chemoTreatment_cycle2.Patient_height__c = 12;
            chemoTreatment_cycle2.Patient_weight__c = 12;
            chemoTreatment_cycle2.Status__c = 'Completed';
            insert chemoTreatment_cycle2;
            
            Chemo_Therapy_Regimen__c chemoTherapy_cycle1 = new Chemo_Therapy_Regimen__c();
            chemoTherapy_cycle1.Agent__c = agent.Id;
            chemoTherapy_cycle1.Chemo_Treatment__c = chemoTreatment_cycle1.Id;
            chemoTherapy_cycle1.Day__c = 2;
            chemoTherapy_cycle1.Did_patient_stop_receiving__c = false;
            chemoTherapy_cycle1.Dose_Delay__c = 'Yes';
            //chemoTherapy_cycle1.Dose_Mod__c = 12;
            //chemoTherapy_cycle1.Prescribed_Dose__c = 12;
            chemoTherapy_cycle1.Total_Dose__c = 24;
            insert chemoTherapy_cycle1;
            
            Chemo_Therapy_Regimen__c chemoTherapy_cycle2 = new Chemo_Therapy_Regimen__c();
            chemoTherapy_cycle2.Agent__c = agent.Id;
            chemoTherapy_cycle2.Chemo_Treatment__c = chemoTreatment_cycle2.Id;
            chemoTherapy_cycle2.Day__c = 2;
            chemoTherapy_cycle2.Did_patient_stop_receiving__c = false;
            chemoTherapy_cycle2.Dose_Delay__c = 'Yes';
            //chemoTherapy_cycle2.Dose_Mod__c = 12;
            //chemoTherapy_cycle2.Prescribed_Dose__c = 12;
            chemoTherapy_cycle2.Total_Dose__c = 24;
            insert chemoTherapy_cycle2;
            
            Chemo_Therapy_Regimen__c chemoTherapy_cycle3 = new Chemo_Therapy_Regimen__c();
            chemoTherapy_cycle3.Chemo_Treatment__c = chemoTreatment_cycle2.Id;
            chemoTherapy_cycle3.Other_Agent__c = 'test';
            chemoTherapy_cycle3.Day__c = 2;
            chemoTherapy_cycle3.Did_patient_stop_receiving__c = false;
            chemoTherapy_cycle3.Dose_Delay__c = 'Yes';
            //chemoTherapy_cycle2.Dose_Mod__c = 12;
            //chemoTherapy_cycle2.Prescribed_Dose__c = 12;
            chemoTherapy_cycle3.Total_Dose__c = 24;
            insert chemoTherapy_cycle3;
            
            Chemo_Therapy_Regimen__c chemoTherapy_cycle4 = new Chemo_Therapy_Regimen__c();
            chemoTherapy_cycle4.Chemo_Treatment__c = chemoTreatment_cycle2.Id;
            chemoTherapy_cycle4.Other_Agent__c = 'test';
            chemoTherapy_cycle4.Day__c = 2;
            chemoTherapy_cycle4.Did_patient_stop_receiving__c = false;
            chemoTherapy_cycle4.Dose_Delay__c = 'Yes';
            //chemoTherapy_cycle2.Dose_Mod__c = 12;
            //chemoTherapy_cycle2.Prescribed_Dose__c = 12;
            chemoTherapy_cycle4.Total_Dose__c = 24;
            insert chemoTherapy_cycle4;
            
            Chemo_Summary_Form__c chemoSummaryForm = new Chemo_Summary_Form__c ();
            chemoSummaryForm.TrialPatient__c = tp.Id;
            chemoSummaryForm.Status__c = 'Not Completed';
            insert chemoSummaryForm;
            
            Chemo_Regimen__c chemoRegimen1 = new Chemo_Regimen__c();
            chemoRegimen1.Name = 'Taxane';
            insert chemoRegimen1;
            
            Chemo_Regimen__c chemoRegimen2 = new Chemo_Regimen__c();
            chemoRegimen2.Name = 'Anthracycline';
            insert chemoRegimen2;
            
            Chemo_Regimen__c chemoRegimen3 = new Chemo_Regimen__c();
            chemoRegimen3.Name = 'Investigational';
            insert chemoRegimen3;
            
            ChemoSummaryRegimenDetail__c chemoSummaryRegimenDetail = new ChemoSummaryRegimenDetail__c();
            chemoSummaryRegimenDetail.First_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail.Last_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail.Treatment_End_Reasons__c = 'Treatment completed per protocol criteria';
            chemoSummaryRegimenDetail.Chemo_Regimen__c = chemoRegimen1.Id;
            chemoSummaryRegimenDetail.Chemo_Summary_Form__c = chemoSummaryForm.Id;
            insert chemoSummaryRegimenDetail;
            
            ChemoSummaryRegimenDetail__c chemoSummaryRegimenDetail1 = new ChemoSummaryRegimenDetail__c();
            chemoSummaryRegimenDetail1.First_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail1.Last_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail1.Treatment_End_Reasons__c = 'Treatment completed per protocol criteria';
            chemoSummaryRegimenDetail1.Chemo_Summary_Form__c = chemoSummaryForm.Id;
            insert chemoSummaryRegimenDetail1;
            
            ChemoSummaryRegimenDetail__c chemoSummaryRegimenDetail2 = new ChemoSummaryRegimenDetail__c();
            chemoSummaryRegimenDetail2.First_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail2.Last_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail2.Treatment_End_Reasons__c = 'Treatment completed per protocol criteria';
            chemoSummaryRegimenDetail2.Chemo_Regimen__c = chemoRegimen2.Id;
            chemoSummaryRegimenDetail2.Chemo_Summary_Form__c = chemoSummaryForm.Id;
            insert chemoSummaryRegimenDetail2;
            
            ChemoSummaryRegimenDetail__c chemoSummaryRegimenDetail3 = new ChemoSummaryRegimenDetail__c();
            chemoSummaryRegimenDetail3.First_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail3.Last_Date_of_Therapy__c = system.today();
            chemoSummaryRegimenDetail3.Treatment_End_Reasons__c = 'Treatment completed per protocol criteria';
            chemoSummaryRegimenDetail3.Chemo_Regimen__c = chemoRegimen3.Id;
            chemoSummaryRegimenDetail3.Chemo_Summary_Form__c = chemoSummaryForm.Id;
            insert chemoSummaryRegimenDetail3;
        
            RegimenAgentController regAgentController = new RegimenAgentController();
            regAgentController.chemoSummaryId = chemoSummaryForm.Id;
            regAgentController.trialPatientId = tp.Id;
            regAgentController.regimenName = chemoRegimen.Name;
            regAgentController.getRegimenDetailWrapper();
            
            RegimenAgentController regAgentController1 = new RegimenAgentController();
            regAgentController1.chemoSummaryId = chemoSummaryForm.Id;
            regAgentController1.trialPatientId = tp.Id;
            regAgentController1.regimenName = 'Other';
            regAgentController1.getRegimenDetailWrapper();
            regAgentController1.saveComponent(chemoSummaryForm.Id, 'Taxane');
            regAgentController1.saveComponent(chemoSummaryForm.Id, 'Anthracycline');
            regAgentController1.saveComponent(chemoSummaryForm.Id, 'Investigational');
            regAgentController1.saveComponent(chemoSummaryForm.Id, 'test');
            }
        }
    }
}