src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Id</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
</CustomObject>

src/objects/Code_Master__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsReportColumn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsReportColumn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Snomed_Code__c</fullName>
        <label>Snomed Code</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Variable_Description__c</fullName>
        <label>Variable Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Code Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MRI_Volume__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>MRI Volumes</relationshipLabel>
        <relationshipName>MRI_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>MRI Volumes</relationshipLabel>
        <relationshipName>MRI_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Point__c</fullName>
        <label>Time Point</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Regimen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Surgery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial Patient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>MRI Volumes CRF</relationshipLabel>
        <relationshipName>MRI_Volumes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MRI Volume</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>MRI Volume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MRI Volumes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Snomed_Code__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Snomed Codes</relationshipLabel>
        <relationshipName>Snomed_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Code Master</label>
        <referenceTo>Code_Master__c</referenceTo>
        <relationshipLabel>Snomed Codes</relationshipLabel>
        <relationshipName>Snomed_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Snomed Codes</relationshipLabel>
        <relationshipName>Snomed_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>snomed_Code_Name__c</fullName>
        <description>This is custom field for storing snomed code name. Earlier we were storing code name in standard &quot;Name&quot; field but that only contains 80 characters. Thats why we created this field.</description>
        <label>snomed Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Snomed Code</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Snomed Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snomed Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestInsertCRFOnMRIVolume.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestInsertCRFOnMRIVolume {

     @isTest static void myUnitTest() {
        // TO DO: implement unit test
        
        List<User> thisUser = [ select u.Id , u.IsActive from User u where profile.Name = 'System Administrator' and IsActive = true];
        System.runAs (thisUser[0]){
        
        Account inst1 = new Account();

        List<Account> lstAccount = [Select a.RecordType.Name, a.RecordTypeId, a.Id From Account a where RecordType.Name = 'Institution'];
        
        if(!lstAccount.isEmpty()){
                
        inst1 = lstAccount[0];
                
        Site__c site1 = new Site__c();
        site1.Name = 'test site1';
        site1.Type__c = 'test type';
        site1.Institute__c = inst1.Id;
        insert site1;
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Ethnicity__c = 'Hispanic or latino';
        p.Gender__c = 'female';
        p.Race__c = 'asian;indian';
        p.Last_Name__c = 'kumar';
        p.Status__c = 'approval not required';
        p.First_Name__c = 'test';
        p.Birthdate__c = date.newInstance(1980, 08, 05);
        p.Institution__c = inst1.Id;
        insert p;
        
        Trial__c t = new Trial__c();
        t.Name = 'test';
        insert t;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        tp.Trial_Id__c = t.Id;
        insert tp;
        
        CRF__c crf = new CRF__c();
        crf.Patient__c = p.Id;
        crf.Status__c = 'Not Completed';
        insert crf;
        
        Code_Master__c snomedObject = new Code_Master__c();
        snomedObject.Variable_Description__c = 'test';
        snomedObject.IsReportColumn__c = true;
        snomedObject.Display_Order__c = 3.0;
        snomedObject.Name = 'MRIvol_T0';
        insert snomedObject;
        
        Snomed_Code__c snomed = new Snomed_Code__c();
        snomed.Code_Master__c = snomedObject.Id;
        snomed.snomed_Code_Name__c = 'LOINC_MRI_Vol_3';
        snomed.CRF__c = crf.Id;
        insert snomed;
        
        MRI_Volume__c mri = new MRI_Volume__c();
        mri.TrialPatient__c = tp.Id;
        mri.CRF__c = crf.Id;
        mri.Time_Point__c = 'Pre-Treatment';
        mri.MRI_Volume_in_cm3__c = 12.0;
        mri.MRI_Scan_Date__c = date.newInstance(2012, 7, 7);
        mri.Longest_Diameter_Of_Index_Lesion_in_cm__c = 2.4;
        insert mri;
        update mri;
        
     /*   //=========================else if line 137====================================================
        
        Code_Master__c snomedObject3 = new Code_Master__c();
        snomedObject3.Variable_Description__c = 'test';
        snomedObject3.IsReportColumn__c = true;
        snomedObject3.Display_Order__c = 3.0;
        snomedObject3.Name = 'MRIvol_T3';
        insert snomedObject3;
        
        Snomed_Code__c snomed1 = new Snomed_Code__c();
        snomed1.Code_Master__c = snomedObject.Id;
        snomed1.snomed_Code_Name__c = 'MRIvol_T3';
        snomed1.CRF__c = crf.Id;
        insert snomed1;
        
        MRI_Volume__c mri3 = new MRI_Volume__c();
        mri3.TrialPatient__c = tp.Id;
        mri3.CRF__c = crf.Id;
        mri3.Time_Point__c = 'Pre-Surgery';
        mri3.MRI_Scan_Date__c = date.newInstance(2012, 7, 7);
        mri3.Longest_Diameter_Of_Index_Lesion_in_cm__c = 2.4;
        mri3.MRI_Volume_in_cm3__c = 12.0;
        insert mri3;
        update mri3; */
            }
        }
    }
    
    @isTest static void myUnitTest1() {
        // TO DO: implement unit test
        
        List<User> thisUser = [ select u.Id , u.IsActive from User u where profile.Name = 'System Administrator' and IsActive = true];
        System.runAs (thisUser[0]){
        
        Account inst1 = new Account();

        List<Account> lstAccount = [Select a.RecordType.Name, a.RecordTypeId, a.Id From Account a where RecordType.Name = 'Institution'];
        
        if(!lstAccount.isEmpty()){
                
        inst1 = lstAccount[0];
                
        Site__c site1 = new Site__c();
        site1.Name = 'test site1';
        site1.Type__c = 'test type';
        site1.Institute__c = inst1.Id;
        insert site1;
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Ethnicity__c = 'Hispanic or latino';
        p.Gender__c = 'female';
        p.Race__c = 'asian;indian';
        p.Last_Name__c = 'kumar';
        p.Status__c = 'approval not required';
        p.First_Name__c = 'test';
        p.Birthdate__c = date.newInstance(1980, 08, 05);
        p.Institution__c = inst1.Id;
        insert p;
        
        Trial__c t = new Trial__c();
        t.Name = 'test';
        insert t;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        tp.Trial_Id__c = t.Id;
        insert tp;
        
        CRF__c crf = new CRF__c();
        crf.Patient__c = p.Id;
        crf.Status__c = 'Not Completed';
        insert crf;
        
        //===========================else if line 119================================================
        
        Code_Master__c snomedObject1 = new Code_Master__c();
        snomedObject1.Variable_Description__c = 'test';
        snomedObject1.IsReportColumn__c = true;
        snomedObject1.Display_Order__c = 3.0;
        snomedObject1.Name = 'MRIvol_T1';
        insert snomedObject1;
        
        MRI_Volume__c mri1 = new MRI_Volume__c();
        mri1.TrialPatient__c = tp.Id;
        mri1.CRF__c = crf.Id;
        mri1.Time_Point__c = 'Early Treatment';
        mri1.MRI_Scan_Date__c = date.newInstance(2012, 7, 7);
        mri1.Longest_Diameter_Of_Index_Lesion_in_cm__c = 2.4;
        mri1.MRI_Volume_in_cm3__c = 12.0;
        insert mri1;
        update mri1;
        
            }
        }
    }
    
    @isTest static void myUnitTest3() {
        // TO DO: implement unit test
        
        List<User> thisUser = [ select u.Id , u.IsActive from User u where profile.Name = 'System Administrator' and IsActive = true];
        System.runAs (thisUser[0]){
        
        Account inst1 = new Account();

        List<Account> lstAccount = [Select a.RecordType.Name, a.RecordTypeId, a.Id From Account a where RecordType.Name = 'Institution'];
        
        if(!lstAccount.isEmpty()){
                
        inst1 = lstAccount[0];
                
        Site__c site1 = new Site__c();
        site1.Name = 'test site1';
        site1.Type__c = 'test type';
        site1.Institute__c = inst1.Id;
        insert site1;
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Ethnicity__c = 'Hispanic or latino';
        p.Gender__c = 'female';
        p.Race__c = 'asian;indian';
        p.Last_Name__c = 'kumar';
        p.Status__c = 'approval not required';
        p.First_Name__c = 'test';
        p.Birthdate__c = date.newInstance(1980, 08, 05);
        p.Institution__c = inst1.Id;
        insert p;
        
        Trial__c t = new Trial__c();
        t.Name = 'test';
        insert t;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        tp.Trial_Id__c = t.Id;
        insert tp;
        
        CRF__c crf = new CRF__c();
        crf.Patient__c = p.Id;
        crf.Status__c = 'Not Completed';
        insert crf;
        
        //=========================else if line 128====================================================
        
        Code_Master__c snomedObject2 = new Code_Master__c();
        snomedObject2.Variable_Description__c = 'test';
        snomedObject2.IsReportColumn__c = true;
        snomedObject2.Display_Order__c = 3.0;
        snomedObject2.Name = 'MRIvol_T2';
        insert snomedObject2;
        
        MRI_Volume__c mri2 = new MRI_Volume__c();
        mri2.TrialPatient__c = tp.Id;
        mri2.CRF__c = crf.Id;
        mri2.Time_Point__c = 'Inter-Regimen';
        mri2.MRI_Scan_Date__c = date.newInstance(2012, 7, 7);
        mri2.Longest_Diameter_Of_Index_Lesion_in_cm__c = 2.4;
        mri2.MRI_Volume_in_cm3__c = 12.0;
        insert mri2;
        update mri2;
        
            }
        }
    }
}