src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Id</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>DCC</fullName>
        <active>true</active>
        <label>DCC</label>
    </recordTypes>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
</CustomObject>

src/objects/InstitutionTrial__c.object
<CustomObject>
    <fields>
        <fullName>Institution_Id__c</fullName>
        <label>Institution Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Institution Trials</relationshipLabel>
        <relationshipName>InstitutionTrials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>InstitutionTrials</relationshipLabel>
        <relationshipName>InstitutionTrials</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>InstitutionTrial</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InstitutionTrials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/InstitutionTrialDcc__c.object
<CustomObject>
    <fields>
        <fullName>DCC_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DCC Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>InstitutionTrialDccs (DCC Id)</relationshipLabel>
        <relationshipName>InstitutionTrialDccs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Id__c</fullName>
        <label>Institution Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>InstitutionTrialDccs</relationshipLabel>
        <relationshipName>InstitutionTrialDccs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>InstitutionTrialDccs</relationshipLabel>
        <relationshipName>InstitutionTrialDccs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InstitutionTrialDcc</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InstitutionTrialDccs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssociateDccAndTrial.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAssociateDccAndTrial {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
        
        List<RecordType> recInst = [select id,Name from RecordType where Name = 'DCC'];
        List<RecordType> recInst1 = [select id,Name from RecordType where Name = 'Institution'];
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            Account acc = new Account();
            acc.Name = 'TestDCC';
            acc.RecordTypeId = recInst[0].Id;
            insert acc;
            
            Account acc1 = new Account();
            acc1.Name = 'TestIns';
            acc1.RecordTypeId = recInst1[0].Id;
            insert acc1;
            
            Account dcc = new Account();
            dcc.Name = 'TestIns';
            dcc.RecordTypeId = recInst[0].Id;
            insert dcc;
            
            Trial__c tri = new Trial__c();
            tri.Name = 'Test';
            insert tri;
            
            InstitutionTrial__c it = new InstitutionTrial__c();
            it.Institution_Id__c = acc1.Id;
            it.Trial_Id__c = tri.Id;
            insert it;
            
            InstitutionTrialDcc__c itd = new InstitutionTrialDcc__c();
            itd.Trial_Id__c = tri.Id;
            itd.Institution_Id__c = acc1.Id;
            itd.DCC_Id__c = dcc.Id;
            insert itd;
            
            Apexpages.currentPage().getParameters().put('institutionId',acc1.Id);
            AssociateDccAndTrial assDT = new AssociateDccAndTrial();
            AssociateDccAndTrial.wrapperClass wc = new AssociateDccAndTrial.wrapperClass();
            AssociateDccAndTrial.TrialWrapper tw = new AssociateDccAndTrial.TrialWrapper();
            wc.ischecked = true;
            //assDT.trialIdSet = tri.Id;
            Pagereference pr = assDT.submit();
        }
    }
}