src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Proposed_Rescheduling__c.object
<CustomObject>
    <fields>
        <fullName>DurationInMinutes__c</fullName>
        <label>DurationInMinutes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Eventid__c</fullName>
        <label>Eventid</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minutes__c</fullName>
        <label>Minutes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PatientId__c</fullName>
        <label>PatientId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposed_New_Date__c</fullName>
        <label>Proposed New Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StartDateTime__c</fullName>
        <label>StartDateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>refId__c</fullName>
        <label>refId</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>studyStaff__c</fullName>
        <label>studyStaff</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Proposed Rescheduling</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Proposed Resch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposed Rescheduling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestEventUpdate.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestEventUpdate {

    @isTest static void myUnitTest() { 
        
        List<User> thisUser = [Select u.IsActive, u.Id ,u.Patient_Id__c,u.ProfileId,u.Username From User u where IsActive = true and Username != null];   
        
        System.runAs (thisUser[0]) {   
            
        List<RecordType> recordT = [Select r.Name, r.Id From RecordType r where sObjectType = 'Account' and Name='Institution' order by Name];
        
        Account accObj = new Account();
        accObj.Name = 'test Institute 1';
        accObj.RecordTypeId = recordT[0].Id;
        insert accObj; 
        
        Trial__c tr = new Trial__c();
        tr.Name = 'test';
        insert tr;
        
        Patient_Custom__c patObj = new Patient_Custom__c();
        patObj.Birthdate__c = date.newInstance(1960, 8, 7);
        patObj.Ethnicity__c = 'Hispanic or latino';
        patObj.Gender__c = 'female';
        patObj.Race__c = 'asian';
        patObj.First_Name__c = 'test';
        patObj.Last_Name__c = 'kumar';
        patObj.Institution__c = accObj.Id;
        patObj.Email__c = thisUser[0].Username;
        insert patObj;
            
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        
        system.debug('patObj.Email__c : '+patObj.Email__c);
        envelope.toAddress = patObj.Email__c;
        email.subject = 'test';
        email.plainTextBody = 'Accept';
        envelope.fromAddress = '7.bhupesh@gmail.com';
        
        
        Event eventObject = new Event();
        eventObject.Trial__c = tr.Id;
        eventObject.ActivityDateTime = system.now();
        eventObject.WhatId = accObj.Id;
        eventObject.OwnerId = thisUser[0].Id;
        eventObject.Subject = 'test';
        eventObject.DurationInMinutes = 300;
        eventObject.Hours__c = null;
        eventObject.Minutes__c = null;
        eventObject.StartDateTime = eventObject.ActivityDateTime;
        insert eventObject;
        update eventObject;
        
        Proposed_Rescheduling__c prObject = new Proposed_Rescheduling__c();
        prObject.Eventid__c = eventObject.Id;
        prObject.Proposed_New_Date__c = eventObject.ActivityDateTime;
        prObject.OwnerId = thisUser[0].Id;
        prObject.PatientId__c = patObj.Id;
        prObject.studyStaff__c = thisUser[0].Id;
        prObject.DurationInMinutes__c = 300;
        prObject.StartDateTime__c = eventObject.ActivityDateTime;
        prObject.refId__c = email.subject;
        insert prObject;
        
        EventUpdate euObject = new EventUpdate();
        euObject.handleInboundEmail(email, envelope); 
      }
   }
   @isTest static void myUnitTest1() { // SATISFY "ELSE" CONDITION LINE 102
        
        List<User> thisUser = [Select u.IsActive, u.Id ,u.Patient_Id__c,u.ProfileId,u.Username From User u where IsActive = true and Username != null];   
        
        System.runAs (thisUser[0]) {   
            
        List<RecordType> recordT = [Select r.Name, r.Id From RecordType r where sObjectType = 'Account' and Name='Institution' order by Name];
        
        Account accObj = new Account();
        accObj.Name = 'test Institute 1';
        accObj.RecordTypeId = recordT[0].Id;
        insert accObj; 
        
        Trial__c tr = new Trial__c();
        tr.Name = 'test';
        insert tr;
        
        Patient_Custom__c patObj = new Patient_Custom__c();
        patObj.Birthdate__c = date.newInstance(1960, 8, 7);
        patObj.Ethnicity__c = 'Hispanic or latino';
        patObj.Gender__c = 'female';
        patObj.Race__c = 'asian';
        patObj.First_Name__c = 'test';
        patObj.Last_Name__c = 'kumar';
        patObj.Institution__c = accObj.Id;
        patObj.Email__c = thisUser[0].Username;
        insert patObj;
            
        Event eventObject = new Event();
        eventObject.Trial__c = tr.Id;
        eventObject.WhatId = accObj.Id;
        eventObject.OwnerId = thisUser[0].Id;
        eventObject.Subject = 'test';
        eventObject.DurationInMinutes = 300;
        eventObject.Hours__c = 2.0;
        eventObject.Minutes__c = 30.0;
        eventObject.StartDateTime = system.now();
        insert eventObject;
        update eventObject;
        
        system.debug('eventObject.Owner.UserName : '+eventObject.Owner.UserName);
        
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        Messaging.InboundEnvelope envelope = new Messaging.InboundEnvelope();
        
        system.debug('patObj.Email__c : '+patObj.Email__c);
        envelope.toAddress = patObj.Email__c;
        email.subject = 'test';
        email.plainTextBody = 'Reject';                                                             // satisfy "else" part 
        envelope.fromAddress = '7.bhupesh@gmail.com';
        
        Proposed_Rescheduling__c prObject = new Proposed_Rescheduling__c();
        prObject.Eventid__c = eventObject.Id;
        prObject.OwnerId = thisUser[0].Id;
        prObject.PatientId__c = patObj.Id;
        prObject.studyStaff__c = thisUser[0].Id;
        prObject.DurationInMinutes__c = 300;
        prObject.StartDateTime__c = system.now();
        prObject.refId__c = email.subject;
        insert prObject;
        
        EventUpdate euObject = new EventUpdate();
        euObject.handleInboundEmail(email, envelope); 
      }
   }
}