src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Institution</fullName>
        <active>true</active>
        <label>Institution</label>
    </recordTypes>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <picklist>
            <picklistValues>
                <fullName>under 20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>over 90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestPatientByEthinicityAndRaceController.cls
@isTest
public class  TestPatientByEthinicityAndRaceController{
  public static testMethod void test(){
          Account acc = new Account(Name='TEst Institution');
        insert acc;
        Date d= Date.Today();
        Patient_Custom__c patient= new Patient_Custom__c(Last_Name__c = 'Test last', Birthdate__c = d  ,Ethnicity__c='Hispanic or Latino', Age_Group__c = '20-30', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient;
        Patient_Custom__c patient1= new Patient_Custom__c(Last_Name__c = 'Test last1', Birthdate__c = d  ,Ethnicity__c='Hispanic or Latino', Age_Group__c = '30-40', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient1;
        Patient_Custom__c patient2= new Patient_Custom__c(Last_Name__c = 'Test last2', Birthdate__c = d  ,Ethnicity__c='Non Hispanic or Latino', Age_Group__c = '40-50', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient2;
        Patient_Custom__c patient3= new Patient_Custom__c(Last_Name__c = 'Test last3', Birthdate__c = d  ,Ethnicity__c='NOn Hispanic or Latino', Age_Group__c = '50-60', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient3;
        Patient_Custom__c patient4= new Patient_Custom__c(Last_Name__c = 'Test last4', Birthdate__c = d  ,Ethnicity__c='Hispanic or Latino', Age_Group__c = '60-70', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient4;
        Patient_Custom__c patient5= new Patient_Custom__c(Last_Name__c = 'Test last5', Birthdate__c = d  ,Ethnicity__c='Hispanic or Latino', Age_Group__c = '70-80', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient5;
        Patient_Custom__c patient6= new Patient_Custom__c(Last_Name__c = 'Test last6', Birthdate__c = d  ,Ethnicity__c='Hispanic or Latino', Age_Group__c = '80-90', Race__c = 'Asian' , Institution__c = acc.id);
        insert patient6;
        PatientByEthinicityAndRaceController per1 = new PatientByEthinicityAndRaceController();
        PageReference pageRef = Page.PatientByAgeEthinicity;
        pageRef.getParameters().put('institute', String.valueOf(acc.Id));
        Test.setCurrentPageReference(pageRef); 
       PatientByEthinicityAndRaceController per = new PatientByEthinicityAndRaceController();
        
        
  }
}