src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Id</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Chemo_Therapy_Regimen__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <label>Chemo Therapy Regimen</label>
    <nameField>
        <label>Chemo Therapy Regims Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chemo Therapy Regimens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Chemo_Treatment__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Chemo Treatments</relationshipLabel>
        <relationshipName>Chemo_Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chemo Treatment</label>
    <nameField>
        <label>Chemo Treatment CRF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chemo Treatments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>HIPPA_Consent_Date__c</fullName>
        <label>HIPPA Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IRB_Approval_Date__c</fullName>
        <label>IRB Approval Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ISPY2_Subject_Id__c</fullName>
        <label>ISPY2 Subject Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Screening_Informed_Consent_Date__c</fullName>
        <label>Screening Informed Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is need for SignAndSubmit button which is using this id for approval.</description>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>IsTestSite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for test site only.</description>
        <label>IsTestSite</label>
        <type>Checkbox</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestPatientSummaryReport.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestPatientSummaryReport {  

   @isTest static void myUnitTest() { 
        // TO DO: implement unit test
    List<User> thisUser = [ select u.Id , u.IsActive from User u where IsActive = true and id =: userinfo.getUserId()];
    System.runAs (thisUser[0]){
            
    Account inst1 = new Account();
        
    List<Account> lstAccount = [Select a.Id From Account a limit 1];
    
    if(!lstAccount.isEmpty()){
                
        inst1 = lstAccount[0];
        
        Patient_Custom__c pc = new Patient_Custom__c();
        pc.Last_Name__c = 'test1';
        pc.Gender__c = 'Male';
        pc.Birthdate__c = date.newInstance(1977, 8, 7);
        pc.Race__c = 'White';
        pc.Ethnicity__c = 'Not Hispanic or Latino';
        pc.Institution__c = inst1.Id;
        insert pc;
        
        Trial__c tri = new Trial__c();
        tri.Name = 'Test';
        insert tri;
        
        Site__c siteObject = new Site__c(); 
        siteObject.Institute__c = inst1.Id;
        siteObject.IsTestSite__c = false;
        insert siteObject; 
        
        TrialPatient__c triPat = new TrialPatient__c();
        triPat.Trial_Id__c = tri.Id;
        triPat.Patient_Id__c = pc.Id;
        triPat.Site__c = siteObject.Id;
        triPat.Subject_Id__c = ''+123;
        insert triPat;
        
        Registration__c reg1 = new Registration__c();
        reg1.Patient__c = pc.Id;
        reg1.TrialPatient__c = triPat.Id;
        reg1.Registration_Date__c = system.today();
        reg1.Trial__c = tri.Id;
        reg1.Institution__c = inst1.Id;
        reg1.IRB_Approval_Date__c = date.newInstance(2008, 7, 7); 
        reg1.Screening_Informed_Consent_Date__c = date.newInstance(2009, 7, 7);
        reg1.HIPPA_Consent_Date__c = date.newInstance(2011, 7, 7);
        reg1.Effective_Time__c = system.now();
        reg1.ISPY2_Subject_Id__c = ''+123;
        reg1.Status__c = 'Approval Pending';
        insert reg1; 
        reg1.Status__c = 'Accepted';
        Test.startTest();
        update reg1; 
        Test.stopTest();
        
        
        Agent__c agent = new Agent__c();
        agent.Name = 'Paclitaxel (Taxol)';
        agent.Display_Order__c = 0;
        insert agent;
        
        Chemo_Treatment__c chemObject = new Chemo_Treatment__c();
        chemObject.TrialPatient__c = triPat.Id;
        chemObject.Cycle_number__c = 2.0;
        insert chemObject;
        
        Chemo_Therapy_Regimen__c chemo = new Chemo_Therapy_Regimen__c ();
        chemo.Chemo_Treatment__c = chemObject.Id;
        chemo.Agent__c = agent.Id;
        chemo.Effective_Time__c = system.now();
        insert chemo;
        
        Off_Study_Detail__c offStudy1 = new Off_Study_Detail__c(); 
        offStudy1.TrialPatient__c = triPat.Id; 
        offStudy1.Patient_completed_study_per_protocol__c = true;
        offStudy1.Patient_did_not_want_to_complete_MRI__c = true;
        offStudy1.Patient_did_nt_want_to_complete_core_bio__c = true;
        offStudy1.Patient_did_nt_continue_on_treatment_arm__c = true;
        offStudy1.Patient_did_not_have_surgery__c = true;
        offStudy1.Patient_Died__c = true;
        
        insert offStudy1;
        
        
        
        PatientSummaryReport psrObject = new PatientSummaryReport();
        List<String> sis = new List<String>();
        sis.add(inst1.Id);
        psrObject.selectedInstitute = sis;
        
        List<String> tids = new List<String>();
        tids.add(tri.Id);
        psrObject.selectedTrial = tids;
        psrObject.reportRequestAction(); 
        PatientSummaryReport.sortList(new List<Sobject>{chemo}, 'Effective_Time__c', 'asc'); 
        
        PatientSummaryReport.sortList(new List<Sobject>{chemo}, 'Effective_Time__c', 'desc'); // satisfy "else if" condition line 779
        
     }
   }
 }
        @isTest public static void unitTest1() {  
            
        Account inst1 = new Account();
        List<Account> lstAccount = [Select a.Id From Account a limit 1];
        if(!lstAccount.isEmpty()){
                    
        inst1 = lstAccount[0];
            
        Patient_Custom__c pc = new Patient_Custom__c();
        pc.Last_Name__c = 'test1';
        pc.Gender__c = 'Male';
        pc.Birthdate__c = date.newInstance(1977, 8, 7);
        pc.Race__c = 'White';
        pc.Ethnicity__c = 'Not Hispanic or Latino';
        pc.Institution__c = inst1.Id;
        insert pc;
        
        Trial__c tri = new Trial__c();
        tri.Name = 'Test';
        insert tri;
        
        Site__c siteObject = new Site__c(); 
        siteObject.Institute__c = inst1.Id;
        siteObject.IsTestSite__c = false;
        insert siteObject;  
        
        TrialPatient__c triPat = new TrialPatient__c();
        triPat.Trial_Id__c = tri.Id;
        triPat.Patient_Id__c = pc.Id;
        triPat.Site__c = siteObject.Id;
        triPat.Subject_Id__c = ''+123;
        insert triPat;
            
        Registration__c reg1 = new Registration__c();
        reg1.Patient__c = pc.Id;
        reg1.TrialPatient__c = triPat.Id;
        reg1.Registration_Date__c = system.today();
        reg1.Trial__c = tri.Id;
        reg1.Institution__c = inst1.Id;
        reg1.IRB_Approval_Date__c = date.newInstance(2008, 7, 7); 
        reg1.Screening_Informed_Consent_Date__c = date.newInstance(2009, 7, 7);
        reg1.HIPPA_Consent_Date__c = date.newInstance(2011, 7, 7);
        reg1.Effective_Time__c = system.now();
        reg1.ISPY2_Subject_Id__c = ''+123;
        reg1.Status__c = 'Approval Pending';
        insert reg1; 
        reg1.Status__c = 'Accepted';
        update reg1; 
                
        Report_Request__c reportReq = new Report_Request__c();
        reportReq.Report_Type__c = 'Patient Summary';
        reportReq.Status__c = 'In Progress';
        insert reportReq;
            
        PatientSummaryReport psrObject = new PatientSummaryReport();
        List<String> sis = new List<String>();
        sis.add(inst1.Id);
        psrObject.selectedInstitute = sis;
        
        List<String> tids = new List<String>();
        tids.add(tri.Id);
        psrObject.selectedTrial = tids;
        Apexpages.currentPage().getParameters().put('repReqId',reportReq.Id);
        psrObject.storePatientSummaryReport(reportReq.Id, new List<String>{tri.Id}, new List<String>{inst1.Id});
        
        psrObject.generatePatientSummaryReport();   
        
      }
   } 
}