src/objects/AE_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Hospitalized__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was patient hospitalized since the last AE report?</description>
        <inlineHelpText>Was patient hospitalized since the last AE report?</inlineHelpText>
        <label>Patient Hospitalized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>AE Details</relationshipLabel>
        <relationshipName>AE_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>AE Detail</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AE Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Agent__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Agent</label>
    <nameField>
        <label>Agent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Arm__c.object
<CustomObject>
    <label>Arm</label>
    <nameField>
        <label>Arm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Toxicity__c.object
<CustomObject>
    <fields>
        <fullName>AE_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Detail</label>
        <referenceTo>AE_Detail__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AE_End_Date__c</fullName>
        <label>AE End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Attribution__c</fullName>
        <label>Attribute</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Unrelated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Unlikely</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Possible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 - Probable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 - Definite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0 - Baseline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Onset_Date__c</fullName>
        <label>Onset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient_Complaint__c</fullName>
        <label>Patient Complaint</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Resolved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resolved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Toxicity_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Toxicity Agent</label>
        <referenceTo>Toxicity_Agent__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toxicity_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Toxicity Master</label>
        <referenceTo>Toxicity_Master__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toxicity_Status__c</fullName>
        <label>Toxicity Status</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Assessed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toxicity</label>
    <nameField>
        <label>Toxicity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toxicities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Toxicity_Agent__c.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipLabel>Toxicity Agents</relationshipLabel>
        <relationshipName>Toxicity_Agents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toxicity_Master__c</fullName>
        <label>Toxicity Master</label>
        <referenceTo>Toxicity_Master__c</referenceTo>
        <relationshipLabel>Toxicity Agents</relationshipLabel>
        <relationshipName>Toxicity_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Toxicity Agent</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Toxicity Agent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toxicity Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Toxicity_Master__c.object
<CustomObject>
    <fields>
        <fullName>Grade_1__c</fullName>
        <label>Grade 1</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grade_2__c</fullName>
        <label>Grade 2</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grade_3__c</fullName>
        <label>Grade 3</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grade_4__c</fullName>
        <label>Grade 4</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grade_5__c</fullName>
        <label>Grade 5</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Toxicity_Name__c</fullName>
        <label>Toxicity Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Toxicity Master</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Toxicity Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toxicity Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestToxicityAgentComponentClass.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestToxicityAgentComponentClass {

  
      @isTest static  void myUnitTest() {
        // TO DO: implement unit test
        
        List<User> lstSiteUser = [Select u.IsActive, u.Id From User u where IsActive = true and Profile.Name = 'System Administrator'];
        System.runAs ( lstSiteUser[0] ) { 
            
        Account acc = new Account();
        acc.Name = 'testting acc';
        insert acc;
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1950, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; 
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        insert tp;
        
        Agent__c agentObj = new Agent__c();
        agentObj.Name = 'test agent';
        agentObj.Display_Order__c = 0;
        insert agentObj; 
        
        Toxicity_Master__c tox = new Toxicity_Master__c();
        tox.Toxicity_Name__c = 'test1';
        tox.Grade_1__c = 'testing';
        tox.Grade_2__c = 'testing1';
        tox.Grade_3__c = 'testing3';
        tox.Grade_4__c = 'testing4';
        tox.Grade_5__c = 'testing5';
        insert tox;
        
        AE_Detail__c aedObj = new AE_Detail__c();
        aedObj.TrialPatient__c = tp.Id;
        aedObj.Visit_Date__c = date.newInstance(2012, 7, 7);
        aedObj.Patient_Hospitalized__c = true;
        insert aedObj;
        
        Arm__c armObj = new Arm__c();
        armObj.Name = 'test agent';
        insert armObj;
        
        Toxicity_Agent__c toxagentObj = new Toxicity_Agent__c ();
        toxagentObj.Toxicity_Master__c = tox.Id;
        toxagentObj.Agent__c = agentObj.Id;
        insert toxagentObj;
        
        Toxicity__c toxi1 = new Toxicity__c();
        toxi1.AE_Detail__c = aedObj.Id;
        toxi1.TrialPatient__c = tp.Id;
        toxi1.Resolved__c = true;
        toxi1.Onset_Date__c = system.today();
        toxi1.AE_End_Date__c = system.today();
        toxi1.Name = tox.Toxicity_Name__c;
        toxi1.Toxicity_Master__c = tox.Id;
        toxi1.Grade__c = 'testing';
        toxi1.Toxicity_Status__c = 'Yes';
        toxi1.Toxicity_Agent__c = toxagentObj.Id;
        toxi1.Attribution__c = '5 - Definite';
        toxi1.Patient_Complaint__c = 'test complain';
        insert toxi1;
        
        Apexpages.currentPage().getParameters().put('aeid',aedObj.Id);
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        ToxicityAgentComponentClass tacObj = new ToxicityAgentComponentClass();
        
        tacObj.aeid = aedObj.Id;
        tacObj.TreatmentArmId = armObj.Id;
        tacObj.trialPatId = tp.Id;
        
        tacObj.getLstWrapToxiAgent();
        
        Apexpages.currentPage().getParameters().put('toxAgentId',toxagentObj.Id);
        tacObj.saveToxicity();
        
        Apexpages.currentPage().getParameters().put('toxAgentId',toxagentObj.Id);
        tacObj.EditToxicity();
        
        Apexpages.currentPage().getParameters().put('toxAgentId',toxagentObj.Id);
        tacObj.updateCancelToxicity();
        
        Apexpages.currentPage().getParameters().put('toxAgentId',toxagentObj.Id);
        tacObj.removeToxicity(); 
        
        }
    }
  
        @isTest static void myUnitTest1() { // else if line 126 "toxi1.Toxicity_Status__c = 'No'"
        // TO DO: implement unit test
        
        List<User> lstSiteUser = [Select u.IsActive, u.Id From User u where IsActive = true and Profile.Name = 'System Administrator'];
        System.runAs ( lstSiteUser[0] ) { 
            
        Account acc = new Account();
        acc.Name = 'testting acc';
        insert acc;
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1950, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; 
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        insert tp;
        
        Agent__c agentObj = new Agent__c();
        agentObj.Name = 'test agent';
        agentObj.Display_Order__c = 0;
        insert agentObj; 
        
        Toxicity_Master__c tox = new Toxicity_Master__c();
        tox.Toxicity_Name__c = 'test1';
        tox.Grade_1__c = 'testing';
        tox.Grade_2__c = 'testing1';
        tox.Grade_3__c = 'testing3';
        tox.Grade_4__c = 'testing4';
        tox.Grade_5__c = 'testing5';
        insert tox;
        
        AE_Detail__c aedObj = new AE_Detail__c();
        aedObj.TrialPatient__c = tp.Id;
        aedObj.Visit_Date__c = date.newInstance(2012, 7, 7);
        aedObj.Patient_Hospitalized__c = true;
        insert aedObj;
        
        Arm__c armObj = new Arm__c();
        armObj.Name = 'test agent';
        insert armObj;
        
        Toxicity_Agent__c toxagentObj = new Toxicity_Agent__c ();
        toxagentObj.Toxicity_Master__c = tox.Id;
        toxagentObj.Agent__c = agentObj.Id;
        insert toxagentObj;
        
        Toxicity__c toxi1 = new Toxicity__c();
        toxi1.AE_Detail__c = aedObj.Id;
        toxi1.TrialPatient__c = tp.Id;
        toxi1.Resolved__c = true;
        toxi1.Onset_Date__c = system.today();
        toxi1.AE_End_Date__c = system.today();
        toxi1.Name = tox.Toxicity_Name__c;
        toxi1.Toxicity_Master__c = tox.Id;
        toxi1.Grade__c = 'testing';
        toxi1.Toxicity_Status__c = 'No';
        toxi1.Toxicity_Agent__c = toxagentObj.Id;
        toxi1.Attribution__c = '5 - Definite';
        toxi1.Patient_Complaint__c = 'test complain';
        insert toxi1;
        
        Apexpages.currentPage().getParameters().put('aeid',aedObj.Id);
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        ToxicityAgentComponentClass tacObj = new ToxicityAgentComponentClass();
        
        tacObj.aeid = aedObj.Id;
        tacObj.TreatmentArmId = armObj.Id;
        tacObj.trialPatId = tp.Id;
        
        tacObj.getLstWrapToxiAgent();
        
        Apexpages.currentPage().getParameters().put('toxAgentId',toxagentObj.Id);
        tacObj.saveToxicity();
        
        
        //============================else if line 155 "toxi.Toxicity_Status__c = 'Not assessed'"=============================
        
        Toxicity__c toxi = new Toxicity__c();
        toxi.AE_Detail__c = aedObj.Id;
        toxi.TrialPatient__c = tp.Id;
        toxi.Resolved__c = true;
        toxi.Onset_Date__c = system.today();
        toxi.AE_End_Date__c = system.today();
        toxi.Name = tox.Toxicity_Name__c;
        toxi.Toxicity_Master__c = tox.Id;
        toxi.Grade__c = 'testing';
        toxi.Toxicity_Status__c = 'Not assessed';
        toxi.Toxicity_Agent__c = toxagentObj.Id;
        toxi.Attribution__c = '5 - Definite';
        toxi.Patient_Complaint__c = 'test complain';
        insert toxi;
        
        Apexpages.currentPage().getParameters().put('aeid',aedObj.Id);
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        ToxicityAgentComponentClass tacObj1 = new ToxicityAgentComponentClass();
        
        tacObj1.aeid = aedObj.Id;
        tacObj1.TreatmentArmId = armObj.Id;
        tacObj1.trialPatId = tp.Id;
        
        tacObj1.getLstWrapToxiAgent();
        
        Apexpages.currentPage().getParameters().put('toxAgentId',toxagentObj.Id);
        tacObj1.saveToxicity(); 
        
        
        }
    }
}