src/objects/AE_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>AE Details</relationshipLabel>
        <relationshipName>AE_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>AE Detail</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AE Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Arm__c.object
<CustomObject>
    <label>Arm</label>
    <nameField>
        <label>Arm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ArmPatient__c.object
<CustomObject>
    <fields>
        <fullName>Arm_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Arm Id</label>
        <referenceTo>Arm__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <formula>TrialPatient__r.Subject_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subject Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ArmPatient</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Arm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ArmPatients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BaselineSymptomsForm__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Baseline Symptoms Forms</relationshipLabel>
        <relationshipName>Baseline_Symptoms_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>Baseline Symptoms Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Symptoms Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SymptomMaster__c.object
<CustomObject>
    <label>Symptom Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Symptom Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Toxicity__c.object
<CustomObject>
    <fields>
        <fullName>AE_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Detail</label>
        <referenceTo>AE_Detail__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AE_End_Date__c</fullName>
        <label>AE End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Baseline_Symptoms_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Baseline Symptoms Form</label>
        <referenceTo>BaselineSymptomsForm__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Onset_Date__c</fullName>
        <label>Onset Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient_Complaint__c</fullName>
        <label>Patient Complaint</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Resolved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Resolved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SAE__c</fullName>
        <label>SAE</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Symptom_Masters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Symptom Masters</label>
        <referenceTo>SymptomMaster__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toxicity_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Toxicity Master</label>
        <referenceTo>Toxicity_Master__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toxicity</label>
    <nameField>
        <label>Toxicity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toxicities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Toxicity_Master__c.object
<CustomObject>
    <label>Toxicity Master</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Toxicity Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toxicity Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AdverseEventReport_Refactored.cls
public with sharing class AdverseEventReport_Refactored {
    
    public void prepareTotalAdverseEvent() {
        
        //TODO: Report has to be executed for ALL or Selected patients. This is not handled yet.
        //TODO: CTCAEv4 Term, ascending
        
        //Selecct the baseline and ae forms which are approved.
        /*
        Date endDate = Date.valueOf(Apexpages.currentPage().getParameters().get('endDate'));
        Date startDate = Date.valueOf(Apexpages.currentPage().getParameters().get('startDate'));
        
        List<BaselineSymptomsForm__c> baseLineCRFList = [Select Id, Visit_Date__c,Status__c, (select id,Resolved__c,Toxicity_Master__c,Symptom_Masters__c,
        Symptom_Masters__r.Name, Onset_Date__c,AE_End_Date__c,SAE__c,Patient_Complaint__c from Toxicities__r 
                where AE_End_Date__c >= :startDate order by Onset_Date__c asc, AE_End_Date__c asc), 
                TrialPatient__c,TrialPatient__r.Subject_Id__c from BaselineSymptomsForm__c 
                where Visit_Date__c <= :endDate and Status__c = 'Accepted' order by Visit_Date__c asc];
                
        List<AE_Detail__c> aeCRFList = [Select Id, Visit_Date__c,Status__c, 
                    (select id,Resolved__c,Toxicity_Master__c,Symptom_Masters__c,Symptom_Masters__r.Name,Onset_Date__c,AE_End_Date__c,SAE__c, 
                    Patient_Complaint__c from Toxicities__r where (Onset_Date__c <= :endDate OR (AE_End_Date__c = null OR AE_End_Date__c >= :startDate)) 
                    order by Onset_Date__c asc, AE_End_Date__c asc), 
                    TrialPatient__c,TrialPatient__r.Subject_Id__c from AE_Detail__c where Status__c = 'Accepted' order by Visit_Date__c asc];
        
        //Collect trial patient ids for these baseline and ae forms
        Set<Id> trialPatientIds = new Set<Id>();
        for(BaselineSymptomsForm__c bsf : baseLineCRFList) {
            trialPatientIds.add(bsf.TrialPatient__c);
        }
        for(AE_Detail__c ae : aeCRFList) {
            trialPatientIds.add(ae.TrialPatient__c);
        }
        
        List<ArmPatient__c> armPatient = [Select a.TrialPatient__r.Resolved_AEs__c, a.TrialPatient__r.Unresolved_AEs__c, 
                    a.TrialPatient__r.Total_AEs__c, a.TrialPatient__r.Possible_SAEs__c, a.TrialPatient__r.Subject_Id__c, a.TrialPatient__c, 
                    a.Arm_Id__r.Name, a.Arm_Id__c From ArmPatient__c a where Id IN :trialPatientIds order by Arm_Id__r.Name asc];
        List<SummaryWrapper> lstSummaryWrapper = new List<SummaryWrapper>();
        Set<String> arms = new Set<String>();
        integer totalAEsForArm = 0;
        integer possibleSAEsForArm = 0;
        integer resolvedAEsForArm = 0;
        integer unresolvedAEsForArm = 0;
        SummaryWrapper tempSW = null;
        for(ArmPatient__c ap : armPatient) {
            SummaryWrapper sw = new SummaryWrapper();
            if(!arms.contains(ap.Arm_Id__r.Name)) {
                if(tempSW == null) tempSW = sw;
                arms.add(ap.Arm_Id__r.Name);
                
                sw.armOrSubject = ap.Arm_Id__r.Name;
                tempSW.totalAEs = totalAEsForArm;
                tempSW.possibleSAEs = possibleSAEsForArm;
                tempSW.resolvedAEs = resolvedAEsForArm; 
                tempSW.unresolvedAEs = unresolvedAEsForArm;
                
                tempSW = null;
                totalAEsForArm = 0;
                possibleSAEsForArm = 0;
                resolvedAEsForArm = 0;
                unresolvedAEsForArm = 0;
                
            } else {
                sw.armOrSubject = ap.TrialPatient__r.Subject_Id__c;
                sw.totalAEs = ap.TrialPatient__r.Total_AEs__c;
                sw.possibleSAEs = ap.TrialPatient__r.Possible_SAEs__c;
                sw.resolvedAEs = ap.TrialPatient__r.Resolved_AEs__c;
                sw.unresolvedAEs = ap.TrialPatient__r.Unresolved_AEs__c;
                
                totalAEsForArm += sw.totalAEs;
                possibleSAEsForArm += sw.possibleSAEs;
                resolvedAEsForArm += sw.resolvedAEs;
                unresolvedAEsForArm += sw.unresolvedAEs;
                
            }
            
            lstSummaryWrapper.add(sw);
        }*/
    }
    
    public class SummaryWrapper {
        public String armOrSubject {get;set;}
        public integer totalAEs {get;set;}
        public integer possibleSAEs {get;set;}
        public integer unresolvedAEs {get;set;}
        public integer resolvedAEs {get;set;}
        public boolean isArm {get;set;}
        public String rowColor {get;set;}
        
        public SummaryWrapper() {
            totalAEs = 0;
            possibleSAEs  = 0;
            unresolvedAEs = 0;
            resolvedAEs = 0;
            isArm = false;
        }
    }
}