src/objects/AE_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>AE Details</relationshipLabel>
        <relationshipName>AE_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Visit Date</label>
        <type>Date</type>
    </fields>
    <label>AE Detail</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AE Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/On_Study_Eligibility_Form__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>On Study Eligibility CRF</relationshipLabel>
        <relationshipName>On_Study_Eligibility_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>On Study Eligibility Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>On Study Eligibility Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On Study Eligibility Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CheckApprovalPendingStatus.cls
global class CheckApprovalPendingStatus implements Schedulable {

	//Run on 0th second of every minute
	public static String CRON_EXP = '0 5 * * * ?';
	 
	global void execute(SchedulableContext sc) {
		Map<Id, AE_Detail__c> aeMap = new Map<Id, AE_Detail__c>([Select a.Visit_Date__c, a.Status__c,a.TrialPatient__r.Subject_id__c From AE_Detail__c a where Status__c = 'Not Completed']);
		system.debug('Total AE forms with Not Completed status:'+aeMap.keySet().size());
      	List<ProcessInstance> piList = [Select p.TargetObjectId, p.Status, p.CreatedDate From ProcessInstance p where p.TargetObjectId in :aeMap.keySet() and Status = 'Pending'];
      	system.debug('Total AE records pending in approval process : '+piList.size());
      	String aeMessage = '<br/>AE forms having Not Completed status instead of Approval Pending<br/>';
      	boolean aeFound = false;
      	if(piList.size() != 0) {
      		List<AE_Detail__c> changeStatusList = new List<AE_Detail__c>();
      		for(ProcessInstance pi : piList) {
      			if(aeMap.containsKey(pi.TargetObjectId)) {
      				aeFound = true;
      				aeMessage += aeMap.get(pi.TargetObjectId).TrialPatient__r.Subject_id__c + ' - ' + aeMap.get(pi.TargetObjectId).Status__c + ' - ' + pi.TargetObjectId+'<br/>';
      				system.debug('aeMessage:'+aeMessage);
      				aeMap.get(pi.TargetObjectId).Status__c  = 'Approval Pending';
      				changeStatusList.add(aeMap.get(pi.TargetObjectId));
      			}
      		}
      		if(!changeStatusList.isEmpty()) {
      			update changeStatusList;
      		}
		}
		
		piList.clear();
		
		Map<Id, On_Study_Eligibility_Form__c> oseMap = new Map<Id, On_Study_Eligibility_Form__c>([Select Id, a.Status__c, a.TrialPatient__r.Subject_id__c From On_Study_Eligibility_Form__c a where Status__c = 'Not Completed']);
		system.debug('Total OSE forms with Not Completed status:'+oseMap.keySet().size());
      	piList = [Select p.TargetObjectId, p.Status, p.CreatedDate From ProcessInstance p where p.TargetObjectId in :oseMap.keySet() and Status = 'Pending'];
      	system.debug('Total OSE records pending in approval process : '+piList.size());
      	String oseMessage = '<br/>OSE forms having Not Completed status instead of Approval Pending<br/>';
      	boolean oseFound = false;
      	if(piList.size() != 0) {
      		List<On_Study_Eligibility_Form__c> changeStatusList = new List<On_Study_Eligibility_Form__c>();
      		for(ProcessInstance pi : piList) {
      			if(oseMap.containsKey(pi.TargetObjectId)) {
      				oseFound = true;
      				oseMessage += oseMap.get(pi.TargetObjectId).TrialPatient__r.Subject_id__c + ' - ' + oseMap.get(pi.TargetObjectId).Status__c + ' - ' + pi.TargetObjectId+'<br/>';
      				system.debug('oseMessage:'+oseMessage);
      				oseMap.get(pi.TargetObjectId).Status__c  = 'Approval Pending';
      				changeStatusList.add(oseMap.get(pi.TargetObjectId));
      			}
      		}
      		if(!changeStatusList.isEmpty()) {
      			update changeStatusList;
      		}
		}
		if(aeFound || oseFound) {
			Messaging.Singleemailmessage mail = new Messaging.Singleemailmessage();
	    	mail.setToAddresses(new List<String>{'patelb@opallios.com', 'ddumitru@blueoctave.com', 'zp@opallios.com', 'arorav@opallios.com'});
	    	mail.setReplyTo(Userinfo.getUserEmail());
	    	mail.setSenderDisplayName(Userinfo.getName());
		    mail.setSubject('Approval Request');
			
			mail.setHtmlBody(aeMessage + '<br/>' + oseMessage);
			System.debug('__mail__'+mail);
			Messaging.sendEmail(new Messaging.Singleemailmessage[] { mail });
		}
	}
}