src/objects/AE_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>AE Detail</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AE Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AE Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BaselineSymptomsForm__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Baseline Symptoms Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baseline Symptoms Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CTCAE_Code__c.object
<CustomObject>
    <fields>
        <fullName>AE_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Detail</label>
        <referenceTo>AE_Detail__c</referenceTo>
        <relationshipLabel>CTCAE Codes</relationshipLabel>
        <relationshipName>CTCAE_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Baseline_Symptoms_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Baseline Symptoms Form</label>
        <referenceTo>BaselineSymptomsForm__c</referenceTo>
        <relationshipLabel>CTCAE Codes</relationshipLabel>
        <relationshipName>CTCAE_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Toxicity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Toxicity</label>
        <referenceTo>Toxicity__c</referenceTo>
        <relationshipLabel>CTCAE Codes</relationshipLabel>
        <relationshipName>CTCAE_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTCAE Code</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTCAE Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CTCAECodeMaster__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Symptom_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Symptom Master</label>
        <referenceTo>SymptomMaster__c</referenceTo>
        <relationshipName>CTCAEMaster</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toxicity_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Toxicity Master</label>
        <referenceTo>Toxicity_Master__c</referenceTo>
        <relationshipName>CTCAEMaster</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CTCAECodeMaster</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>CTCAEMaster Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTCAECodeMaster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Toxicity__c.object
<CustomObject>
    <fields>
        <fullName>AE_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AE Detail</label>
        <referenceTo>AE_Detail__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Baseline_Symptoms_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Baseline Symptoms Form</label>
        <referenceTo>BaselineSymptomsForm__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CTCAE_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CTCAE Code</label>
        <referenceTo>CTCAE_Code__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Symptom_Masters__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Symptom Masters</label>
        <referenceTo>SymptomMaster__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Toxicity_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Toxicity Master</label>
        <referenceTo>Toxicity_Master__c</referenceTo>
        <relationshipLabel>Toxicities</relationshipLabel>
        <relationshipName>Toxicities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toxicity</label>
    <nameField>
        <label>Toxicity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toxicities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Toxicity_Master__c.object
<CustomObject>
    <fields>
        <fullName>Symptom_Master__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Symptom Master</label>
        <referenceTo>SymptomMaster__c</referenceTo>
        <relationshipLabel>Toxicity Masters</relationshipLabel>
        <relationshipName>Toxicity_Masters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Toxicity Master</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Toxicity Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Toxicity Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CTCAECodeManager.cls
public with sharing class CTCAECodeManager {
	static Map<String, String> mapCTCCode = new Map<String, String>();
	static {
		List<CTCAECodeMaster__c> lstCTCAECodeMaster = [Select c.Toxicity_Master__c, c.Symptom_Master__c, c.Code__c From CTCAECodeMaster__c c];
		for(CTCAECodeMaster__c ctcAe : lstCTCAECodeMaster) {
			mapCTCCode.put(ctcAe.Symptom_Master__c+'-'+ctcAe.Toxicity_Master__c, ctcAe.Code__c);
		}
	}
	
	public static String getCodeForSymptomAndToxicity(Id symptomId, Id toxicityId) {
		return mapCTCCode.get(symptomId+'-'+toxicityId);
	}
	
	public static void createCTCAECode(Set<Id> crfIds, String objectName) {
    	List<CTCAE_Code__c> lstCTCAECode = new List<CTCAE_Code__c>();
    	List<Sobject> lstSObject = Database.query('Select Status__c, Id, (Select Id, Toxicity_Master__c, Symptom_Masters__c, AE_Detail__c, Baseline_Symptoms_Form__c From Toxicities__r) From '+objectName+' where Id IN :crfIds and Status__c = \'Accepted\'');
    	for(Sobject sobj : lstSObject) {
    		List<Toxicity__c> lstToxicity = sobj.getSObjects('Toxicities__r');
    		if(lstToxicity == null) continue;
    		for(Toxicity__c t : lstToxicity) {
    			CTCAE_Code__c code = new CTCAE_Code__c();
    			if(objectName == 'BaselineSymptomsForm__c') {
					code.Baseline_Symptoms_Form__c = t.Baseline_Symptoms_Form__c;
    			}
    			if(objectName == 'AE_Detail__c') {
					code.AE_Detail__c = t.AE_Detail__c;
    			}
    			system.debug('t.Toxicity_Master__c: '+t.Toxicity_Master__c+', t.Symptom_Masters__c: '+t.Symptom_Masters__c);
				code.Code__c = CTCAECodeManager.getCodeForSymptomAndToxicity(t.Symptom_Masters__c, t.Toxicity_Master__c);
				code.Toxicity__c = t.Id;
				lstCTCAECode.add(code);
    		}
    	}
    	insert lstCTCAECode;
    }
	
}