src/objects/AnswerOption__c.object
<CustomObject>
    <fields>
        <fullName>ContextDataUnit__c</fullName>
        <label>ContextDataUnit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contextdata__c</fullName>
        <label>Contextdata</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuestionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Id</label>
        <referenceTo>QuestionAnswer__c</referenceTo>
        <relationshipLabel>AnswerOptions</relationshipLabel>
        <relationshipName>AnswerOptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AnswerOptions</label>
    <nameField>
        <displayFormat>Ans-{000000}</displayFormat>
        <label>AnswerOption</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AnswerOptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CRFAdditionalQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>QuestionAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question ID</label>
        <referenceTo>QuestionAnswer__c</referenceTo>
        <relationshipLabel>CRFAdditionalQuestion</relationshipLabel>
        <relationshipName>CRFAdditionalQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFAdditionalQuestion</relationshipLabel>
        <relationshipName>CRFAdditionalQuestion</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRFAdditionalQuestion</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFAdditionalQuestion</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lab_and_Test__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Lab and Tests</relationshipLabel>
        <relationshipName>Lab_and_Tests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lab and Test</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Lab and Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lab and Tests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/On_Study_Eligibility_Form__c.object
<CustomObject>
    <fields>
        <fullName>How_was_the_cancer_first_detected__c</fullName>
        <label>How was the cancer first detected?</label>
        <picklist>
            <picklistValues>
                <fullName>Self exam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical exam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screening mammogram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Screening MRI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>On Study Eligibility CRF</relationshipLabel>
        <relationshipName>On_Study_Eligibility_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>On Study Eligibility Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>On Study Eligibility Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On Study Eligibility Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QuestionAnswer__c.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>Agent__c</referenceTo>
        <relationshipName>QuestionAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AnswerType__c</fullName>
        <inlineHelpText>Please add comma separated values in AnswerOptions, if you are selecting Picklist and  Picklist (Multi-Select).</inlineHelpText>
        <label>Answer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist (Multi-Select)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TextArea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Arm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Arm</label>
        <referenceTo>Arm__c</referenceTo>
        <relationshipName>QuestionAnswers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Question</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Flexible Question Scheme</label>
    <nameField>
        <displayFormat>Que-{000000}</displayFormat>
        <label>Question Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flexible Question Scheme</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAdditionalQuestionControllerReadOnly.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAdditionalQuestionControllerReadOnly {

    @isTest static void AddQuesUnitTest() {
        
        Account acc = new Account();
        
        List<Account> lstAccount = [Select a.Id From Account a limit 1];
        
        if(lstAccount.isEmpty()) return;
            
        acc = lstAccount[0];
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Ethnicity__c = 'Hispanic or latino';
        p.Gender__c = 'female';
        p.Race__c = 'asian;indian';
        p.Last_Name__c = 'kumar';
        p.Status__c = 'approval not required';
        p.Birthdate__c = date.newInstance(1950, 08, 05);
        p.Institution__c = acc.Id;
        insert p;
        
        List<Patient_Custom__c> lstPatient = [select Name from Patient_Custom__c where Id = :P.Id];
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        tp.FirstName__c = 'a';
        tp.LastName__c = 'b';
        insert tp;
        
        On_Study_Eligibility_Form__c ose = new On_Study_Eligibility_Form__c();
        ose.TrialPatient__c = tp.Id;
        ose.How_was_the_cancer_first_detected__c = 'Clinical exam'; 
        ose.Status__c = 'Accepted';
        insert ose;
         
        
        Lab_and_Test__c labAndTest1 = new Lab_and_Test__c();
        labAndTest1.TrialPatient__c = tp.Id;
        insert labAndTest1;
        
        Lab_and_Test__c labAndTest = new Lab_and_Test__c();
        labAndTest.TrialPatient__c = tp.Id;
        insert labAndTest;
        System.debug('labAndTest.CreatedDate : '+labAndTest.CreatedDate);
        
        Arm__c arm = new Arm__c();
        arm.Name = 'Test Arm';
        insert arm;
        
        Agent__c agent = new Agent__c();
        agent.Name = 'Test Arm';
        insert agent;
        
        QuestionAnswer__c per_quesAns = new QuestionAnswer__c();
        per_quesAns.AnswerType__c = 'Boolean';
        per_quesAns.Agent__c = agent.Id; 
        per_quesAns.Question__c = 'test Question';
        per_quesAns.Type__c = 'Test';
        insert per_quesAns;
        
        QuestionAnswer__c per_quesAns1 = new QuestionAnswer__c();
        per_quesAns1.AnswerType__c = 'Boolean';
        per_quesAns1.Agent__c = agent.Id; 
        per_quesAns1.Question__c = 'test Question';
        per_quesAns1.Type__c = 'Test';
        insert per_quesAns1;
        
        AnswerOption__c ansOpt1 = new AnswerOption__c();
        ansOpt1.ContextDataUnit__c = 'test';
        //ansOpt1.Contextdata__c = 12;
        ansOpt1.QuestionId__c = per_quesAns.Id;
        insert ansOpt1;
        
        QuestionAnswer__c quesAnsc1 = new QuestionAnswer__c();
        quesAnsc1.AnswerType__c = 'Boolean';
        quesAnsc1.Agent__c = agent.Id; 
        quesAnsc1.Question__c = 'test Question';
        quesAnsc1.Type__c = 'Test';
        quesAnsc1.Parent_Question_Answer__c = per_quesAns.Id;
        insert quesAnsc1;
        
        QuestionAnswer__c quesAnsch1 = new QuestionAnswer__c();
        quesAnsch1.AnswerType__c = 'Picklist';
        quesAnsch1.Agent__c = agent.Id; 
        quesAnsch1.Question__c = 'test Question';
        quesAnsch1.Type__c = 'Test';
        quesAnsch1.PickList_Values__c = '345,345,43,543';
        quesAnsch1.Parent_Question_Answer__c = per_quesAns.Id;
        insert quesAnsch1;
        
        QuestionAnswer__c quesAnsch2 = new QuestionAnswer__c();
        quesAnsch2.AnswerType__c = 'Picklist (Multi-Select)';
        quesAnsch2.Agent__c = agent.Id; 
        quesAnsch2.Question__c = 'test Question';
        quesAnsch2.Type__c = 'Test';
        quesAnsch2.Parent_Question_Answer__c = per_quesAns.Id;
        quesAnsch2.PickList_Values__c = '345,345,43,543';
        insert quesAnsch2;
        
        QuestionAnswer__c quesAnsch3 = new QuestionAnswer__c();
        quesAnsch3.AnswerType__c = 'Text';
        quesAnsch3.Agent__c = agent.Id; 
        quesAnsch3.Question__c = 'test Question';
        quesAnsch3.Type__c = 'Test';
        quesAnsch3.Parent_Question_Answer__c = per_quesAns.Id;
        insert quesAnsch3;
        
        QuestionAnswer__c quesAnsch4 = new QuestionAnswer__c();
        quesAnsch4.AnswerType__c = 'TextArea';
        quesAnsch4.Agent__c = agent.Id; 
        quesAnsch4.Question__c = 'test Question';
        quesAnsch4.Type__c = 'Test';
        quesAnsch4.Parent_Question_Answer__c = per_quesAns.Id;
        insert quesAnsch4;
        
        QuestionAnswer__c quesAnsch5 = new QuestionAnswer__c();
        quesAnsch5.AnswerType__c = 'Date';
        quesAnsch5.Arm__c = arm.Id;
        quesAnsch5.Question__c = 'test Question';
        quesAnsch5.Type__c = 'Test';
        quesAnsch5.Parent_Question_Answer__c = per_quesAns.Id;
        quesAnsch5.Agent__c = agent.Id; 
        insert quesAnsch5;
        
        AnswerOption__c ansOptCh = new AnswerOption__c();
        ansOptCh.ContextDataUnit__c = 'test';
        //ansOptCh.Contextdata__c = 2;
        ansOptCh.QuestionId__c = quesAnsc1.Id;
        insert ansOptCh;
        
        QuestionAnswer__c quesAnsp2 = new QuestionAnswer__c();
        quesAnsp2.AnswerType__c = 'Text';
        quesAnsp2.Arm__c = arm.Id;
        quesAnsp2.Question__c = 'test Question';
        quesAnsp2.Type__c = 'Test';
        quesAnsp2.Agent__c = agent.Id; 
        insert quesAnsp2;
        
        QuestionAnswer__c quesAnsp3 = new QuestionAnswer__c();
        quesAnsp3.AnswerType__c = 'TextArea';
        quesAnsp3.Arm__c = arm.Id;
        quesAnsp3.Question__c = 'test Question';
        quesAnsp3.Type__c = 'Test';
        quesAnsp3.Agent__c = agent.Id; 
        insert quesAnsp3;
        
        QuestionAnswer__c quesAnsp4 = new QuestionAnswer__c();
        quesAnsp4.AnswerType__c = 'Picklist';
        quesAnsp4.Arm__c = arm.Id;
        quesAnsp4.Question__c = 'test';
        quesAnsp4.PickList_Values__c = '123,123,123,123';
        quesAnsp4.Type__c = 'Test';
        quesAnsp4.Agent__c = agent.Id; 
        insert quesAnsp4;
        
        AnswerOption__c ansOptCh4 = new AnswerOption__c();
        ansOptCh4.ContextDataUnit__c = 'test';
        //ansOptCh.Contextdata__c = 2;
        ansOptCh4.QuestionId__c = quesAnsp4.Id;
        insert ansOptCh4;
        
        QuestionAnswer__c quesAnsp5 = new QuestionAnswer__c();
        quesAnsp5.AnswerType__c = 'Picklist (Multi-Select)';
        quesAnsp5.Arm__c = arm.Id;
        quesAnsp5.Question__c = 'test';
        quesAnsp5.PickList_Values__c = '123,123,123,123';
        quesAnsp5.Type__c = 'Test';
        quesAnsp5.Agent__c = agent.Id;      
        insert quesAnsp5;
        
        AnswerOption__c ansOptCh5 = new AnswerOption__c();
        ansOptCh5.ContextDataUnit__c = 'test';
        //ansOptCh.Contextdata__c = 2;
        ansOptCh5.QuestionId__c = quesAnsp5.Id;
        insert ansOptCh5;
        
        System.debug('quesAnsp5.CreatedDate : '+quesAnsp5.CreatedDate);
        
        QuestionAnswer__c quesAnsp6 = new QuestionAnswer__c();
        quesAnsp6.AnswerType__c = 'Date';
        quesAnsp6.Arm__c = arm.Id;
        quesAnsp6.Question__c = 'test Question';
        quesAnsp6.Type__c = 'Test';
        quesAnsp6.Agent__c = agent.Id; 
        insert quesAnsp6;
        
        CRFAdditionalQuestion__c crfAddQues = new CRFAdditionalQuestion__c();
        crfAddQues.CRFId__c = labAndTest.Id;
        crfAddQues.QuestionAnswer__c = quesAnsp6.Id;
        crfAddQues.Answer__c = String.valueOf(System.today());
        insert crfAddQues;
        
        AnswerOption__c CRFansOpt = new AnswerOption__c();
        CRFansOpt.ContextDataUnit__c = 'test';
        CRFansOpt.CRFAdditionalQuestion__c = crfAddQues.Id;
        insert CRFansOpt;
        
        CRFAdditionalQuestion__c crfAddQues1 = new CRFAdditionalQuestion__c();
        crfAddQues1.CRFId__c = labAndTest.Id;
        crfAddQues1.QuestionAnswer__c = quesAnsp4.Id;
        crfAddQues1.Answer__c = 'Test';
        insert crfAddQues1;
        
        CRFAdditionalQuestion__c crfAddQues5 = new CRFAdditionalQuestion__c();
        crfAddQues5.CRFId__c = labAndTest.Id;
        crfAddQues5.QuestionAnswer__c = quesAnsp5.Id;
        crfAddQues5.Answer__c = 'Test';
        insert crfAddQues5;
        
        CRFAdditionalQuestion__c crfAddQues2 = new CRFAdditionalQuestion__c();
        crfAddQues2.CRFId__c = labAndTest.Id;
        crfAddQues2.QuestionAnswer__c = quesAnsp2.Id;
        crfAddQues2.Answer__c = 'Test';
        insert crfAddQues2;
        
        CRFAdditionalQuestion__c crfAddQues3 = new CRFAdditionalQuestion__c();
        crfAddQues3.CRFId__c = labAndTest.Id;
        crfAddQues3.QuestionAnswer__c = quesAnsp3.Id;
        crfAddQues3.Answer__c = 'Test';
        insert crfAddQues3;
        
        CRFAdditionalQuestion__c crfAddQues7 = new CRFAdditionalQuestion__c();
        crfAddQues7.CRFId__c = labAndTest.Id;
        crfAddQues7.QuestionAnswer__c = per_quesAns.Id;
        crfAddQues7.Answer__c = 'Test';
        insert crfAddQues7;
        
        
        AdditionalQuestionControllerReadOnly addQuesCon2 = new AdditionalQuestionControllerReadOnly();
        addQuesCon2.getlstQuesAnsWrapper();
        
        /*addQuesCon2.Questiontype = 'Test';
        addQuesCon2.CRFType = '00055';
        addQuesCon2.isReadOnly = true;
        addQuesCon2.CRFId = labAndTest.Id;
        addQuesCon2.armId = arm.Id;
        addQuesCon2.Questiontype = 'Test'; 
        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
        
        addQuesCon2.saveComponent(labAndTest.Id);
        addQuesCon2.CRFId = labAndTest.Id;
        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
        addQuesCon2.setlstQuesAnsWrapper(addQuesCon2.lstQuesAnsWrapper);
        addQuesCon2.saveComponent(labAndTest.Id);
        
        AdditionalQuestionControllerReadOnly addQuesCon3 = new AdditionalQuestionControllerReadOnly();
        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
        addQuesCon3.Questiontype = 'Test';
        addQuesCon3.CRFType = '00055';
        addQuesCon3.CRFId = ose.Id;
        addQuesCon3.armId = arm.Id;
        addQuesCon3.Questiontype = 'Test'; 
        addQuesCon3.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();*/
        
    }
    
        @isTest static void AddQuesUnitTest1() {
        
	        Account acc = new Account();
	        
	        List<Account> lstAccount = [Select a.Id From Account a limit 1];
	        
	        if(lstAccount.isEmpty()) return;
	            
	        acc = lstAccount[0];
	        
	        Patient_Custom__c p = new Patient_Custom__c();
	        p.Ethnicity__c = 'Hispanic or latino';
	        p.Gender__c = 'female';
	        p.Race__c = 'asian;indian';
	        p.Last_Name__c = 'kumar';
	        p.Status__c = 'approval not required';
	        p.Birthdate__c = date.newInstance(1950, 08, 05);
	        p.Institution__c = acc.Id;
	        insert p;
	        
	        List<Patient_Custom__c> lstPatient = [select Name from Patient_Custom__c where Id = :P.Id];
	        
	        TrialPatient__c tp = new TrialPatient__c();
	        tp.Patient_Id__c = p.Id;
	        tp.FirstName__c = 'a';
	        tp.LastName__c = 'b';
	        insert tp;
	        
	        On_Study_Eligibility_Form__c ose = new On_Study_Eligibility_Form__c();
	        ose.TrialPatient__c = tp.Id;
	        ose.How_was_the_cancer_first_detected__c = 'Clinical exam'; 
	        ose.Status__c = 'Accepted';
	        insert ose;
	         
	        
	        Lab_and_Test__c labAndTest1 = new Lab_and_Test__c();
	        labAndTest1.TrialPatient__c = tp.Id;
	        insert labAndTest1;
	        
	        Lab_and_Test__c labAndTest = new Lab_and_Test__c();
	        labAndTest.TrialPatient__c = tp.Id;
	        insert labAndTest;
	        System.debug('labAndTest.CreatedDate : '+labAndTest.CreatedDate);
	        
	        Arm__c arm = new Arm__c();
	        arm.Name = 'Test Arm';
	        insert arm;
	        
	        Agent__c agent = new Agent__c();
	        agent.Name = 'Test Arm';
	        insert agent;
	        
	        QuestionAnswer__c per_quesAns = new QuestionAnswer__c();
	        per_quesAns.AnswerType__c = 'Boolean';
	        per_quesAns.Agent__c = agent.Id; 
	        per_quesAns.Question__c = 'test Question';
	        per_quesAns.Type__c = 'Test';
	        insert per_quesAns;
	        
	        QuestionAnswer__c per_quesAns1 = new QuestionAnswer__c();
	        per_quesAns1.AnswerType__c = 'Boolean';
	        per_quesAns1.Agent__c = agent.Id; 
	        per_quesAns1.Question__c = 'test Question';
	        per_quesAns1.Type__c = 'Test';
	        insert per_quesAns1;
	        
	        AnswerOption__c ansOpt1 = new AnswerOption__c();
	        ansOpt1.ContextDataUnit__c = 'test';
	        //ansOpt1.Contextdata__c = 12;
	        ansOpt1.QuestionId__c = per_quesAns.Id;
	        insert ansOpt1;
	        
	        QuestionAnswer__c quesAnsc1 = new QuestionAnswer__c();
	        quesAnsc1.AnswerType__c = 'Boolean';
	        quesAnsc1.Agent__c = agent.Id; 
	        quesAnsc1.Question__c = 'test Question';
	        quesAnsc1.Type__c = 'Test';
	        quesAnsc1.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsc1;
	        
	        QuestionAnswer__c quesAnsch1 = new QuestionAnswer__c();
	        quesAnsch1.AnswerType__c = 'Picklist';
	        quesAnsch1.Agent__c = agent.Id; 
	        quesAnsch1.Question__c = 'test Question';
	        quesAnsch1.Type__c = 'Test';
	        quesAnsch1.PickList_Values__c = '345,345,43,543';
	        quesAnsch1.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsch1;
	        
	        QuestionAnswer__c quesAnsch2 = new QuestionAnswer__c();
	        quesAnsch2.AnswerType__c = 'Picklist (Multi-Select)';
	        quesAnsch2.Agent__c = agent.Id; 
	        quesAnsch2.Question__c = 'test Question';
	        quesAnsch2.Type__c = 'Test';
	        quesAnsch2.Parent_Question_Answer__c = per_quesAns.Id;
	        quesAnsch2.PickList_Values__c = '345,345,43,543';
	        insert quesAnsch2;
	        
	        QuestionAnswer__c quesAnsch3 = new QuestionAnswer__c();
	        quesAnsch3.AnswerType__c = 'Text';
	        quesAnsch3.Agent__c = agent.Id; 
	        quesAnsch3.Question__c = 'test Question';
	        quesAnsch3.Type__c = 'Test';
	        quesAnsch3.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsch3;
	        
	        QuestionAnswer__c quesAnsch4 = new QuestionAnswer__c();
	        quesAnsch4.AnswerType__c = 'TextArea';
	        quesAnsch4.Agent__c = agent.Id; 
	        quesAnsch4.Question__c = 'test Question';
	        quesAnsch4.Type__c = 'Test';
	        quesAnsch4.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsch4;
	        
	        QuestionAnswer__c quesAnsch5 = new QuestionAnswer__c();
	        quesAnsch5.AnswerType__c = 'Date';
	        quesAnsch5.Arm__c = arm.Id;
	        quesAnsch5.Question__c = 'test Question';
	        quesAnsch5.Type__c = 'Test';
	        quesAnsch5.Parent_Question_Answer__c = per_quesAns.Id;
	        quesAnsch5.Agent__c = agent.Id; 
	        insert quesAnsch5;
	        
	        AnswerOption__c ansOptCh = new AnswerOption__c();
	        ansOptCh.ContextDataUnit__c = 'test';
	        //ansOptCh.Contextdata__c = 2;
	        ansOptCh.QuestionId__c = quesAnsc1.Id;
	        insert ansOptCh;
	        
	        QuestionAnswer__c quesAnsp2 = new QuestionAnswer__c();
	        quesAnsp2.AnswerType__c = 'Text';
	        quesAnsp2.Arm__c = arm.Id;
	        quesAnsp2.Question__c = 'test Question';
	        quesAnsp2.Type__c = 'Test';
	        quesAnsp2.Agent__c = agent.Id; 
	        insert quesAnsp2;
	        
	        QuestionAnswer__c quesAnsp3 = new QuestionAnswer__c();
	        quesAnsp3.AnswerType__c = 'TextArea';
	        quesAnsp3.Arm__c = arm.Id;
	        quesAnsp3.Question__c = 'test Question';
	        quesAnsp3.Type__c = 'Test';
	        quesAnsp3.Agent__c = agent.Id; 
	        insert quesAnsp3;
	        
	        QuestionAnswer__c quesAnsp4 = new QuestionAnswer__c();
	        quesAnsp4.AnswerType__c = 'Picklist';
	        quesAnsp4.Arm__c = arm.Id;
	        quesAnsp4.Question__c = 'test';
	        quesAnsp4.PickList_Values__c = '123,123,123,123';
	        quesAnsp4.Type__c = 'Test';
	        quesAnsp4.Agent__c = agent.Id; 
	        insert quesAnsp4;
	        
	        AnswerOption__c ansOptCh4 = new AnswerOption__c();
	        ansOptCh4.ContextDataUnit__c = 'test';
	        //ansOptCh.Contextdata__c = 2;
	        ansOptCh4.QuestionId__c = quesAnsp4.Id;
	        insert ansOptCh4;
	        
	        QuestionAnswer__c quesAnsp5 = new QuestionAnswer__c();
	        quesAnsp5.AnswerType__c = 'Picklist (Multi-Select)';
	        quesAnsp5.Arm__c = arm.Id;
	        quesAnsp5.Question__c = 'test';
	        quesAnsp5.PickList_Values__c = '123,123,123,123';
	        quesAnsp5.Type__c = 'Test';
	        quesAnsp5.Agent__c = agent.Id;      
	        insert quesAnsp5;
	        
	        AnswerOption__c ansOptCh5 = new AnswerOption__c();
	        ansOptCh5.ContextDataUnit__c = 'test';
	        //ansOptCh.Contextdata__c = 2;
	        ansOptCh5.QuestionId__c = quesAnsp5.Id;
	        insert ansOptCh5;
	        
	        System.debug('quesAnsp5.CreatedDate : '+quesAnsp5.CreatedDate);
	        
	        QuestionAnswer__c quesAnsp6 = new QuestionAnswer__c();
	        quesAnsp6.AnswerType__c = 'Date';
	        quesAnsp6.Arm__c = arm.Id;
	        quesAnsp6.Question__c = 'test Question';
	        quesAnsp6.Type__c = 'Test';
	        quesAnsp6.Agent__c = agent.Id; 
	        insert quesAnsp6;
	        
	        CRFAdditionalQuestion__c crfAddQues = new CRFAdditionalQuestion__c();
	        crfAddQues.CRFId__c = labAndTest.Id;
	        crfAddQues.QuestionAnswer__c = quesAnsp6.Id;
	        crfAddQues.Answer__c = String.valueOf(System.today());
	        insert crfAddQues;
	        
	        AnswerOption__c CRFansOpt = new AnswerOption__c();
	        CRFansOpt.ContextDataUnit__c = 'test';
	        CRFansOpt.CRFAdditionalQuestion__c = crfAddQues.Id;
	        insert CRFansOpt;
	        
	        CRFAdditionalQuestion__c crfAddQues1 = new CRFAdditionalQuestion__c();
	        crfAddQues1.CRFId__c = labAndTest.Id;
	        crfAddQues1.QuestionAnswer__c = quesAnsp4.Id;
	        crfAddQues1.Answer__c = 'Test';
	        insert crfAddQues1;
	        
	        CRFAdditionalQuestion__c crfAddQues5 = new CRFAdditionalQuestion__c();
	        crfAddQues5.CRFId__c = labAndTest.Id;
	        crfAddQues5.QuestionAnswer__c = quesAnsp5.Id;
	        crfAddQues5.Answer__c = 'Test';
	        insert crfAddQues5;
	        
	        CRFAdditionalQuestion__c crfAddQues2 = new CRFAdditionalQuestion__c();
	        crfAddQues2.CRFId__c = labAndTest.Id;
	        crfAddQues2.QuestionAnswer__c = quesAnsp2.Id;
	        crfAddQues2.Answer__c = 'Test';
	        insert crfAddQues2;
	        
	        CRFAdditionalQuestion__c crfAddQues3 = new CRFAdditionalQuestion__c();
	        crfAddQues3.CRFId__c = labAndTest.Id;
	        crfAddQues3.QuestionAnswer__c = quesAnsp3.Id;
	        crfAddQues3.Answer__c = 'Test';
	        insert crfAddQues3;
	        
	        CRFAdditionalQuestion__c crfAddQues7 = new CRFAdditionalQuestion__c();
	        crfAddQues7.CRFId__c = labAndTest.Id;
	        crfAddQues7.QuestionAnswer__c = per_quesAns.Id;
	        crfAddQues7.Answer__c = 'Test';
	        insert crfAddQues7;
	        
	        
	        AdditionalQuestionControllerReadOnly addQuesCon2 = new AdditionalQuestionControllerReadOnly();
	        addQuesCon2.Questiontype = 'Test';
	        addQuesCon2.CRFType = '00055';
	        addQuesCon2.isReadOnly = true;
	        addQuesCon2.CRFId = labAndTest.Id;
	        addQuesCon2.armId = arm.Id;
	        addQuesCon2.Questiontype = 'Test'; 
	        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
	        
	        /*addQuesCon2.saveComponent(labAndTest.Id);
	        addQuesCon2.CRFId = labAndTest.Id;
	        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
	        addQuesCon2.setlstQuesAnsWrapper(addQuesCon2.lstQuesAnsWrapper);
	        addQuesCon2.saveComponent(labAndTest.Id);
	        
	        AdditionalQuestionControllerReadOnly addQuesCon3 = new AdditionalQuestionControllerReadOnly();
	        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
	        addQuesCon3.Questiontype = 'Test';
	        addQuesCon3.CRFType = '00055';
	        addQuesCon3.CRFId = ose.Id;
	        addQuesCon3.armId = arm.Id;
	        addQuesCon3.Questiontype = 'Test'; 
	        addQuesCon3.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();*/
        
    	}
    	
    	@isTest static void AddQuesUnitTest2() {
        
	        Account acc = new Account();
	        
	        List<Account> lstAccount = [Select a.Id From Account a limit 1];
	        
	        if(lstAccount.isEmpty()) return;
	            
	        acc = lstAccount[0];
	        
	        Patient_Custom__c p = new Patient_Custom__c();
	        p.Ethnicity__c = 'Hispanic or latino';
	        p.Gender__c = 'female';
	        p.Race__c = 'asian;indian';
	        p.Last_Name__c = 'kumar';
	        p.Status__c = 'approval not required';
	        p.Birthdate__c = date.newInstance(1950, 08, 05);
	        p.Institution__c = acc.Id;
	        insert p;
	        
	        List<Patient_Custom__c> lstPatient = [select Name from Patient_Custom__c where Id = :P.Id];
	        
	        TrialPatient__c tp = new TrialPatient__c();
	        tp.Patient_Id__c = p.Id;
	        tp.FirstName__c = 'a';
	        tp.LastName__c = 'b';
	        insert tp;
	        
	        On_Study_Eligibility_Form__c ose = new On_Study_Eligibility_Form__c();
	        ose.TrialPatient__c = tp.Id;
	        ose.How_was_the_cancer_first_detected__c = 'Clinical exam'; 
	        ose.Status__c = 'Accepted';
	        insert ose;
	         
	        
	        Lab_and_Test__c labAndTest1 = new Lab_and_Test__c();
	        labAndTest1.TrialPatient__c = tp.Id;
	        insert labAndTest1;
	        
	        Lab_and_Test__c labAndTest = new Lab_and_Test__c();
	        labAndTest.TrialPatient__c = tp.Id;
	        insert labAndTest;
	        System.debug('labAndTest.CreatedDate : '+labAndTest.CreatedDate);
	        
	        Arm__c arm = new Arm__c();
	        arm.Name = 'Test Arm';
	        insert arm;
	        
	        Agent__c agent = new Agent__c();
	        agent.Name = 'Test Arm';
	        insert agent;
	        
	        QuestionAnswer__c per_quesAns = new QuestionAnswer__c();
	        per_quesAns.AnswerType__c = 'Boolean';
	        per_quesAns.Agent__c = agent.Id; 
	        per_quesAns.Question__c = 'test Question';
	        per_quesAns.Type__c = 'Test';
	        insert per_quesAns;
	        
	        QuestionAnswer__c per_quesAns1 = new QuestionAnswer__c();
	        per_quesAns1.AnswerType__c = 'Boolean';
	        per_quesAns1.Agent__c = agent.Id; 
	        per_quesAns1.Question__c = 'test Question';
	        per_quesAns1.Type__c = 'Test';
	        insert per_quesAns1;
	        
	        AnswerOption__c ansOpt1 = new AnswerOption__c();
	        ansOpt1.ContextDataUnit__c = 'test';
	        //ansOpt1.Contextdata__c = 12;
	        ansOpt1.QuestionId__c = per_quesAns.Id;
	        insert ansOpt1;
	        
	        QuestionAnswer__c quesAnsc1 = new QuestionAnswer__c();
	        quesAnsc1.AnswerType__c = 'Boolean';
	        quesAnsc1.Agent__c = agent.Id; 
	        quesAnsc1.Question__c = 'test Question';
	        quesAnsc1.Type__c = 'Test';
	        quesAnsc1.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsc1;
	        
	        QuestionAnswer__c quesAnsch1 = new QuestionAnswer__c();
	        quesAnsch1.AnswerType__c = 'Picklist';
	        quesAnsch1.Agent__c = agent.Id; 
	        quesAnsch1.Question__c = 'test Question';
	        quesAnsch1.Type__c = 'Test';
	        quesAnsch1.PickList_Values__c = '345,345,43,543';
	        quesAnsch1.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsch1;
	        
	        QuestionAnswer__c quesAnsch2 = new QuestionAnswer__c();
	        quesAnsch2.AnswerType__c = 'Picklist (Multi-Select)';
	        quesAnsch2.Agent__c = agent.Id; 
	        quesAnsch2.Question__c = 'test Question';
	        quesAnsch2.Type__c = 'Test';
	        quesAnsch2.Parent_Question_Answer__c = per_quesAns.Id;
	        quesAnsch2.PickList_Values__c = '345,345,43,543';
	        insert quesAnsch2;
	        
	        QuestionAnswer__c quesAnsch3 = new QuestionAnswer__c();
	        quesAnsch3.AnswerType__c = 'Text';
	        quesAnsch3.Agent__c = agent.Id; 
	        quesAnsch3.Question__c = 'test Question';
	        quesAnsch3.Type__c = 'Test';
	        quesAnsch3.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsch3;
	        
	        QuestionAnswer__c quesAnsch4 = new QuestionAnswer__c();
	        quesAnsch4.AnswerType__c = 'TextArea';
	        quesAnsch4.Agent__c = agent.Id; 
	        quesAnsch4.Question__c = 'test Question';
	        quesAnsch4.Type__c = 'Test';
	        quesAnsch4.Parent_Question_Answer__c = per_quesAns.Id;
	        insert quesAnsch4;
	        
	        QuestionAnswer__c quesAnsch5 = new QuestionAnswer__c();
	        quesAnsch5.AnswerType__c = 'Date';
	        quesAnsch5.Arm__c = arm.Id;
	        quesAnsch5.Question__c = 'test Question';
	        quesAnsch5.Type__c = 'Test';
	        quesAnsch5.Parent_Question_Answer__c = per_quesAns.Id;
	        quesAnsch5.Agent__c = agent.Id; 
	        insert quesAnsch5;
	        
	        AnswerOption__c ansOptCh = new AnswerOption__c();
	        ansOptCh.ContextDataUnit__c = 'test';
	        //ansOptCh.Contextdata__c = 2;
	        ansOptCh.QuestionId__c = quesAnsc1.Id;
	        insert ansOptCh;
	        
	        QuestionAnswer__c quesAnsp2 = new QuestionAnswer__c();
	        quesAnsp2.AnswerType__c = 'Text';
	        quesAnsp2.Arm__c = arm.Id;
	        quesAnsp2.Question__c = 'test Question';
	        quesAnsp2.Type__c = 'Test';
	        quesAnsp2.Agent__c = agent.Id; 
	        insert quesAnsp2;
	        
	        QuestionAnswer__c quesAnsp3 = new QuestionAnswer__c();
	        quesAnsp3.AnswerType__c = 'TextArea';
	        quesAnsp3.Arm__c = arm.Id;
	        quesAnsp3.Question__c = 'test Question';
	        quesAnsp3.Type__c = 'Test';
	        quesAnsp3.Agent__c = agent.Id; 
	        insert quesAnsp3;
	        
	        QuestionAnswer__c quesAnsp4 = new QuestionAnswer__c();
	        quesAnsp4.AnswerType__c = 'Picklist';
	        quesAnsp4.Arm__c = arm.Id;
	        quesAnsp4.Question__c = 'test';
	        quesAnsp4.PickList_Values__c = '123,123,123,123';
	        quesAnsp4.Type__c = 'Test';
	        quesAnsp4.Agent__c = agent.Id; 
	        insert quesAnsp4;
	        
	        AnswerOption__c ansOptCh4 = new AnswerOption__c();
	        ansOptCh4.ContextDataUnit__c = 'test';
	        //ansOptCh.Contextdata__c = 2;
	        ansOptCh4.QuestionId__c = quesAnsp4.Id;
	        insert ansOptCh4;
	        
	        QuestionAnswer__c quesAnsp5 = new QuestionAnswer__c();
	        quesAnsp5.AnswerType__c = 'Picklist (Multi-Select)';
	        quesAnsp5.Arm__c = arm.Id;
	        quesAnsp5.Question__c = 'test';
	        quesAnsp5.PickList_Values__c = '123,123,123,123';
	        quesAnsp5.Type__c = 'Test';
	        quesAnsp5.Agent__c = agent.Id;      
	        insert quesAnsp5;
	        
	        AnswerOption__c ansOptCh5 = new AnswerOption__c();
	        ansOptCh5.ContextDataUnit__c = 'test';
	        //ansOptCh.Contextdata__c = 2;
	        ansOptCh5.QuestionId__c = quesAnsp5.Id;
	        insert ansOptCh5;
	        
	        System.debug('quesAnsp5.CreatedDate : '+quesAnsp5.CreatedDate);
	        
	        QuestionAnswer__c quesAnsp6 = new QuestionAnswer__c();
	        quesAnsp6.AnswerType__c = 'Date';
	        quesAnsp6.Arm__c = arm.Id;
	        quesAnsp6.Question__c = 'test Question';
	        quesAnsp6.Type__c = 'Test';
	        quesAnsp6.Agent__c = agent.Id; 
	        insert quesAnsp6;
	        
	        CRFAdditionalQuestion__c crfAddQues = new CRFAdditionalQuestion__c();
	        crfAddQues.CRFId__c = labAndTest.Id;
	        crfAddQues.QuestionAnswer__c = quesAnsp6.Id;
	        crfAddQues.Answer__c = String.valueOf(System.today());
	        insert crfAddQues;
	        
	        AnswerOption__c CRFansOpt = new AnswerOption__c();
	        CRFansOpt.ContextDataUnit__c = 'test';
	        CRFansOpt.CRFAdditionalQuestion__c = crfAddQues.Id;
	        insert CRFansOpt;
	        
	        CRFAdditionalQuestion__c crfAddQues1 = new CRFAdditionalQuestion__c();
	        crfAddQues1.CRFId__c = labAndTest.Id;
	        crfAddQues1.QuestionAnswer__c = quesAnsp4.Id;
	        crfAddQues1.Answer__c = 'Test';
	        insert crfAddQues1;
	        
	        CRFAdditionalQuestion__c crfAddQues5 = new CRFAdditionalQuestion__c();
	        crfAddQues5.CRFId__c = labAndTest.Id;
	        crfAddQues5.QuestionAnswer__c = quesAnsp5.Id;
	        crfAddQues5.Answer__c = 'Test';
	        insert crfAddQues5;
	        
	        CRFAdditionalQuestion__c crfAddQues2 = new CRFAdditionalQuestion__c();
	        crfAddQues2.CRFId__c = labAndTest.Id;
	        crfAddQues2.QuestionAnswer__c = quesAnsp2.Id;
	        crfAddQues2.Answer__c = 'Test';
	        insert crfAddQues2;
	        
	        CRFAdditionalQuestion__c crfAddQues3 = new CRFAdditionalQuestion__c();
	        crfAddQues3.CRFId__c = labAndTest.Id;
	        crfAddQues3.QuestionAnswer__c = quesAnsp3.Id;
	        crfAddQues3.Answer__c = 'Test';
	        insert crfAddQues3;
	        
	        CRFAdditionalQuestion__c crfAddQues7 = new CRFAdditionalQuestion__c();
	        crfAddQues7.CRFId__c = labAndTest.Id;
	        crfAddQues7.QuestionAnswer__c = per_quesAns.Id;
	        crfAddQues7.Answer__c = 'Test';
	        insert crfAddQues7;
	        
	        
	        AdditionalQuestionControllerReadOnly addQuesCon2 = new AdditionalQuestionControllerReadOnly();
	        addQuesCon2.saveComponent(labAndTest.Id);
	        addQuesCon2.CRFId = labAndTest.Id;
	        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
	        addQuesCon2.setlstQuesAnsWrapper(addQuesCon2.lstQuesAnsWrapper);
	        addQuesCon2.saveComponent(labAndTest.Id);
	        
	        /*AdditionalQuestionControllerReadOnly addQuesCon3 = new AdditionalQuestionControllerReadOnly();
	        addQuesCon2.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();
	        addQuesCon3.Questiontype = 'Test';
	        addQuesCon3.CRFType = '00055';
	        addQuesCon3.CRFId = ose.Id;
	        addQuesCon3.armId = arm.Id;
	        addQuesCon3.Questiontype = 'Test'; 
	        addQuesCon3.lstQuesAnsWrapper = addQuesCon2.getlstQuesAnsWrapper();*/
        
    	}
}