src/objects/Arm__c.object
<CustomObject>
    <label>Arm</label>
    <nameField>
        <label>Arm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>OriginalCRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriginalCRF</label>
        <referenceTo>Off_Study_Detail__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Randomization_Form__c.object
<CustomObject>
    <fields>
        <fullName>OriginalCRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriginalCRF</label>
        <referenceTo>Randomization_Form__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Randomization Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Randomization Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScheduleManager.cls
public with sharing class ScheduleManager {
	public static void generateSchedule(ARM__c armObj, TrialPatient__c trailPatObj) {
		if(trailPatObj != null) {
			//List<Randomization_Form__c> lstRandomization = [select Id from Randomization_Form__c where TrialPatient__c =:trailPatObj.Id];
			List<TrialPatient__c> lstTrialPatient = [Select (select Id From Randomization_Forms__r), (select Id From Off_Study_Details__r) From TrialPatient__c t where Id =:trailPatObj.Id];
			if(!lstTrialPatient.isEmpty() && !lstTrialPatient[0].Randomization_Forms__r.isEmpty() && lstTrialPatient[0].Off_Study_Details__r.isEmpty()) {
				/*commented to get characters for other coding
				TaskManager.createTaskAfterRandomzation(new Set<Id>{trailPatObj.Id});
				*/
			}
		}
	}
}