src/objects/Arm__c.object
<CustomObject>
    <label>Arm</label>
    <nameField>
        <label>Arm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ArmPatient__c.object
<CustomObject>
    <fields>
        <fullName>Arm_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Arm Id</label>
        <referenceTo>Arm__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Id</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <formula>TrialPatient__r.Subject_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subject Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ArmPatient</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Arm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ArmPatients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Randomization_Form__c.object
<CustomObject>
    <fields>
        <fullName>Did_Patient_Sign_Treatment_Consent_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Did Patient Sign Treatment Consent Form?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Randomization_Result__c</fullName>
        <defaultValue>&apos;Not Randomized&apos;</defaultValue>
        <label>Randomization Result</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Randomization Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Randomization Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientsContinueOptedOutDrillDown.cls
Public with sharing class PatientsContinueOptedOutDrillDown{
    public String data{get;set;}
    public PatientsContinueOptedOutDrillDown(){
            data  =   '[\'ARM\',\' Created Date\',\' Subject IDs\'],';
            String drilldownfiled = ApexPages.CurrentPage().getParameters().get('drilldown');
            
            List<Randomization_Form__c> randomizationpatientlist = database.query('SELECT TrialPatient__r.Patient_Id__c,Randomization_Result__c FROM Randomization_Form__c where Randomization_Result__c != \'Not Randomized\' and Status__c = \'Approval Not Required\' and Did_Patient_Sign_Treatment_Consent_Form__c = true and TrialPatient__c not in (SELECT TrialPatient__c FROM Off_Study_Detail__c where  status__c = \'Accepted\') ');
             List<Randomization_Form__c> randomizationpatientlist1 = database.query('SELECT TrialPatient__r.Patient_Id__c,Randomization_Result__c FROM Randomization_Form__c where Randomization_Result__c != \'Not Randomized\' and Status__c = \'Approval Not Required\' and Did_Patient_Sign_Treatment_Consent_Form__c = true and TrialPatient__c in (SELECT TrialPatient__c FROM Off_Study_Detail__c where  status__c = \'Accepted\') ');
            
            List<Id> continueIds = new List<Id>();
            List<Id> optedoutIds= new List<Id>();
            
            for(Randomization_Form__c rr :randomizationpatientlist )
                continueIds.add(rr.TrialPatient__r.Patient_Id__c);
            
            for(Randomization_Form__c rr :randomizationpatientlist1)
                optedoutIds.add(rr.TrialPatient__r.Patient_Id__c);
                
            List<ArmPatient__c > armp = new List<ArmPatient__c >();
            if(drilldownfiled  == 'Opted Out Patient'){
                armp = [select Arm_Id__r.Name,Subject_Id__c,CreatedDate,TrialPatient__r.Patient_Id__r.CreatedDate FROM ArmPatient__c where TrialPatient__r.Patient_Id__r.CreatedDate != null and TrialPatient__r.Patient_Id__c in :optedoutIds Order By Name];
                integer count=1;
                for(ArmPatient__c  c: armp ){
                    if(count == armp.size())
                        data += '[\''+c.Arm_Id__r.Name+'\',\''+c.TrialPatient__r.Patient_Id__r.CreatedDate+'\',\''+c.Subject_Id__c+'\']';
                    else    
                        data += '[\''+c.Arm_Id__r.Name+'\',\''+c.TrialPatient__r.Patient_Id__r.CreatedDate+'\',\''+c.Subject_Id__c+'\'],';   
                    count++;    
                }
            }
            else if(drilldownfiled == 'Continued Patient'){
                armp = [select Arm_Id__r.Name,Subject_Id__c,CreatedDate,TrialPatient__r.Patient_Id__r.CreatedDate FROM ArmPatient__c where TrialPatient__r.Patient_Id__r.CreatedDate != null and  TrialPatient__r.Patient_Id__c in :continueIds Order By Arm_Id__r.Name];
                integer count=1;
                for(ArmPatient__c  c: armp ){
                    if(count == armp.size())
                        data += '[\''+c.Arm_Id__r.Name+'\',\''+c.TrialPatient__r.Patient_Id__r.CreatedDate+'\',\''+c.Subject_Id__c+'\']';
                    else    
                        data += '[\''+c.Arm_Id__r.Name+'\',\''+c.TrialPatient__r.Patient_Id__r.CreatedDate+'\',\''+c.Subject_Id__c+'\'],';   
                    count++;  
                }
            }
            else{
                armp = [select Arm_Id__r.Name,Subject_Id__c,CreatedDate,TrialPatient__r.Patient_Id__r.CreatedDate FROM ArmPatient__c where TrialPatient__r.Patient_Id__r.CreatedDate != null and TrialPatient__r.Patient_Id__c in :optedoutIds Order By Name];
                for(ArmPatient__c  c: armp ){
                    data += '[\''+c.Arm_Id__r.Name+'\',\''+c.TrialPatient__r.Patient_Id__r.CreatedDate+'\',\''+c.Subject_Id__c+'\'],';   
               }
                armp = [select Arm_Id__r.Name,Subject_Id__c,CreatedDate,TrialPatient__r.Patient_Id__r.CreatedDate FROM ArmPatient__c where TrialPatient__r.Patient_Id__r.CreatedDate != null and TrialPatient__r.Patient_Id__c in :continueIds Order By Arm_Id__r.Name];
                for(ArmPatient__c  c: armp ){
                    data += '[\''+c.Arm_Id__r.Name+'\',\''+c.TrialPatient__r.Patient_Id__r.CreatedDate+'\',\''+c.Subject_Id__c+'\'],';   
                }
            
            }
           
   
    }
}