src/objects/ArmPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Id</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>ArmPatients</relationshipLabel>
        <relationshipName>ArmPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ArmPatient</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Arm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ArmPatients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PreEligibility_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PreEligibility Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PreEligibility Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PreEligibility Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Randomization_Form__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Randomization_Result__c</fullName>
        <defaultValue>&apos;Not Randomized&apos;</defaultValue>
        <label>Randomization Result</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Randomization Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Randomization Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScreenedInTreatmentOffStudyController.cls
Public with sharing class ScreenedInTreatmentOffStudyController{
    public String data{get;set;}
    public ScreenedInTreatmentOffStudyController(){
        try{
            data  =   '[\'Name\',\' Number Of Patients\'],';
            List<TrialPatient__c  > screened = new List<TrialPatient__c  >();
            List<TrialPatient__c  >  inTreatment  = new List<TrialPatient__c  >();
            List<TrialPatient__c  >  offstudy = new List<TrialPatient__c  >();
            
            List<patient_Custom__c> screened1 = new  List<patient_Custom__c>() ;
            List<patient_Custom__c>  inTreatment1 = new  List<patient_Custom__c>() ;
            List<patient_Custom__c>  offstudy1 = new  List<patient_Custom__c>() ;
            
            String instituteId = ApexPages.CurrentPage().getParameters().get('institute');
            String siteId = ApexPages.CurrentPage().getParameters().get('site');
            String trialId = ApexPages.CurrentPage().getParameters().get('trial');
            
            List<Randomization_Form__c> randomizeformpatientId = [select CRF__r.patient__c,CRF__c FROM Randomization_Form__c where Randomization_Result__c != 'Not Randomized'  and CRF__c not in (SELECT CRF__c FROM Off_Study_Detail__c where Status__c = 'Accepted')];
            List<Id> patientlist = new List<Id>();
            for(Randomization_Form__c id :randomizeformpatientId ){
                patientlist.add(id.CRF__r.patient__c);
            }
            List<Id> offstudypatientlist = new List<Id>();
            List<Off_Study_Detail__c> offstudypatient = [SELECT CRF__r.Patient__c  FROM Off_Study_Detail__c where Status__c ='Accepted'];
            for(Off_Study_Detail__c id :offstudypatient){
                    offstudypatientlist.add(id.CRF__r.patient__c);
            } 
            
            if((siteId != '' && siteId != null) || (instituteId != '' && instituteId != null) || (trialId != '' && trialId != null)){    
                String condition ='';
               
                if(siteId != '' && siteId != null){
                     condition +='and Site__c IN ('+siteId+')';
                }
                screened= database.query('select Patient_Id__c   from TrialPatient__c  where Patient_Id__c in (select Patient__c from CRF__c where type__c =\'PreEligibility_Checklist__c\') and Patient_Id__c not in (SELECT Patient_Id__c FROM ArmPatient__c) '+condition);
                inTreatment = database.query('select Patient_Id__c   from TrialPatient__c  where Patient_Id__c in :patientlist '+condition);
                offstudy = database.query('select Patient_Id__c   from TrialPatient__c  where Patient_Id__c in :offstudypatientlist '+condition);
            }    
            else{  
                screened1 = [select Id   from patient_Custom__c  where id in (select Patient__c from CRF__c where type__c ='PreEligibility_Checklist__c') and id not in (SELECT Patient_Id__c FROM ArmPatient__c)];
                inTreatment1 = [select Id   from patient_Custom__c  where id in :patientlist];
                offstudy1 = [select Id   from patient_Custom__c  where id in :offstudypatientlist];
            }
            Integer intreatmentvar = 0, screenedvar = 0, offstudyvar = 0;    
            if(inTreatment.size()>0){
                intreatmentvar =  inTreatment.size();
            }
            if(inTreatment1.size()>0 && inTreatment.size() == 0)
                intreatmentvar =  inTreatment1.size();
                
            if(screened.size()>0){
                screenedvar = screened.size();
            }
            if(screened1.size()>0 && screened.size() == 0)
                screenedvar = screened1.size();    
                
            if(offstudy.size()>0){
                offstudyvar  = offstudy.size();
            }
            if(offstudy1.size()>0 && offstudy.size() == 0)
                offstudyvar  = offstudy1.size();
            
            data  += '[\'Screened\','+screenedvar +'],[\'In Treatment\','+intreatmentvar +'],[\'Off Study\','+offstudyvar+']';
               
        }
        catch(exception e){
            System.assert(false,e.getstacktracestring());
        }
            
    }
}