src/objects/BloodSpecimenForm__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>BloodSpecimenForms</relationshipLabel>
        <relationshipName>BloodSpecimenForms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CollectionDate__c</fullName>
        <label>Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <label>CompletedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Consented_to_use_specimen_study__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient consented to use specimen for this study</inlineHelpText>
        <label>Consented to use specimen study</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contented_specimen_outside_study__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient consented to use specimen for research outside of this study</inlineHelpText>
        <label>Contented specimen outside study</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Reason_samples_not_shipped__c</fullName>
        <label>Other (Reason samples not shipped)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_all_samples_not_collected__c</fullName>
        <label>Reason all samples not collected</label>
        <picklist>
            <picklistValues>
                <fullName>Patient refused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Point__c</fullName>
        <label>Time Point</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-regimen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Surgery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>BloodSpecimenForms</relationshipLabel>
        <relationshipName>BloodSpecimenForms</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>BloodSpecimenForm</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BloodSpecimenForms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/BloodSpecimenInfo__c.object
<CustomObject>
    <fields>
        <fullName>BloodSpecimenForm__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BloodSpecimenForm</label>
        <referenceTo>BloodSpecimenForm__c</referenceTo>
        <relationshipLabel>BloodSpecimenInfo</relationshipLabel>
        <relationshipName>BloodSpecimenInfo</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Other_Reason_samples_not_shipped__c</fullName>
        <label>Other (Reason samples not shipped)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_samples_not_shipped__c</fullName>
        <label>Reason samples not shipped</label>
        <picklist>
            <picklistValues>
                <fullName>Spilled on floor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thawed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipped__c</fullName>
        <label>Shipped?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Specimen_ID__c</fullName>
        <label>Specimen ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>BloodSpecimenInfo</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BloodSpecimenInfo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <label>CompletedDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <formula>TRIM(LEFT( First_Name__c , 1) ) &amp; &apos;&apos; &amp;  TRIM( LEFT( Middle_Name__c , 1) ) &amp; &apos;&apos; &amp;  TRIM( LEFT( Last_Name__c , 1) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initials</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institute_Text__c</fullName>
        <label>Institute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TissueSpecimenDetail__c.object
<CustomObject>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_all_samples_not_collected__c</fullName>
        <label>Reason all samples not collected</label>
        <picklist>
            <picklistValues>
                <fullName>Patient Refused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Point__c</fullName>
        <label>Time Point</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Treatment Re-Biopsy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Surgery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Tissue Specimen CRF</relationshipLabel>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tissue Specimen Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tissue Specimen Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BloodSpecimenFormPdf.cls
public class BloodSpecimenFormPdf {
    public BloodSpecimenForm__c bloodSpecimen {get;set;}
    public List<SerumSpecimenWrapper> lstSerumSpecimenWrapper {get;set;}
    public List<PlasmaSpecimenWrapper> lstPlasmaSpecimenWrapper {get;set;}
    public List<BuffySpecimenWrapper> lstBuffySpecimenWrapper {get;set;}
    TissueSpecimenDetail__c tissueSpecimenForm ;
    public TrialPatient__c trialPatientObj {get;set;}
    public Patient_Custom__c Patient {get;set;}
    public boolean isReasonAllDisabled {get;set;}
    public boolean isOtherReasonAllDisabled {get;set;}
       
    
    public BloodSpecimenFormPdf (Apexpages.StandardController std){
        lstBuffySpecimenWrapper = new List<BuffySpecimenWrapper>(); 
        lstSerumSpecimenWrapper = new List<SerumSpecimenWrapper>();
        lstPlasmaSpecimenWrapper = new List<PlasmaSpecimenWrapper>();
        
        string tsSpecimenId = ApexPages.currentPage().getParameters().get('tsSpecimenId');
        tissueSpecimenForm = new TissueSpecimenDetail__c();
        if(tsSpecimenId != null)
            tissueSpecimenForm = [Select TrialPatient__r.Patient_Id__c From TissueSpecimenDetail__c  where id =: tsSpecimenId];    
        
        if(tissueSpecimenForm.TrialPatient__r.Patient_Id__c != null){
            trialPatientObj  = [select Subject_Id__c from TrialPatient__c where id=:tissueSpecimenForm.TrialPatient__c];
            Patient = [select initials__c,Institute_Text__c from Patient_Custom__c where id=:tissueSpecimenForm.TrialPatient__r.Patient_Id__c];
        }
        
        string bloodSpecimenId = Apexpages.currentPage().getParameters().get('bloodSpecimenId'); 
        if(bloodSpecimenId != null && bloodSpecimenId != '')
            bloodSpecimen = [Select b.Effective_Time__c,b.TrialPatient__c, b.TrialPatient__r.Name, b.CRF__c,b.TrialPatient__r.Patient_Id__c, b.Time_Point__c, b.Status__c, b.Reason_all_samples_not_collected__c, b.Phase__c, b.Other_Reason_samples_not_shipped__c, b.Name, b.Id, b.Contented_specimen_outside_study__c, b.Consented_to_use_specimen_study__c, b.CompletedDate__c, b.CollectionDate__c, (Select Name, BloodSpecimenForm__c, Shipped__c, Reason_samples_not_shipped__c, Other_Reason_samples_not_shipped__c, Specimen_ID__c From BloodSpecimenInfo__r) From BloodSpecimenForm__c b where Id = :bloodSpecimenId];
        
        /* 
        for(integer i=1;i<=3;i++) {
            SerumSpecimenWrapper serumSpecimen = new SerumSpecimenWrapper();
            serumSpecimen.bloodSpecimenInfo = new BloodSpecimenInfo__c();
            serumSpecimen.isCollected = false;
            serumSpecimen.SpecimenNumber = 'Serum Specimen #'+i;
            serumSpecimen.isShippedDisabled = true;
            serumSpecimen.isReasonDisabled = true;
            serumSpecimen.isOtherDisabled = true;
            lstSerumSpecimenWrapper.add(serumSpecimen);
        }  
        
         
        for(integer i=1;i<=3;i++) {
            PlasmaSpecimenWrapper plasmaSpecimen = new PlasmaSpecimenWrapper();
            plasmaSpecimen.isCollected = false;
            plasmaSpecimen.bloodSpecimenInfo = new BloodSpecimenInfo__c();
            plasmaSpecimen.SpecimenNumber = 'Plasma Specimen #'+i;
            plasmaSpecimen.isShippedDisabled = true;
            plasmaSpecimen.isReasonDisabled = true;
            plasmaSpecimen.isOtherDisabled = true;
            lstPlasmaSpecimenWrapper.add(plasmaSpecimen);
        }
        
        for(integer i=1;i<=2;i++) {
            BuffySpecimenWrapper buffySpecimen = new BuffySpecimenWrapper();
            buffySpecimen.bloodSpecimenInfo = new BloodSpecimenInfo__c();
            buffySpecimen.isCollected = false;
            buffySpecimen.SpecimenNumber = 'Buffy coat specimen #'+i;
            buffySpecimen.isShippedDisabled = true;
            buffySpecimen.isReasonDisabled = true;
            buffySpecimen.isOtherDisabled = true;
            lstBuffySpecimenWrapper.add(buffySpecimen);
        } */ 
       
    }
    
    public class SerumSpecimenWrapper {
        public String SpecimenNumber {get;set;}
        public boolean isCollected {get;set;}
        public boolean isShippedDisabled {get;set;}
        public boolean isReasonDisabled {get;set;}
        public boolean isOtherDisabled {get;set;}
        public BloodSpecimenInfo__c bloodSpecimenInfo {get;set;}
    }
    
    public class PlasmaSpecimenWrapper { 
        public String SpecimenNumber {get;set;}
        public boolean isCollected {get;set;}
        public boolean isShippedDisabled {get;set;}
        public boolean isReasonDisabled {get;set;}
        public boolean isOtherDisabled {get;set;}
        public BloodSpecimenInfo__c bloodSpecimenInfo {get;set;}
    }
    
    public class BuffySpecimenWrapper {
        public String SpecimenNumber {get;set;}
        public boolean isCollected {get;set;}
        public boolean isShippedDisabled {get;set;}
        public boolean isReasonDisabled {get;set;}
        public boolean isOtherDisabled {get;set;}
        public BloodSpecimenInfo__c bloodSpecimenInfo {get;set;}
    } 
}