src/objects/Chemo_Treatment__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Chemo Treatments</relationshipLabel>
        <relationshipName>Chemo_Treatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Chemo Treatment</label>
    <nameField>
        <label>Chemo Treatment CRF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chemo Treatments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registration</label>
        <referenceTo>Registration__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CRFMaster__c.object
<CustomObject>
    <fields>
        <fullName>CRFType__c</fullName>
        <label>CRFType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRFMaster</label>
    <nameField>
        <label>CRF Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRFMasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Followup_Form__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Followup Forms</relationshipLabel>
        <relationshipName>Followup_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Followup Form</label>
    <nameField>
        <displayFormat>FF-{00000}</displayFormat>
        <label>Followup Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Followup Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase Master</label>
        <referenceTo>Phase_Master__c</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Phase_CRFs__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <label>CRF</label>
        <referenceTo>CRFMaster__c</referenceTo>
        <relationshipLabel>Phases CRFs</relationshipLabel>
        <relationshipName>Phases_CRFs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase_Cycle__c</fullName>
        <label>Phase Cycle</label>
        <referenceTo>Phase_Cycle__c</referenceTo>
        <relationshipLabel>Phases CRFs</relationshipLabel>
        <relationshipName>Phases_CRFs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase CRFs</label>
    <nameField>
        <label>Phase CRF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases CRFs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Phase_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <referenceTo>Phase_Master__c</referenceTo>
        <relationshipLabel>Phase Cycles</relationshipLabel>
        <relationshipName>Phase_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase Cycle</label>
    <nameField>
        <label>Phase Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phase Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Phase_Master__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Phase Master</label>
    <nameField>
        <label>Phase Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Randomization_Form__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Randomization Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Randomization Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase Master</label>
        <referenceTo>Phase_Master__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestCRFsPendingForDCCApproval.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestCRFsPendingForDCCApproval {

    @isTest static void myUnitTest1() {
        
        Account acc = new Account();
        acc.Name = 'testing';
        insert acc;
        
        CRFMaster__c crfMaster = new CRFMaster__c();
        crfMaster.CRFType__c = 'Registration__c';
        crfMaster.Object_Name__c = 'Registration__c';
        insert crfMaster;
        
        Phase_Master__c phMaster = new Phase_Master__c();
        phMaster.Name = 'Screening';
        phMaster.Order__c = 108;  
        insert phMaster;
        
        Phase_Cycle__c phc = new Phase_Cycle__c();
        phc.Phase__c = phMaster.id;
        phc.Order__c = 110;
        insert phc;
        
        Phase_CRFs__c phCrf = new Phase_CRFs__c();
        phCrf.Phase_Cycle__c = phc.id;
        phCrf.CRF__c = crfMaster.Id;
        insert phCrf;
        
        Patient_Custom__c pt = new Patient_Custom__c();
        pt.Name = 'testPatient';
        pt.Institution__c = acc.id;
        pt.Last_Name__c = 'test';
        pt.Birthdate__c = date.newInstance(1970, 04, 05);
        pt.Gender__c = 'Male';
        pt.Race__c = 'White';
        pt.Ethnicity__c = 'Not Hispanic or Latino';
        pt.TestHarnessId__c = 'asc002';
        insert pt;
        
        Trial__c tc = new Trial__c();
        tc.Name = 'testTrial';
        insert tc;
         
        Task tsk = new Task();
        tsk.WhatId = pt.id;
        tsk.Subject = 'Complete Registration CRF';
        tsk.ActivityDate = system.today().addDays(3);
        tsk.Original_Due_Date__c = tsk.ActivityDate;
        tsk.Description = 'Please fill Registration CRF till date.';
        //tsk.OwnerId = Userinfo.getUserId();
        tsk.Type = 'Complete Registration CRF';
        tsk.Object_Label__c = 'Registration';
        tsk.Object_Name__c = 'Registration__c';
        //tsk.Status = 'In Progress';
        tsk.CallType = 'Internal';
        tsk.Trial_Id__c = tc.id;
        tsk.Trial__c = tc.Name;
        insert tsk;
        
        TrialPatient__c tpObj = new TrialPatient__c();
        tpObj.Patient_Id__c = pt.Id;    
        tpObj.Trial_Id__c = tc.Id;
        insert tpObj;
        
        CRFsPendingForDCCApproval crfPendingDcc = new CRFsPendingForDCCApproval();
        Apexpages.currentPage().getParameters().put('CRFName','Registration__c');
        
        crfPendingDcc.CRFPendingListsView();
        crfPendingDcc.selectedCRFViewOption = 'Registration__c';
        crfPendingDcc.createNewCRFsList();
        crfPendingDcc.CRFPendingRandomization();
        
    }
    
    @isTest static void myUnitTest2() {
        Account acc = new Account();
        acc.Name = 'testing';
        insert acc;
        
        CRFMaster__c crfMaster = new CRFMaster__c();
        crfMaster.CRFType__c = 'Chemo_Treatment__c';
        crfMaster.Object_Name__c = 'Chemo_Treatment__c';
        insert crfMaster;
        
        Phase_Master__c phMaster = new Phase_Master__c();
        phMaster.Name = 'Treatment';
        phMaster.Order__c = 109;  
        insert phMaster;
        
        Phase_Cycle__c phc = new Phase_Cycle__c();
        phc.Phase__c = phMaster.id;
        phc.Order__c = 111;
        insert phc;
        
        Phase_CRFs__c phCrf = new Phase_CRFs__c();
        phCrf.Phase_Cycle__c = phc.id;
        phCrf.CRF__c = crfMaster.Id;
        insert phCrf;
        
        Patient_Custom__c pt = new Patient_Custom__c();
        pt.Name = 'testPatient';
        pt.Institution__c = acc.id;
        pt.Last_Name__c = 'test';
        pt.Birthdate__c = date.newInstance(1970, 04, 05);
        pt.Gender__c = 'Male';
        pt.Race__c = 'White';
        pt.Ethnicity__c = 'Not Hispanic or Latino';
        pt.TestHarnessId__c = 'asc002';
        insert pt;
        
        Trial__c tc = new Trial__c();
        tc.Name = 'testTrial';
        insert tc;
        
        Task tsk = new Task();
        tsk.WhatId = pt.id;
        tsk.Subject = 'Complete Registration CRF';
        tsk.ActivityDate = system.today().addDays(3);
        tsk.Original_Due_Date__c = tsk.ActivityDate;
        tsk.Description = 'Please fill Registration CRF till date.';
        //tsk.OwnerId = Userinfo.getUserId();
        tsk.Type = 'Complete Chemo Treatment CRF';
        tsk.Object_Label__c = 'Chemo Treatment';
        tsk.Object_Name__c = 'Chemo_Treatment__c';
        //tsk.Status = 'In Progress';
        tsk.CallType = 'Internal';
        tsk.Trial_Id__c = tc.id;
        tsk.Trial__c = tc.Name;
        insert tsk;
        
        TrialPatient__c tpObj = new TrialPatient__c();
        tpObj.Patient_Id__c = pt.Id;    
        tpObj.Trial_Id__c = tc.Id;
        insert tpObj;
        
        CRFsPendingForDCCApproval crfPendingDcc = new CRFsPendingForDCCApproval();
        Apexpages.currentPage().getParameters().put('CRFName','Chemo_Treatment__c');
        
        crfPendingDcc.CRFPendingListsView();
        crfPendingDcc.selectedCRFViewOption = 'Chemo_Treatment__c';
        crfPendingDcc.createNewCRFsList();
        crfPendingDcc.CRFPendingRandomization();
    }
    
    @isTest static void myUnitTest3() {
        Account acc = new Account();
        acc.Name = 'testing';
        insert acc;
        
        CRFMaster__c crfMaster = new CRFMaster__c();
        crfMaster.CRFType__c = 'Followup_Form__c';
        crfMaster.Object_Name__c = 'Followup_Form__c';
        insert crfMaster;
        
        Phase_Master__c phMaster = new Phase_Master__c();
        phMaster.Name = 'Follow Up';
        phMaster.Order__c = 109;  
        insert phMaster;
        
        Phase_Cycle__c phc = new Phase_Cycle__c();
        phc.Phase__c = phMaster.id;
        phc.Order__c = 111;
        insert phc;
        
        Phase_CRFs__c phCrf = new Phase_CRFs__c();
        phCrf.Phase_Cycle__c = phc.id;
        phCrf.CRF__c = crfMaster.Id;
        insert phCrf;
        
        Patient_Custom__c pt = new Patient_Custom__c();
        pt.Name = 'testPatient';
        pt.Institution__c = acc.id;
        pt.Last_Name__c = 'test';
        pt.Birthdate__c = date.newInstance(1970, 04, 05);
        pt.Gender__c = 'Male';
        pt.Race__c = 'White';
        pt.Ethnicity__c = 'Not Hispanic or Latino';
        pt.TestHarnessId__c = 'asc002';
        insert pt;
        
        Trial__c tc = new Trial__c();
        tc.Name = 'testTrial';
        insert tc;
        
        Task tsk = new Task();
        tsk.WhatId = pt.id;
        tsk.Subject = 'Complete Follow Up CRF';
        tsk.ActivityDate = system.today().addDays(3);
        tsk.Original_Due_Date__c = tsk.ActivityDate;
        tsk.Description = 'Please fill Registration CRF till date.';
        //tsk.OwnerId = Userinfo.getUserId();
        tsk.Type = 'Complete Chemo Treatment CRF';
        tsk.Object_Label__c = 'Follow Up';
        tsk.Object_Name__c = 'Followup_Form__c';
        //tsk.Status = 'In Progress';
        tsk.CallType = 'Internal';
        tsk.Trial_Id__c = tc.id;
        tsk.Trial__c = tc.Name;
        insert tsk;
        
        TrialPatient__c tpObj = new TrialPatient__c();
        tpObj.Patient_Id__c = pt.Id;    
        tpObj.Trial_Id__c = tc.Id;
        insert tpObj;
        
        CRFsPendingForDCCApproval crfPendingDcc = new CRFsPendingForDCCApproval();
        Apexpages.currentPage().getParameters().put('CRFName','Followup_Form__c');
        
        crfPendingDcc.CRFPendingListsView();
        crfPendingDcc.selectedCRFViewOption = 'Followup_Form__c';
        crfPendingDcc.createNewCRFsList();
        crfPendingDcc.CRFPendingRandomization();
        
        crfPendingDcc.selectedCRFViewOption = 'Patients pending Randomization';
        crfPendingDcc.createNewCRFsList();
        
        crfPendingDcc.selectedCRFViewOption = 'pending submission';
        crfPendingDcc.createNewCRFsList();
        
        crfPendingDcc.selectedCRFViewOption = 'pending re-submission';
        crfPendingDcc.createNewCRFsList();
        
        crfPendingDcc.selectedCRFViewOption = 'Patients pending registration';
        crfPendingDcc.createNewCRFsList();
        
        Apexpages.currentPage().getParameters().put('CRFName','Randomization_Form__c');
        crfPendingDcc.CRFPendingListsView();
        
        CRFsPendingForDCCApproval.CRFRandomizationWrapper crfWap = new CRFsPendingForDCCApproval.CRFRandomizationWrapper();
        
    }
}