src/objects/Code_Master__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsReportColumn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsReportColumn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variable_Description__c</fullName>
        <label>Variable Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Code Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LCIS__c.object
<CustomObject>
    <fields>
        <fullName>LCIS__c</fullName>
        <label>LCIS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Study_Pathology_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>On-Study Pathology Form</label>
        <referenceTo>On_Study_Pathology_Form__c</referenceTo>
        <relationshipLabel>LCIS</relationshipLabel>
        <relationshipName>LCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Surgery_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Surgery Summary</label>
        <referenceTo>Post_Surgaory_Summary__c</referenceTo>
        <relationshipLabel>LCIS</relationshipLabel>
        <relationshipName>LCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LCIS</label>
    <nameField>
        <displayFormat>LCIS-{000000}</displayFormat>
        <label>LCIS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCIS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/On_Study_Pathology_Form__c.object
<CustomObject>
    <fields>
        <fullName>Does_the_patient_have_bilateral_breast_c__c</fullName>
        <inlineHelpText>Does the patient have bilateral breast cancer?</inlineHelpText>
        <label>Patient have bilateral breast cancer?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>On-Study Pathology Form</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>On-Study Pathology Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On-Study Pathology Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Post_Surgaory_Summary__c.object
<CustomObject>
    <label>Post Surgery Summary</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Surgery Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Receptors__c.object
<CustomObject>
    <fields>
        <fullName>Estrogen_Intensity_Score__c</fullName>
        <label>Estrogen Intensity Score</label>
        <picklist>
            <picklistValues>
                <fullName>0 (negative)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 (weak)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 (intermediate)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 (strong)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estrogen_Receptor_Proportion_Score__c</fullName>
        <label>Estrogen Receptor  Proportion Score</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 (less than 1%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 (1%-10%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 (10%-33%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 (33%-66%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 (66%-100%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Letarality__c</fullName>
        <label>Letarality</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Study_Pathology_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>On-Study Pathology Form</label>
        <referenceTo>On_Study_Pathology_Form__c</referenceTo>
        <relationshipLabel>Receptors</relationshipLabel>
        <relationshipName>Receptors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Surgery_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Surgery Summary</label>
        <referenceTo>Post_Surgaory_Summary__c</referenceTo>
        <relationshipLabel>Receptors</relationshipLabel>
        <relationshipName>Receptors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Progesterone_Intensity_Score__c</fullName>
        <label>Progesterone Intensity Score</label>
        <picklist>
            <picklistValues>
                <fullName>0 (negative)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 (weak)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 (intermediate)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 (strong)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Progesterone_Receptor_Proportion_Score__c</fullName>
        <label>Progesterone Receptor Proportion Score</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1 (less than 1%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 (1%-10%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 (10%-33%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 (33%-66%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 (66%-100%)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Receptors</label>
    <nameField>
        <displayFormat>REC-{000000}</displayFormat>
        <label>Receptors Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receptors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestReceptors.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestReceptors {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
        /*
        LCIS__c lc = new LCIS__c();
        insert lc;*/
        Code_Master__c snomedObject = new Code_Master__c();
        snomedObject.Variable_Description__c = 'test';
        snomedObject.IsReportColumn__c = true;
        snomedObject.Display_Order__c = 3.0;
        snomedObject.Name = 'ER_TS_OS';
        insert snomedObject;
        
        Code_Master__c snomedObject1 = new Code_Master__c();
        snomedObject1.Variable_Description__c = 'test';
        snomedObject1.IsReportColumn__c = true;
        snomedObject1.Display_Order__c = 3.0;
        snomedObject1.Name = 'PgR_TS_OS';
        insert snomedObject1;
        
        Receptors recp1 = new Receptors(); // else part line 16
        
        On_Study_Pathology_Form__c osp = new On_Study_Pathology_Form__c();
        //osp.LCIS__c = lc.Id;
        //osp.Receptors__c = recObj.Id;
        osp.Does_the_patient_have_bilateral_breast_c__c = 'Yes';
        insert osp;
        
        Post_Surgaory_Summary__c pos = new Post_Surgaory_Summary__c();
        //pos.LCIS__c = lc.Id;
        //pos.Receptors_Left__c = recObj.Id;
        insert pos;
        
        Receptors__c recObj = new Receptors__c();
        recObj.Estrogen_Receptor_Proportion_Score__c = '0';
        recObj.Estrogen_Intensity_Score__c = '0(Negative)';
        recObj.Progesterone_Receptor_Proportion_Score__c = '0';
        recObj.Progesterone_Intensity_Score__c = '0(Negative)';
        recObj.Post_Surgery_Summary__c = pos.Id;
        recObj.On_Study_Pathology_Form__c = osp.Id;
        recObj.Letarality__c = 'Left';
        insert recObj;
        
        ComponentControllerBase ccb = new ComponentControllerBase(); // VIRTUAL CLASS "ComponentControllerBase"
        ccb.key = '1';
        
        PageControllerBase pcb = new PageControllerBase();   // VIRTUAL CLASS "PageControllerBase" BEGINS HERE
        pcb.getComponentControllerMap(); // "get"
        pcb.getReceptorsComponentController(); // "get"
        pcb.getThis();
        
        pcb.setComponentControllerMap('1', ccb);        // "set"
        pcb.setReceptorsComponentController(ccb);           // "set" and VIRTUAL CLASS "PageControllerBase" ENDS HERE
        
        Apexpages.currentPage().getParameters().put('PathologyId',osp.Id);
        //Apexpages.currentPage().getParameters().put('postid',pos.Id);
        Receptors recp = new Receptors(); //class
        
        recp.getKey();
        recp.setPageController(pcb);
        recp.getPageController();
        recp.setKey('1');
        recp.setObjId(osp.Id);
        
        recp.recId = osp.Id;
        recp.recObj = recObj;
        recp.insertRec(osp.Id); // method "insertrec"
        
        recp.recId = pos.Id;
        recp.insertRecPostLeft(pos.Id); // method "left"
        
        recp.recId = pos.Id;
        recp.insertRecPostRight(pos.Id); // method "right"
       
    }
    @isTest static void myUnitTest1() {
        // TO DO: implement unit test
        /*
        LCIS__c lc = new LCIS__c();
        insert lc;
        */
        Code_Master__c snomedObject = new Code_Master__c();
        snomedObject.Variable_Description__c = 'test';
        snomedObject.IsReportColumn__c = true;
        snomedObject.Display_Order__c = 3.0;
        snomedObject.Name = 'ER_TS_OS';
        insert snomedObject;
        
        Code_Master__c snomedObject1 = new Code_Master__c();
        snomedObject1.Variable_Description__c = 'test';
        snomedObject1.IsReportColumn__c = true;
        snomedObject1.Display_Order__c = 3.0;
        snomedObject1.Name = 'PgR_TS_OS';
        insert snomedObject1;
        
        Receptors recp1 = new Receptors(); // else part line 16
        
        On_Study_Pathology_Form__c osp = new On_Study_Pathology_Form__c();
        //osp.LCIS__c = lc.Id;
        //osp.Receptors__c = recObj.Id;
        osp.Does_the_patient_have_bilateral_breast_c__c = 'Yes';
        insert osp;
        
        Post_Surgaory_Summary__c pos = new Post_Surgaory_Summary__c();
        //pos.LCIS__c = lc.Id;
        //pos.Receptors_Right__c = recObj.Id;
        insert pos;
        
        Receptors__c recObj = new Receptors__c();
        recObj.Estrogen_Receptor_Proportion_Score__c = '0';
        recObj.Estrogen_Intensity_Score__c = '0(Negative)';
        recObj.Progesterone_Receptor_Proportion_Score__c = '0';
        recObj.Progesterone_Intensity_Score__c = '0(Negative)';
        recObj.Post_Surgery_Summary__c = pos.Id;
        recObj.On_Study_Pathology_Form__c = osp.Id;
        recObj.Letarality__c = 'Left';
        insert recObj;
        
        Receptors__c recObj1 = new Receptors__c();
        recObj1.Estrogen_Receptor_Proportion_Score__c = '0';
        recObj1.Estrogen_Intensity_Score__c = '0(Negative)';
        recObj1.Progesterone_Receptor_Proportion_Score__c = '0';
        recObj1.Progesterone_Intensity_Score__c = '0(Negative)';
        recObj1.Post_Surgery_Summary__c = pos.Id;
        recObj1.On_Study_Pathology_Form__c = osp.Id;
        recObj1.Letarality__c = 'Right';
        insert recObj1;
        
        Apexpages.currentPage().getParameters().put('postid',pos.Id);
        Receptors recp = new Receptors(); //class
        
        recp.setObjId(pos.Id);
        recp.recId = osp.Id;
        recp.recObj = recObj;
        recp.insertRec(osp.Id); // method "insertrec"
        
        recp.recId = pos.Id;
        recp.insertRecPostLeft(pos.Id); // method "left"
        
        recp.recId = pos.Id;
        recp.insertRecPostRight(pos.Id); // method "right"
       
    }
    @isTest static void myUnitTest2() {
        // TO DO: implement unit test
        /*
        LCIS__c lc = new LCIS__c();
        insert lc;
        */
        Code_Master__c snomedObject = new Code_Master__c();
        snomedObject.Variable_Description__c = 'test';
        snomedObject.IsReportColumn__c = true;
        snomedObject.Display_Order__c = 3.0;
        snomedObject.Name = 'ER_TS_OS';
        insert snomedObject;
        
        Code_Master__c snomedObject1 = new Code_Master__c();
        snomedObject1.Variable_Description__c = 'test';
        snomedObject1.IsReportColumn__c = true;
        snomedObject1.Display_Order__c = 3.0;
        snomedObject1.Name = 'PgR_TS_OS';
        insert snomedObject1;
        
        Receptors recp1 = new Receptors(); // else part line 16
        
        On_Study_Pathology_Form__c osp = new On_Study_Pathology_Form__c();
        //osp.LCIS__c = lc.Id;
        //osp.Receptors__c = recObj.Id;
        osp.Does_the_patient_have_bilateral_breast_c__c = 'Yes';
        insert osp;
        
        Post_Surgaory_Summary__c pos = new Post_Surgaory_Summary__c();
        //pos.LCIS__c = lc.Id;
        //pos.Receptors_Left__c = recObj.Id;
        insert pos;
        
        Receptors__c recObj = new Receptors__c();
        recObj.Estrogen_Receptor_Proportion_Score__c = '0';
        recObj.Estrogen_Intensity_Score__c = '0(Negative)';
        recObj.Progesterone_Receptor_Proportion_Score__c = '0';
        recObj.Progesterone_Intensity_Score__c = '0(Negative)';
        recObj.Post_Surgery_Summary__c = pos.Id;
        recObj.On_Study_Pathology_Form__c = osp.Id;
        insert recObj;
        
        Apexpages.currentPage().getParameters().put('PathologyId',osp.Id);
        Receptors recp = new Receptors(); //class
        
        recp.recId = osp.Id;
        recp.recObj = recObj;
        recp.insertRec(osp.Id); // method "insertrec"
        
    }
}