src/objects/Code_Master__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsReportColumn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsReportColumn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Snomed_Code__c</fullName>
        <label>Snomed Code</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Variable_Description__c</fullName>
        <label>Variable Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Code Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DCIS__c.object
<CustomObject>
    <fields>
        <fullName>DCIS__c</fullName>
        <label>DCIS %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>On_Study_Pathology_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>On-Study Pathology Form</label>
        <referenceTo>On_Study_Pathology_Form__c</referenceTo>
        <relationshipLabel>DCIS</relationshipLabel>
        <relationshipName>DCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Surgery_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Surgery Summary</label>
        <referenceTo>Post_Surgaory_Summary__c</referenceTo>
        <relationshipLabel>DCIS</relationshipLabel>
        <relationshipName>DCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Punctate_necrosis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Punctate necrosis</label>
        <type>Checkbox</type>
    </fields>
    <label>DCIS</label>
    <nameField>
        <displayFormat>DCIS-{000000}</displayFormat>
        <label>DCIS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DCIS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LCIS__c.object
<CustomObject>
    <fields>
        <fullName>LCIS__c</fullName>
        <label>LCIS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Study_Pathology_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>On-Study Pathology Form</label>
        <referenceTo>On_Study_Pathology_Form__c</referenceTo>
        <relationshipLabel>LCIS</relationshipLabel>
        <relationshipName>LCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Surgery_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Surgery Summary</label>
        <referenceTo>Post_Surgaory_Summary__c</referenceTo>
        <relationshipLabel>LCIS</relationshipLabel>
        <relationshipName>LCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LCIS</label>
    <nameField>
        <displayFormat>LCIS-{000000}</displayFormat>
        <label>LCIS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCIS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/On_Study_Pathology_Form__c.object
<CustomObject>
    <fields>
        <fullName>Tumor_laterality__c</fullName>
        <inlineHelpText>Tumor laterality (or side with most advanced disease)</inlineHelpText>
        <label>Tumor laterality</label>
        <picklist>
            <picklistValues>
                <fullName>Left</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>On-Study Pathology Form</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>On-Study Pathology Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On-Study Pathology Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Post_Surgaory_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Type_Of_Tumor__c</fullName>
        <label>Type Of Tumor</label>
        <picklist>
            <picklistValues>
                <fullName>None Present</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single Discrete Mass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifocal Discrete Masses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gross Stromal Alterations/Fibrosis</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Post Surgery Summary</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Surgery Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Snomed_Code__c.object
<CustomObject>
    <fields>
        <fullName>Code_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Code Master</label>
        <referenceTo>Code_Master__c</referenceTo>
        <relationshipLabel>Snomed Codes</relationshipLabel>
        <relationshipName>Snomed_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>snomed_Code_Name__c</fullName>
        <description>This is custom field for storing snomed code name. Earlier we were storing code name in standard &quot;Name&quot; field but that only contains 80 characters. Thats why we created this field.</description>
        <label>snomed Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Snomed Code</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Snomed Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Snomed Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestLCISBeforeInsertUpdate.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestLCISBeforeInsertUpdate {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
        
        Code_Master__c snomedObject = new Code_Master__c();
        snomedObject.Variable_Description__c = 'test';
        snomedObject.IsReportColumn__c = true;
        snomedObject.Display_Order__c = 3.0;
        snomedObject.Name = 'LCISHistology_PS';
        insert snomedObject;
        
        Snomed_Code__c snomed = new Snomed_Code__c();
        snomed.Code_Master__c = snomedObject.Id;
        insert snomed;
        
        Post_Surgaory_Summary__c postObject = new Post_Surgaory_Summary__c();
        postObject.Type_Of_Tumor__c = 'Single Discrete Mass';
        insert postObject;
        
        On_Study_Pathology_Form__c studyObject = new On_Study_Pathology_Form__c();
        studyObject.Tumor_laterality__c = 'Left';
        insert studyObject;
        
        DCIS__c dcisObject = new DCIS__c();
        dcisObject.Post_Surgery_Summary__c = postObject.Id;
        dcisObject.Punctate_necrosis__c = true;
        insert dcisObject;
        
        LCIS__c lcisObject = new LCIS__c();
        lcisObject.Post_Surgery_Summary__c = postObject.Id;
        lcisObject.On_Study_Pathology_Form__c = studyObject.Id;
        insert lcisObject;
        update lcisObject;
        
        Code_Master__c snomedObject1 = new Code_Master__c();
        snomedObject1.Variable_Description__c = 'test';
        snomedObject1.IsReportColumn__c = true;
        snomedObject1.Display_Order__c = 3.0;
        snomedObject1.Name = 'InSitu_PS';
        insert snomedObject1;
        
        Snomed_Code__c snomed1 = new Snomed_Code__c();
        snomed1.Code_Master__c = snomedObject1.Id;
        snomed1.snomed_Code_Name__c = 'IHTSDO_4567';
        insert snomed1;
        
        LCIS__c lcisObject1 = new LCIS__c();
        lcisObject1.Post_Surgery_Summary__c = postObject.Id;
        lcisObject1.On_Study_Pathology_Form__c = studyObject.Id;
        insert lcisObject1;
        update lcisObject1;
        
    }
}