src/objects/Code_Master__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsReportColumn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsReportColumn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Variable_Description__c</fullName>
        <label>Variable Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Code Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Code Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Died__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Died</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_completed_study_per_protocol__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient completed study per protocol</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_not_have_surgery__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not have surgery.</description>
        <inlineHelpText>Patient did not have surgery.</inlineHelpText>
        <label>Patient did not have surgery</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_not_want_to_complete_MRI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not want to complete study MRI scans.</description>
        <inlineHelpText>Patient did not want to complete study MRI scans.</inlineHelpText>
        <label>Patient did not want to complete MRI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_nt_continue_on_treatment_arm__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not continue on treatment arm.</description>
        <inlineHelpText>Patient did not continue on treatment arm.</inlineHelpText>
        <label>Patient did&apos;nt continue on treatment arm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_nt_want_to_complete_core_bio__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not want to complete study core biopsy.</description>
        <inlineHelpText>Patient did not want to complete study core biopsy.</inlineHelpText>
        <label>Patient did&apos;nt want to complete core bio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Why_patient_didnt_continue_treatment_arm__c</fullName>
        <description>Why Patient did not continue treatment arm.</description>
        <inlineHelpText>Why Patient did not continue treatment arm.</inlineHelpText>
        <label>Why patient didnt continue treatment arm</label>
        <picklist>
            <picklistValues>
                <fullName>Due to (S)AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecurityCode__c</fullName>
        <label>SecurityCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestOffStudyController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestOffStudyController {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
            List<User> lstSiteUser = [Select u.IsActive, u.Id, SecurityCode__c From User u where IsActive = true and Profile.Name = 'Site User'];     
            System.runAs ( lstSiteUser[0] ) { 
            
            Account acc = new Account();
            
            List<Account> lstAccount = [Select a.Id From Account a limit 1];
            
            if(!lstAccount.isEmpty()){
                
            acc = lstAccount[0];
            
            Patient_Custom__c p = new Patient_Custom__c();
            p.Birthdate__c = date.newInstance(1980, 08, 05);
            p.Institution__c = acc.Id;
            p.Last_Name__c = 'test'; // patient
            p.Gender__c = 'Male';
            p.Race__c = 'White';
            p.Ethnicity__c = 'Not Hispanic or Latino';
            insert p;
            
            Code_Master__c snomedObject = new Code_Master__c();
            snomedObject.Variable_Description__c = 'test';
            snomedObject.IsReportColumn__c = true;
            snomedObject.Display_Order__c = 3.0;
            snomedObject.Name = 'OffStudy';
            insert snomedObject;
            
            TrialPatient__c tp = new TrialPatient__c();
            tp.Patient_Id__c = p.Id;
            insert tp;
            
            Off_Study_Detail__c offStudy1 = new Off_Study_Detail__c(); // if condition line 43
            offStudy1.TrialPatient__c = tp.Id;
            insert offStudy1;
            
            Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
            ApexPages.StandardController controller1 = new ApexPages.StandardController(offStudy1);
            OffStudyController osc1 = new OffStudyController(controller1);  // if condition line 43
            osc1.saveCrf(); // else line 50
            Apexpages.currentPage().getParameters().put('id',offStudy1.Id); // if line 45
            osc1.saveCrf();
            
            Off_Study_Detail__c offStudy = new Off_Study_Detail__c();
            offStudy.TrialPatient__c = tp.Id;
            insert offStudy;
            
            Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
            Apexpages.currentPage().getParameters().put('offStudyId',offStudy.Id);
            ApexPages.StandardController controller = new ApexPages.StandardController(offStudy);
            OffStudyController osc = new OffStudyController(controller);
            
            Apexpages.currentPage().getParameters().put('nextTab','attachmentTab');
            osc.next();
            
            Apexpages.currentPage().getParameters().put('nextTab','saveAndClose');
            osc.next();
            
            Apexpages.currentPage().getParameters().put('prevTab','attachmentTab');
            osc.previous();
            
            osc.saveCrf();
            osc.password = '3c47d9ff';
            osc.signAndSubmit();
            osc.resendCode();
            osc.cloneCRF();
            osc.editCRF();
            
            Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
            osc.customCancel();
            }
        }
    }
    
    @isTest static void myUnitTest1() {
        List<User> lstSiteUser = [Select u.IsActive, u.Id, SecurityCode__c From User u where IsActive = true and Profile.Name = 'Site User'];     
            System.runAs ( lstSiteUser[0] ) { 
            
            Account acc = new Account();
            
            List<Account> lstAccount = [Select a.Id From Account a limit 1];
            
            if(!lstAccount.isEmpty()){
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; // patient
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                Code_Master__c snomedObject = new Code_Master__c();
                snomedObject.Variable_Description__c = 'test';
                snomedObject.IsReportColumn__c = true;
                snomedObject.Display_Order__c = 3.0;
                snomedObject.Name = 'OffStudy';
                insert snomedObject;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                Off_Study_Detail__c offStudy2 = new Off_Study_Detail__c();
                offStudy2.TrialPatient__c = tp.Id;
                offStudy2.Patient_completed_study_per_protocol__c = true;
                insert offStudy2;
                
                offStudy2.Status__c = 'Accepted';
                update offStudy2;
                
                Off_Study_Detail__c offStudy3 = new Off_Study_Detail__c();
                offStudy3.TrialPatient__c = tp.Id;
                //Patient_Died__c, Patient_did_not_have_surgery__c, Why_patient_didnt_continue_treatment_arm__c, Patient_did_nt_continue_on_treatment_arm__c, 
                //Patient_did_nt_want_to_complete_core_bio__c, Patient_did_not_want_to_complete_MRI__c
                offStudy3.Patient_Died__c = true;
                offStudy3.Patient_did_not_have_surgery__c = true;
                offStudy3.Patient_did_nt_continue_on_treatment_arm__c = true;
                offStudy3.Why_patient_didnt_continue_treatment_arm__c = 'Due to (S)AE';
                offStudy3.Patient_did_nt_want_to_complete_core_bio__c = true;
                offStudy3.Patient_did_not_want_to_complete_MRI__c = true;
                insert offStudy3;
                
                offStudy3.Status__c = 'Accepted';
                update offStudy3;
            }
        }
    }
    
    @isTest static void myUnitTest2() {
        List<User> lstSiteUser = [Select u.IsActive, u.Id, SecurityCode__c From User u where IsActive = true and Profile.Name = 'Site User'];     
            System.runAs ( lstSiteUser[0] ) { 
            
            Account acc = new Account();
            
            List<Account> lstAccount = [Select a.Id From Account a limit 1];
            
            if(!lstAccount.isEmpty()){
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; // patient
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                Code_Master__c snomedObject = new Code_Master__c();
                snomedObject.Variable_Description__c = 'test';
                snomedObject.IsReportColumn__c = true;
                snomedObject.Display_Order__c = 3.0;
                snomedObject.Name = 'OffStudy';
                insert snomedObject;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                Off_Study_Detail__c offStudy3 = new Off_Study_Detail__c();
                offStudy3.TrialPatient__c = tp.Id;
                //Patient_Died__c, Patient_did_not_have_surgery__c, Why_patient_didnt_continue_treatment_arm__c, Patient_did_nt_continue_on_treatment_arm__c, 
                //Patient_did_nt_want_to_complete_core_bio__c, Patient_did_not_want_to_complete_MRI__c
                offStudy3.Patient_Died__c = true;
                offStudy3.Patient_did_not_have_surgery__c = true;
                offStudy3.Patient_did_nt_continue_on_treatment_arm__c = true;
                offStudy3.Why_patient_didnt_continue_treatment_arm__c = 'Personal Preference';
                offStudy3.Patient_did_nt_want_to_complete_core_bio__c = true;
                offStudy3.Patient_did_not_want_to_complete_MRI__c = true;
                insert offStudy3;
                
                offStudy3.Status__c = 'Accepted';
                update offStudy3;
                
                Off_Study_Detail__c offStudy2 = new Off_Study_Detail__c();
                offStudy2.TrialPatient__c = tp.Id;
                //Patient_Died__c, Patient_did_not_have_surgery__c, Why_patient_didnt_continue_treatment_arm__c, Patient_did_nt_continue_on_treatment_arm__c, 
                //Patient_did_nt_want_to_complete_core_bio__c, Patient_did_not_want_to_complete_MRI__c
                offStudy2.Patient_Died__c = true;
                offStudy2.Patient_did_not_have_surgery__c = true;
                offStudy2.Patient_did_nt_continue_on_treatment_arm__c = true;
                offStudy2.Why_patient_didnt_continue_treatment_arm__c = 'Other';
                offStudy2.Patient_did_nt_want_to_complete_core_bio__c = true;
                offStudy2.Patient_did_not_want_to_complete_MRI__c = true;
                insert offStudy2;
                
                offStudy2.Status__c = 'Accepted';
                update offStudy2;
            }
        }
    }
}