src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Surgeon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncologist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radiology Coordinator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Widget__c.object
<CustomObject>
    <fields>
        <fullName>Chart_Fields__c</fullName>
        <label>Chart Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data_Limit__c</fullName>
        <label>Data Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query_Type__c</fullName>
        <label>Query Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aggregate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <picklist>
            <picklistValues>
                <fullName>A Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Half</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Three Quarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Column</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestColumnChart.cls
@isTest
public class TestColumnChart{
  public static testMethod void TestColumnChart(){
     
       List<Account> ac = new List<Account>();
      
      for (integer i = 1 ; i < 5 ; i ++ ) {
          ac.add(new Account(name = 'test'+i ,NumberOfEmployees = 10*i,AnnualRevenue = 200 * i));
      }
      
      insert ac;
      Site__c st = new Site__c();
      st.Institute__c = ac[0].Id;
      st.Name = 'Test';
      insert st;
      
      List<Contact> contacts = new List<Contact>();
      
      for (integer i = 1 ; i < ac.size() ; i ++ ) {
          contacts.add(new Contact(lastname = 'test'+i , AccountId= ac[i-1].id, site__c=st.id));
      }
      insert contacts;
      
     Widget__c widget4=new  Widget__c();
     widget4.query__c = 'select name , NumberOfEmployees from account where  NumberOfEmployees != null ';
     widget4.query_type__c ='Normal';
     widget4.Type__c='Column';
     widget4.Size__c='Small';
     widget4.Data_Limit__c = 5;
     widget4.Chart_Fields__c='name,NumberOfEmployees';
     insert widget4;
     
     Widget__c widget1=new  Widget__c();
     widget1.query__c = 'select name ,Count(AccountId) countaac from contact group by name';
     widget1.query_type__c ='Aggregate';
     widget1.Chart_Fields__c='name, countaac';
     widget1.Type__c='Column';
     widget1.Size__c='Small';
     widget1.Data_Limit__c = 5;
     widget1.Chart_Fields__c='name,countaac';
     insert widget1;
     
     Widget__c widget2=new  Widget__c();
     widget2.query__c = 'select Account.name ,Account.NumberOfEmployees from contact';
     widget2.query_type__c ='Normal';
     widget2.Data_Limit__c = 5;
     widget2.Chart_Fields__c='Account.name,Account.NumberOfEmployees';
    
     insert widget2;
     
     ColumnChart cc=new ColumnChart();
     
     cc.getData(widget4);
     
     cc = new ColumnChart();
     cc.getData(widget1);
    
     cc.getData(widget2);
  }
}