src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/InstitutionUser__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Institution Users</relationshipLabel>
        <relationshipName>InstitutionUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>InstitutionUsers</relationshipLabel>
        <relationshipName>InstitutionUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>InstitutionUsers</relationshipLabel>
        <relationshipName>InstitutionUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>InstitutionUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InstitutionUser</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InstitutionUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Randomization_Form__c.object
<CustomObject>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Randomization Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Randomization Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Oncologist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If you doesn&apos;t found oncologist in lookup list then click on &quot;New&quot; button in lookup.</inlineHelpText>
        <label>Oncologist</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OriginalCRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriginalCRF</label>
        <referenceTo>Registration__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Date__c</fullName>
        <label>Registration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Screening_Informed_Consent_Date__c</fullName>
        <label>Screening Informed Consent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is need for SignAndSubmit button which is using this id for approval.</description>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>IsTestSite__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is for test site only.</description>
        <label>IsTestSite</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Name__c</fullName>
        <label>Short Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Lab</fullName>
        <active>true</active>
        <label>Lab</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site_Trial__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Site Trials</relationshipLabel>
        <relationshipName>Site_Trials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Site Trials</relationshipLabel>
        <relationshipName>Site_Trials</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <picklist>
            <picklistValues>
                <fullName>Site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Site Trial</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Trials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/AllPatientSummaryReport.cls
public without sharing class AllPatientSummaryReport {
	
	private List<Selectoption> trials;
	private List<Selectoption> sites;
	public List<Selectoption> selectedSiteOptions {get;set;}
	public List<Selectoption> selectedTrialOptions {get;set;}
	public List<String> selectedTrials {get;set;}
	public String trialName {get;set;}
	public List<String> selectedSites {get;set;}
	public String siteName {get;set;}
	public List<ReportWrapper> lstReportWrapper {get;set;}
	public String trialLabel {get;set;}
	public Date asOfDate {get;set;}
	public Contact contact {get;set;}
	public String currentUser {get;set;}
	public boolean isErrorMsg {get;set;}
	
	public AllPatientSummaryReport() {
		selectedSiteOptions = new List<Selectoption>();
		selectedTrialOptions = new List<Selectoption>();
		selectedSites = new List<String>();
		lstReportWrapper = new List<ReportWrapper>();
		isErrorMsg = false;
		contact = new Contact();
		if(!Test.isRunningTest()) {
			contact.Birthdate = system.today();
		}
		List<Profile> lstProfile = [select Id, Name from Profile where Id = :Userinfo.getProfileId()];
		if(!lstProfile.isEmpty()) {
			currentUser = lstProfile[0].Name;
		}
	}
	
	public List<Selectoption> getSites() {
		//siteId = '';
		List<Site__c> lstSite = [select id, Name from Site__c where RecordType.Name != 'Lab' and IsTestSite__c = false order by Name asc];
		
		Set<Id> siteIds = new Set<Id>();
		if(currentUser == 'Site User') {
			List<InstitutionUser__c> lstInstUser = [Select i.User__c, i.Site__c From InstitutionUser__c i where User__c = :Userinfo.getUserId()];
			for(InstitutionUser__c instUser : lstInstUser) {
				siteIds.add(instUser.Site__c);
			}
			lstSite = [select id, Name from Site__c where Id IN :siteIds and RecordType.Name != 'Lab' and IsTestSite__c = false order by Name asc];
			if(lstSite.size() == 1) {
				selectedSites.add(lstSite[0].Id);
				siteName = lstSite[0].Name;
			}
		}
		
		List<Selectoption> sitePickList = new List<Selectoption>();
		//sitePickList.add(new Selectoption('', '----None----'));
		for(Site__c site : lstSite) {
			sitePickList.add(new Selectoption(site.Id, site.Name));
		}
		return sitePickList;
	}
	
	public void setSites(List<Selectoption> sites) {
		this.sites = sites;		
	}
	
	public List<Selectoption> getTrials() {
		
		trials = new List<Selectoption>();
		selectedTrials = new List<String>();
		selectedSites = new List<String>();
		if(selectedSiteOptions.isEmpty()) {
			selectedTrialOptions.clear();
		} else {
			for(Selectoption so : selectedSiteOptions) {
				selectedSites.add(so.getValue());	
			}
			for(Selectoption so : selectedTrialOptions) {
				selectedTrials.add(so.getValue());	
			}
		}
		
		Set<String> selectedTrialSet = new Set<String>();
		selectedTrialSet.addAll(selectedTrials);
		
		system.debug('selectedSites : '+selectedSites);
		List<Site_Trial__c> lstSiteTrails = [Select s.Trial__c, s.Trial__r.Name, s.Site__c From Site_Trial__c s where Site__c IN :selectedSites and Site__r.IsTestSite__c = false];
		selectedTrials.clear();
		//List<Site_Trial__c> lstSiteTrails = [Select s.Trial__c, s.Trial__r.Name, s.Site__c From Site_Trial__c s];
		Set<Id> trialIds = new Set<Id>();
		if(currentUser == 'Institute Level Admin') {
			List<InstitutionUser__c> lstInstUser = [Select i.User__c, i.Site__c, i.Institution__c, i.Trial__c From InstitutionUser__c i where User__c = :Userinfo.getUserId()];
			for(InstitutionUser__c instUser : lstInstUser) {
				trialIds.add(instUser.Trial__c);
			}
			lstSiteTrails = [Select s.Trial__c, s.Trial__r.Name, s.Site__c From Site_Trial__c s where Trial__c IN :trialIds];
		}
		
		List<Selectoption> trialPickList = new List<Selectoption>();
		//trialPickList.add(new Selectoption('', '----None----'));
		Set<Id> duplicateTrials = new Set<Id>();
		Set<Id> allTrials = new Set<Id>();
		for(Site_Trial__c st : lstSiteTrails) {
			allTrials.add(st.Trial__c);
			if(selectedTrialSet.contains(st.Trial__c)) continue;
			if(!duplicateTrials.contains(st.Trial__c)) {
				trialPickList.add(new Selectoption(st.Trial__c, st.Trial__r.Name));
				duplicateTrials.add(st.Trial__c);
			}
		}
		
		if(duplicateTrials.size() == 1) {
			trialLabel = lstSiteTrails[0].Trial__r.Name;
			selectedTrials.add(lstSiteTrails[0].Trial__c);
		}
		List<Selectoption> lstSOP = new List<Selectoption>();
		for(Selectoption so : selectedTrialOptions) {
			if(allTrials.contains(so.getValue())) {
				lstSOP.add(so);
			}
		}
		selectedTrialOptions.clear();
		selectedTrialOptions.addAll(lstSOP);
		return trialPickList;
	}
	
	public void setTrials(List<Selectoption> trials) {
		this.trials = trials;		
	}
	
	public Pagereference generateReport() {
		
		//selectedSiteOptions
		//selectedTrialOptions
		if(selectedTrialOptions.isEmpty()) {
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: Please select Trials.');
            ApexPages.addMessage(myMsg);
			return null;
		}
		selectedSites = new List<String>();
		selectedTrials = new List<String>();
		
		for(Selectoption so : selectedSiteOptions) {
			selectedSites.add(so.getValue());	
		}
		
		for(Selectoption so : selectedTrialOptions) {
			selectedTrials.add(so.getValue());	
		}
		
		System.debug('contact.Birthdate : '+contact.Birthdate);
		List<Trial__c> lstTrial = [select id, Name from Trial__c where id IN :selectedTrials];
		if(lstTrial.isEmpty()) return null;
		trialName = '';
		for(Trial__c t : lstTrial) {
			trialName += t.Name+', ';
		}
		if(trialName != null) {
			trialName = trialName.substring(0,trialName.length()-2);
		}
		if(contact.Birthdate == null) contact.Birthdate = System.today();
		asOfDate = contact.Birthdate;
		lstReportWrapper = new List<ReportWrapper>();
		System.debug('selectedTrials : '+selectedTrials);
		System.debug('selectedSites : '+selectedSites);
		System.debug('asOfDate : '+asOfDate.addDays(2));
		List<TrialPatient__c> lstTrialPatient = [Select t.Trial_Id__r.Name, t.Subject_Id__c, t.Site__r.Short_Name__c, t.Patient_Id__r.Zip__c, t.Patient_Id__r.Race__c, 
												t.Patient_Id__r.Gender__c, t.Patient_Id__r.Ethnicity__c, t.Patient_Id__r.Birthdate__c, t.Patient_Id__c, 
												(Select Registration_Date__c, Screening_Informed_Consent_Date__c From Registrations__r where Status__c = 'Approval Not Required' order by LastModifiedDate desc limit 1), 
												(Select Consent_Signed_Date__c, Other_Reason_Did_Not_Sign_Consent_Form__c, Did_Patient_Sign_Treatment_Consent_Form__c, 
												Why_Patient_Not_Signed_Consent_Form__c From Randomization_Forms__r where Status__c = 'Approval Not Required') From TrialPatient__c t 
												where Site__r.IsTestSite__c = false and Trial_Id__c IN :selectedTrials and Site__c IN :selectedSites and CreatedDate <= :asOfDate.addDays(2) and Subject_Id__c != null
												order by Trial_Id__r.Name asc, Subject_Id__c asc];
		
		if(currentUser == 'Institute Level Admin') {
			lstTrialPatient = [Select t.Trial_Id__r.Name, t.Subject_Id__c, t.Site__r.Short_Name__c, t.Patient_Id__r.Zip__c, t.Patient_Id__r.Race__c, 
							t.Patient_Id__r.Gender__c, t.Patient_Id__r.Ethnicity__c, t.Patient_Id__r.Birthdate__c, t.Patient_Id__c, 
							(Select Registration_Date__c, Screening_Informed_Consent_Date__c From Registrations__r where Status__c = 'Approval Not Required' order by LastModifiedDate desc limit 1), 
							(Select Consent_Signed_Date__c, Other_Reason_Did_Not_Sign_Consent_Form__c, Did_Patient_Sign_Treatment_Consent_Form__c, 
							Why_Patient_Not_Signed_Consent_Form__c From Randomization_Forms__r where Status__c = 'Approval Not Required') From TrialPatient__c t 
							where Site__r.IsTestSite__c = false and Trial_Id__c IN :selectedTrials and CreatedDate <= :asOfDate.addDays(2) and Subject_Id__c != null
							order by Trial_Id__r.Name asc, Subject_Id__c asc];
		}
		
		for(TrialPatient__c tp : lstTrialPatient) {
			
			if(tp.Registrations__r.isEmpty()) continue;			
			ReportWrapper rw = new ReportWrapper();
			rw.trial = tp.Trial_Id__r.Name; 
			rw.ispy2_id = tp.Subject_Id__c;
			rw.trial_site = tp.Site__r.Short_Name__c; 
			rw.screening_consent_date = tp.Registrations__r[0].Screening_Informed_Consent_Date__c;
			rw.reg_date = tp.Registrations__r[0].Registration_Date__c;
			if(!tp.Randomization_Forms__r.isEmpty()) {
				if(tp.Randomization_Forms__r[0].Did_Patient_Sign_Treatment_Consent_Form__c) {
					if(tp.Randomization_Forms__r[0].Consent_Signed_Date__c != null) {
						Date csd = tp.Randomization_Forms__r[0].Consent_Signed_Date__c;
						rw.treatment_consent_date = String.valueOf(csd.month())+'/'+String.valueOf(csd.day())+'/'+String.valueOf(csd.year());
					} else {
						rw.treatment_consent_date = '';
					}
					//rw.treatment_consent_date = tp.Randomization_Forms__r[0].Consent_Signed_Date__c!=null?String.valueOf(tp.Randomization_Forms__r[0].Consent_Signed_Date__c):'';
					rw.reason_not_signed_consent = 'NA';		
				} else {
					rw.treatment_consent_date = 'No';
					rw.reason_not_signed_consent = tp.Randomization_Forms__r[0].Why_Patient_Not_Signed_Consent_Form__c=='Other'?'Other Reason - '+tp.Randomization_Forms__r[0].Other_Reason_Did_Not_Sign_Consent_Form__c:tp.Randomization_Forms__r[0].Why_Patient_Not_Signed_Consent_Form__c;
				}
			} else {
				rw.treatment_consent_date = 'Screening';
				rw.reason_not_signed_consent = 'NA';
			}
			rw.gender = tp.Patient_Id__r.Gender__c;
			rw.race = tp.Patient_Id__r.Race__c;
			rw.ethnicity = tp.Patient_Id__r.Ethnicity__c; 
			rw.zip = tp.Patient_Id__r.Zip__c;
			rw.dob = tp.Patient_Id__r.Birthdate__c;
			lstReportWrapper.add(rw);
		}
		if(lstReportWrapper.isEmpty()) {
			isErrorMsg = true;
		} else {
			isErrorMsg = false;
		}
		return null;	
	}
	
	public Pagereference redirectNewPage() {
		String format = Apexpages.currentPage().getParameters().get('format');
		Pagereference ref = null;
		if(format == 'HTML') {
			ref = new Pagereference('/apex/AllPatientSummaryReportHTML');
		} else if(format == 'PDF') {
			ref = new Pagereference('/apex/AllPatientSummaryReportPDF');
		} else if(format == 'CSV') {
			ref = new Pagereference('/apex/AllPatientSummaryReportCSV');
		}
		ref.setRedirect(false);
		return ref;	
	}
	
	public class ReportWrapper {
		public String trial {get;set;}
		public String ispy2_id {get;set;}
		public String trial_site {get;set;}
		public Date screening_consent_date {get;set;}
		public Date reg_date {get;set;}
		public String treatment_consent_date {get;set;}
		public String reason_not_signed_consent {get;set;}
		public String gender {get;set;}
		public String race {get;set;}
		public String ethnicity {get;set;}
		public String zip {get;set;}
		public Date dob {get;set;}
		
	}
}