src/objects/Core_Biopsy_Specimens__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Other_Reason_samples_not_shipped__c</fullName>
        <label>Other (Reason samples not shipped)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_samples_not_shipped__c</fullName>
        <label>Reason samples not shipped</label>
        <picklist>
            <controllingField>Shipped__c</controllingField>
            <picklistValues>
                <fullName>Spilled on floor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thawed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipped__c</fullName>
        <label>Shipped?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SpecimenID__c</fullName>
        <label>Specimen ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TissueSpecimenDetail__c</fullName>
        <label>Tissue Specimen Detail</label>
        <referenceTo>TissueSpecimenDetail__c</referenceTo>
        <relationshipLabel>Core Biopsy Specimens</relationshipLabel>
        <relationshipName>Core_Biopsy_Specimens</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Core Biopsy Specimens</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Core Biopsy Specimens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Date_patient_went_off_study__c</fullName>
        <label>Date patient went off study</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective_Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Patient_Died__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient Died</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_completed_study_per_protocol__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient completed study per protocol</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_not_have_surgery__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not have surgery.</description>
        <inlineHelpText>Patient did not have surgery.</inlineHelpText>
        <label>Patient did not have surgery</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_not_want_to_complete_MRI__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not want to complete study MRI scans.</description>
        <inlineHelpText>Patient did not want to complete study MRI scans.</inlineHelpText>
        <label>Patient did not want to complete MRI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_nt_continue_on_treatment_arm__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not continue on treatment arm.</description>
        <inlineHelpText>Patient did not continue on treatment arm.</inlineHelpText>
        <label>Patient did&apos;nt continue on treatment arm</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_did_nt_want_to_complete_core_bio__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient did not want to complete study core biopsy.</description>
        <inlineHelpText>Patient did not want to complete study core biopsy.</inlineHelpText>
        <label>Patient did&apos;nt want to complete core bio</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Initials__c</fullName>
        <formula>TRIM(LEFT( First_Name__c , 1) ) &amp; &apos;&apos; &amp;  TRIM( LEFT( Middle_Name__c , 1) ) &amp; &apos;&apos; &amp;  TRIM( LEFT( Last_Name__c , 1) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Initials</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institute_Text__c</fullName>
        <label>Institute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TissueSpecimenDetail__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Time__c</fullName>
        <label>Effective Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Tissue Specimen CRF</relationshipLabel>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tissue Specimen Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tissue Specimen Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OffStudyPdfGenerator.cls
public with sharing class OffStudyPdfGenerator {
   
    public Off_Study_Detail__c offStudyObj {get;set;}
    //public List<CoreBiopsyWrapper> lstCoreBiopsyWrapper {get;set;}
    public TrialPatient__c trialPatientObj {get;set;}
    public Patient_Custom__c Patient {get;set;}
    public string initials {get;set;}

   
    public OffStudyPdfGenerator(Apexpages.StandardController std) {
        string offStudyIdValue = ApexPages.currentPage().getParameters().get('Id');
        //lstCoreBiopsyWrapper = new List<CoreBiopsyWrapper>();
        offStudyObj = new Off_Study_Detail__c ();
        if(offStudyIdValue != null)
            offStudyObj = [Select TrialPatient__r.Patient_Id__c,Date_patient_went_off_study__c,Patient_completed_study_per_protocol__c,Patient_did_nt_continue_on_treatment_arm__c,Patient_did_nt_want_to_complete_core_bio__c,Patient_did_not_have_surgery__c,Patient_did_not_want_to_complete_MRI__c,Patient_Died__c,status__c,TrialPatient__c From Off_Study_Detail__c  where id =:offStudyIdValue];
       // system.assert(false,Off_Study_Detail__c.status__c);
       // List<Core_Biopsy_Specimens__c>  tmpCoreBiopsyList = new  List<Core_Biopsy_Specimens__c> ();
       // tmpCoreBiopsyList = [Select TissueSpecimenDetail__c, SpecimenID__c, Shipped__c, Reason_samples_not_shipped__c, Other_Reason_samples_not_shipped__c From Core_Biopsy_Specimens__c  where TissueSpecimenDetail__c = :tissueSpecimenForm.Id order by Effective_Time__c DESC];
        
       /* integer coreBiopsyNumber = 0;
        for(Core_Biopsy_Specimens__c cbs : tmpCoreBiopsyList) {
            if(cbs.Shipped__c != null) {
                CoreBiopsyWrapper cbWrapper = new CoreBiopsyWrapper(); 
                cbWrapper.coreBiopsySpecimen = cbs;
                cbWrapper.coreBiopsyNumber = 'Core Specimen #'+(++coreBiopsyNumber)+' (Frozen)';
                lstCoreBiopsyWrapper.add(cbWrapper);
            }
        }*/
        
        if(offStudyObj.TrialPatient__r.Patient_Id__c != null){
            trialPatientObj  = [select Subject_Id__c from TrialPatient__c where id=:offStudyObj.TrialPatient__c];
            Patient = [select initials__c,Institute_Text__c from Patient_Custom__c where id=:offStudyObj.TrialPatient__r.Patient_Id__c];
        }
    }
    
    public class CoreBiopsyWrapper {
        public String coreBiopsyNumber {get;set;}
        public Core_Biopsy_Specimens__c coreBiopsySpecimen {get;set;}
    }
     
}