src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registration</label>
        <referenceTo>Registration__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CRFMaster__c.object
<CustomObject>
    <fields>
        <fullName>CRFType__c</fullName>
        <label>CRFType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CRFMaster</label>
    <nameField>
        <label>CRF Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRFMasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institute_Text__c</fullName>
        <label>Institute</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase Master</label>
        <referenceTo>Phase_Master__c</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Signed_Screening__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Signed Screening Consent Form</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TestHarnessId__c</fullName>
        <externalId>true</externalId>
        <label>TestHarnessId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Phase_CRFs__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <label>CRF</label>
        <referenceTo>CRFMaster__c</referenceTo>
        <relationshipLabel>Phases CRFs</relationshipLabel>
        <relationshipName>Phases_CRFs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phase_Cycle__c</fullName>
        <label>Phase Cycle</label>
        <referenceTo>Phase_Cycle__c</referenceTo>
        <relationshipLabel>Phases CRFs</relationshipLabel>
        <relationshipName>Phases_CRFs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase CRFs</label>
    <nameField>
        <label>Phase CRF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases CRFs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Phase_Cycle__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <referenceTo>Phase_Master__c</referenceTo>
        <relationshipLabel>Phase Cycles</relationshipLabel>
        <relationshipName>Phase_Cycles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Phase Cycle</label>
    <nameField>
        <label>Phase Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phase Cycles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Phase_Master__c.object
<CustomObject>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Phase Master</label>
    <nameField>
        <label>Phase Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PreEligibility_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>CRF_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRF Id</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OriginalCRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriginalCRF</label>
        <referenceTo>PreEligibility_Checklist__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_signed_up_for_I_SPY2_screening__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient signed up for I-SPY2 screening form.</inlineHelpText>
        <label>Patient signed up for I-SPY2 screening</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PreEligibility Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PreEligibility Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PreEligibility Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalCRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriginalCRF</label>
        <referenceTo>Registration__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreEligibility_Checklist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PreEligibility Checklist</label>
        <referenceTo>PreEligibility_Checklist__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PreEligibilityConsent.cls
public with sharing class PreEligibilityConsent {
    public List<Patient_Custom__c> patientList {get;set;}
    public PreEligibilityConsent(){
        patientList = new List<Patient_Custom__c>();
        List<Patient_Custom__c> pList = [Select p.Signed_Screening__c, p.Name, p.Institution__c, p.Institute_Text__c, p.CreatedDate, (Select Name From Registrations__r order by LastModifiedDate desc limit 1), (Select Name, LastModifiedDate From PreEligibility_Checklists__r where Patient_signed_up_for_I_SPY2_screening__c = true) From Patient_Custom__c p];
        if(!pList.isEmpty()){
            for(Patient_Custom__c p : pList){
                if(p.Registrations__r.size() > 0)continue;
                if(p.PreEligibility_Checklists__r.size() < 1)continue;
                patientList.add(p);
            }       
        }
    }
    @isTest public static void  test1(){
        Account acc = new Account();
        acc.Name = 'testing';
        insert acc;
        
        CRFMaster__c crfMaster = new CRFMaster__c();
        crfMaster.CRFType__c = 'Patient Registration Form';
        crfMaster.CRFType__c = 'Registration__c';
        crfMaster.Object_Name__c = 'Registration__c';
        insert crfMaster;
        
        Phase_Master__c phMaster = new Phase_Master__c();
        phMaster.Name = 'Screening';
        phMaster.Order__c = 108;  
        insert phMaster;
        
        Phase_Cycle__c phc = new Phase_Cycle__c();
        phc.Phase__c = phMaster.id;
        phc.Order__c = 110;
        insert phc;
        
        Phase_CRFs__c phCrf = new Phase_CRFs__c();
        phCrf.Phase_Cycle__c = phc.id;
        phCrf.CRF__c = crfMaster.Id;
        insert phCrf;
        
        Patient_Custom__c pt = new Patient_Custom__c();
        pt.Name = 'testPatient';
        pt.Institution__c = acc.id;
        pt.Last_Name__c = 'test';
        pt.Birthdate__c = date.newInstance(1970, 04, 05);
        pt.Gender__c = 'Male';
        pt.Race__c = 'White';
        pt.Ethnicity__c = 'Not Hispanic or Latino';
        pt.TestHarnessId__c = 'asc002';
        insert pt;
        
        Trial__c tc = new Trial__c();
        tc.Name = 'testTrial';
        insert tc;
        
        PreEligibilityConsent pElgibility = new PreEligibilityConsent();
    }
}