src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ProtocolViolationDetail__c.object
<CustomObject>
    <fields>
        <fullName>CRFId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRFId</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Protocol Violation Details</relationshipLabel>
        <relationshipName>Protocol_Violation_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Eligibility_criteria_exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Eligibility criteria exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrollment_of_ineligeligibleible_patient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enrollment of ineligeligibleible patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Incorrect_therapy_given_to_patient__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Incorrect therapy given to patient</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Medication_non_complicance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Medication non-compliance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_study_procedure_required_by_protocol__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On-study procedure required by protocol not completed.</description>
        <inlineHelpText>On-study procedure required by protocol not completed.</inlineHelpText>
        <label>On-study procedure required by protocol</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Action_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other Action Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_Violation_Checkbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other_Violation_Checkbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_Remains_on_Study__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Patient Remains on Study but data analysis will be modified.</description>
        <inlineHelpText>Patient Remains on Study but data analysis will be modified.</inlineHelpText>
        <label>Patient Remains on Study</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Protocol Violation Details</relationshipLabel>
        <relationshipName>Protocol_Violation_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_became_pregnant_prior_to_surgery__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient became pregnant prior to surgery</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_withdrawn__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Patient withdrawn</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Screening_and_on_study_test_lab_done__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Screening and on-study test/lab done outside the protocol required time.</description>
        <inlineHelpText>Screening and on-study test/lab done outside the protocol required time.</inlineHelpText>
        <label>Screening and on-study test/lab done</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Screening_procedure_required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Screening procedure required by protocol not done.</description>
        <inlineHelpText>Screening procedure required by protocol not done.</inlineHelpText>
        <label>Screening procedure required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Protocol Violation CRF</relationshipLabel>
        <relationshipName>Protocol_Violation_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_non_complicance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Visit non-complicance</label>
        <type>Checkbox</type>
    </fields>
    <label>Protocol Violation Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Protocol Violation Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Lab</fullName>
        <active>true</active>
        <label>Lab</label>
    </recordTypes>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProtocolViolationsController.cls
Public with sharing class ProtocolViolationsController{
    public String data{get;set;}
    Map<String,ActionWrapper> mapActionWrapper = new Map<String,ActionWrapper >();
    ActionWrapper aw = new ActionWrapper();
    public ProtocolViolationsController(){
       data = '[\'Type\',\' Patient Withdrawn\',\' Patient Remain on Study\',\' Other\'],';
       getData();
       Integer i =1;
       if(mapActionWrapper.keyset().size() == 0)
           data += '[\'No Data\',0,0,0]';    
       else{
           
           for(String type : mapActionWrapper.keyset()){
               data += '[\''+type +'\','; 
               ActionWrapper  aw = mapActionWrapper.get(type);
               data += aw.patientWithDrawn+',';
               data += aw.patientRemainOnStudy+',';
               if(i == mapActionWrapper.keyset().size())
                   data += aw.otherAction+']';
               else
                   data += aw.otherAction+'],';    
                   
               i++ ;
           }//System.assert(false,mapActionWrapper+'******'+data);
       }    
    }
    public void getData() {
        List<ProtocolViolationDetail__c> protocolv ;
        String instituteId = ApexPages.CurrentPage().getParameters().get('institute');
        String siteId = ApexPages.CurrentPage().getParameters().get('site');
        String trialId = ApexPages.CurrentPage().getParameters().get('trial');
        System.debug('****'+InstituteId+'****'+siteId+'******'+trialId);
        if((siteId != '' && siteId != null) || (instituteId != '' && instituteId != null) || (trialId != '' && trialId != null)){    
            String condition ='';
            if(instituteId != '' && instituteId != null){
                condition ='CRFId__r.Patient__r.Institution__c=\''+instituteId+'\'' ;
            }
            if(siteId != '' && siteId != null){
                 condition +='TrialPatient__r.Site__c IN ('+siteId+')';
            }
            if(trialId != '' && trialId != null){
               condition +='and CRFId__r.Trial__c=\''+trialId+'\'';
             } 
             System.debug('==========Select id, Incorrect_therapy_given_to_patient__c, Patient_withdrawn__c, Patient_Remains_on_Study__c, Other_Action_Checkbox__c, Other_Violation_Checkbox__c, Eligibility_criteria_exception__c, Enrollment_of_ineligeligibleible_patient__c, Medication_non_complicance__c, On_study_procedure_required_by_protocol__c, Patient_became_pregnant_prior_to_surgery__c, Screening_and_on_study_test_lab_done__c, Screening_procedure_required__c, Visit_non_complicance__c from ProtocolViolationDetail__c where '+condition);
          protocolv = database.query('Select id, Incorrect_therapy_given_to_patient__c, Patient_withdrawn__c, Patient_Remains_on_Study__c, Other_Action_Checkbox__c, Other_Violation_Checkbox__c, Eligibility_criteria_exception__c, Enrollment_of_ineligeligibleible_patient__c, Medication_non_complicance__c, On_study_procedure_required_by_protocol__c, Patient_became_pregnant_prior_to_surgery__c, Screening_and_on_study_test_lab_done__c, Screening_procedure_required__c, Visit_non_complicance__c from ProtocolViolationDetail__c where '+condition) ;
          
      }
      else {
          protocolv = [Select id, Incorrect_therapy_given_to_patient__c, Patient_withdrawn__c, Patient_Remains_on_Study__c, Other_Action_Checkbox__c, Other_Violation_Checkbox__c, Eligibility_criteria_exception__c, Enrollment_of_ineligeligibleible_patient__c, Medication_non_complicance__c, On_study_procedure_required_by_protocol__c, Patient_became_pregnant_prior_to_surgery__c, Screening_and_on_study_test_lab_done__c, Screening_procedure_required__c, Visit_non_complicance__c from ProtocolViolationDetail__c ];    
      }
      
       for (ProtocolViolationDetail__c pvd : protocolv ) {
            if (pvd.Incorrect_therapy_given_to_patient__c) {
                loadMap(pvd,'Incorrect therapy given to patient');         
            }
             if (pvd.Eligibility_criteria_exception__c) {
                loadMap(pvd,'Eligibility criteria exception');         
            }
           
             if (pvd.Enrollment_of_ineligeligibleible_patient__c) {
                loadMap(pvd,'Enrollment of ineligeligibleible patient');         
            }
             if (pvd.Medication_non_complicance__c) {
                loadMap(pvd,'Medication non-compliance');         
            }
             if (pvd.On_study_procedure_required_by_protocol__c) {
                loadMap(pvd,'On-study procedure required by protocol');         
            }
             if (pvd.Other_Violation_Checkbox__c) {
                loadMap(pvd,'Other Type of Violation');         
            }
             if (pvd.Patient_became_pregnant_prior_to_surgery__c) {
                loadMap(pvd,'Patient became pregnant prior to surgery');         
            }
             if (pvd.Screening_procedure_required__c) {
                loadMap(pvd,'Screening procedure required');         
            }
             if (pvd.Visit_non_complicance__c) {
                loadMap(pvd,'Visit non-complicance');         
            }
             if (pvd.Screening_and_on_study_test_lab_done__c) {
                loadMap(pvd,'Screening and on-study test/lab done');         
            }
            
        }
        
      } 
     void loadMap(ProtocolViolationDetail__c pvd, String key) {
        if (!mapActionWrapper.containskey(key)) {
             mapActionWrapper.put(key, new ActionWrapper());
             aw = new ActionWrapper(); 
         }
         else {
             aw = mapActionWrapper.get(key); 
         }
         if (pvd.Other_Action_Checkbox__c == true) {
             aw.otherAction = aw.otherAction + 1; 
         }
         if (pvd.Patient_Remains_on_Study__c== true) {
             aw.patientRemainOnStudy= aw.patientRemainOnStudy + 1;
         }
         if (pvd.Patient_withdrawn__c == true) {
             aw.patientWithDrawn = aw.patientWithDrawn + 1;
         }
         mapActionWrapper.put(key,aw);          
    }  
    public class ActionWrapper {
        
        public integer otherAction{get;set;}
        public integer patientRemainOnStudy{get;set;}
        public integer patientWithDrawn{get;set;}
        
        public ActionWrapper() {
            otherAction = 0;
            patientRemainOnStudy = 0;
            patientWithDrawn = 0;
        }
    }      
}