src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Followup_Form__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Followup Forms</relationshipLabel>
        <relationshipName>Followup_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_dose_cGy_AP__c</fullName>
        <label>Total dose (cGy)  AP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Followup Forms</relationshipLabel>
        <relationshipName>Followup_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Followup Form</label>
    <nameField>
        <displayFormat>FF-{00000}</displayFormat>
        <label>Followup Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Followup Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Irradiated_Site__c.object
<CustomObject>
    <fields>
        <fullName>Followup_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Followup Form</label>
        <referenceTo>Followup_Form__c</referenceTo>
        <relationshipLabel>Irradiated Sites</relationshipLabel>
        <relationshipName>Irradiated_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <picklist>
            <picklistValues>
                <fullName>Breast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Axilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supraclavicular node</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal mammary node</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chest wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_dose_cGy_AP__c</fullName>
        <label>Total dose (cGy)  AP</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Irradiated Site</label>
    <nameField>
        <label>Irradiated Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Irradiated Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecurityCode__c</fullName>
        <label>SecurityCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestIrradiatedSiteTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestIrradiatedSiteTrigger {

    @isTest static void myUnitTest() {
        Profile SiteProp = [ Select p.UserType, p.Name, (Select u.IsActive, u.Id, SecurityCode__c From Users u where IsActive = true) From Profile p where Name = 'Site User'];
        List<User> lstSiteUser = SiteProp.Users;     
        System.runAs ( lstSiteUser[0] ) { 
        
            Account acc = new Account();
            List<Account> lstAccount = [select Id from Account limit 1];
            if(!lstAccount.isEmpty()) {
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; 
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                CRF__c crf = new CRF__c();
                crf.Patient__c = p.Id;
                insert crf;
            
                Followup_Form__c ff1=new Followup_Form__c();
                ff1.TrialPatient__c = tp.Id;
                insert ff1;
                
                Irradiated_Site__c thRec1 = new Irradiated_Site__c();
                thRec1.Followup_Form__c = ff1.Id;
                thRec1.Site__c = 'Boost';
                thRec1.Total_dose_cGy_AP__c = 2.0;
                insert thRec1;
                
                thRec1.Site__c = 'Boost';
                update thRec1;
            }
        }
            
    }
    
    @isTest static void myUnitTest2() {
        Profile SiteProp = [ Select p.UserType, p.Name, (Select u.IsActive, u.Id, SecurityCode__c From Users u where IsActive = true) From Profile p where Name = 'Site User'];
        List<User> lstSiteUser = SiteProp.Users;     
        System.runAs ( lstSiteUser[0] ) { 
        
            Account acc = new Account();
            List<Account> lstAccount = [select Id from Account limit 1];
            if(!lstAccount.isEmpty()) {
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; 
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                CRF__c crf = new CRF__c();
                crf.Patient__c = p.Id;
                insert crf;
            
                Followup_Form__c ff1=new Followup_Form__c();
                ff1.TrialPatient__c = tp.Id;
                insert ff1;
                
                Irradiated_Site__c thRec2 = new Irradiated_Site__c();
                thRec2.Followup_Form__c = ff1.Id;
                thRec2.Site__c = 'Axilla';
                thRec2.Total_dose_cGy_AP__c = 2.0;
                insert thRec2;
                
                thRec2.Site__c = 'Axilla';
                update thRec2;
            }
        }
            
    }
    
    @isTest static void myUnitTest3() {
        Profile SiteProp = [ Select p.UserType, p.Name, (Select u.IsActive, u.Id, SecurityCode__c From Users u where IsActive = true) From Profile p where Name = 'Site User'];
        List<User> lstSiteUser = SiteProp.Users;     
        System.runAs ( lstSiteUser[0] ) { 
        
            Account acc = new Account();
            List<Account> lstAccount = [select Id from Account limit 1];
            if(!lstAccount.isEmpty()) {
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; 
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                CRF__c crf = new CRF__c();
                crf.Patient__c = p.Id;
                insert crf;
            
                Followup_Form__c ff1=new Followup_Form__c();
                ff1.TrialPatient__c = tp.Id;
                insert ff1;
                
                Irradiated_Site__c thRec3 = new Irradiated_Site__c();
                thRec3.Followup_Form__c = ff1.Id;
                thRec3.Site__c = 'Supraclavicular node';
                thRec3.Total_dose_cGy_AP__c = 2.0;
                insert thRec3;
                
                thRec3.Site__c = 'Supraclavicular node';
                update thRec3;
            }
        }
            
    }
    
    @isTest static void myUnitTest4() {
        Profile SiteProp = [ Select p.UserType, p.Name, (Select u.IsActive, u.Id, SecurityCode__c From Users u where IsActive = true) From Profile p where Name = 'Site User'];
        List<User> lstSiteUser = SiteProp.Users;     
        System.runAs ( lstSiteUser[0] ) { 
        
            Account acc = new Account();
            List<Account> lstAccount = [select Id from Account limit 1];
            if(!lstAccount.isEmpty()) {
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; 
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                CRF__c crf = new CRF__c();
                crf.Patient__c = p.Id;
                insert crf;
            
                Followup_Form__c ff1=new Followup_Form__c();
                ff1.TrialPatient__c = tp.Id;
                insert ff1;
                
                Irradiated_Site__c thRec4 = new Irradiated_Site__c();
                thRec4.Followup_Form__c = ff1.Id;
                thRec4.Site__c = 'Internal mammary node';
                thRec4.Total_dose_cGy_AP__c = 2.0;
                insert thRec4;
                
                thRec4.Site__c = 'Internal mammary node';
                update thRec4;
            }
        }
            
    }
    
    @isTest static void myUnitTest5() {
        Profile SiteProp = [ Select p.UserType, p.Name, (Select u.IsActive, u.Id, SecurityCode__c From Users u where IsActive = true) From Profile p where Name = 'Site User'];
        List<User> lstSiteUser = SiteProp.Users;     
        System.runAs ( lstSiteUser[0] ) { 
        
            Account acc = new Account();
            List<Account> lstAccount = [select Id from Account limit 1];
            if(!lstAccount.isEmpty()) {
                acc = lstAccount[0];
                
                Patient_Custom__c p = new Patient_Custom__c();
                p.Birthdate__c = date.newInstance(1980, 08, 05);
                p.Institution__c = acc.Id;
                p.Last_Name__c = 'test'; 
                p.Gender__c = 'Male';
                p.Race__c = 'White';
                p.Ethnicity__c = 'Not Hispanic or Latino';
                insert p;
                
                TrialPatient__c tp = new TrialPatient__c();
                tp.Patient_Id__c = p.Id;
                insert tp;
                
                CRF__c crf = new CRF__c();
                crf.Patient__c = p.Id;
                insert crf;
            
                Followup_Form__c ff1=new Followup_Form__c();
                ff1.TrialPatient__c = tp.Id;
                insert ff1;
                
                Irradiated_Site__c thRec5 = new Irradiated_Site__c();
                thRec5.Followup_Form__c = ff1.Id;
                thRec5.Site__c = 'Internal mammary node';
                thRec5.Total_dose_cGy_AP__c = 2.0;
                insert thRec5;
                
                thRec5.Site__c = 'IHTSDO_4585';
                update thRec5;
            }
        }
            
    }
}