src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Disease_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Clip_placed__c</fullName>
        <label>Clip placed</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Response_Evaluation_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Response Evaluation Form</label>
        <referenceTo>Response_Evaluation_Form__c</referenceTo>
        <relationshipLabel>Disease Assessments</relationshipLabel>
        <relationshipName>Disease_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disease Assessment</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disease Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Response_Evaluation_Form__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>Response Evaluation Forms</relationshipLabel>
        <relationshipName>Response_Evaluation_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinical_Staging_Period__c</fullName>
        <label>Clinical Staging Period</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clinically_staging_period_M__c</fullName>
        <label>Clinically staging period M</label>
        <picklist>
            <picklistValues>
                <fullName>M0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clinically_staging_period_N__c</fullName>
        <label>Clinically staging period N</label>
        <picklist>
            <picklistValues>
                <fullName>N0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N2a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N2b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N3a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N3b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N3c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Clinically_staging_period_T__c</fullName>
        <label>Clinically staging period T</label>
        <picklist>
            <picklistValues>
                <fullName>T0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T1a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T1b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T1c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T4a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T4b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T4c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T4d</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T1mi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matted_nodes__c</fullName>
        <label>Matted nodes</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Palpable_nodes__c</fullName>
        <label>Palpable nodes</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ReasonNotConservationSurgeryCandidate__c</fullName>
        <label>ReasonNotConservationSurgeryCandidate</label>
        <picklist>
            <picklistValues>
                <fullName>Multi-centric disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inflammatory disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diffuse micro calcifications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient choice/family history</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Institutional norm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specific anatomy of primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Response Evaluation Forms</relationshipLabel>
        <relationshipName>Response_Evaluation_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Response Evaluation Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Evaluation Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecurityCode__c</fullName>
        <label>SecurityCode</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestResponseEvaluationFormController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestResponseEvaluationFormController {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
        
        List<User> lstSiteUser = [Select u.IsActive, u.Id, SecurityCode__c From User u where IsActive = true and Profile.Name = 'Site User'];     
        System.runAs ( lstSiteUser[0] ) { 
        
        Account acc = new Account();
        
        List<Account> lstAccount = [Select a.Id From Account a limit 1];
        
        if(!lstAccount.isEmpty()){
            
        acc = lstAccount[0];
        
        ResponseEvaluationFormController refc = new ResponseEvaluationFormController();
      
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1950, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; // patient
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        insert tp;
        
        CRF__c crf = new CRF__c();
        crf.Status__c = 'Accepted';
        crf.Patient__c = p.Id;
        insert crf;
        
        //=======================line 55 else part , since i havent "inserted" Response_Evaluation_Form__c============
        
        Response_Evaluation_Form__c rev1 = new Response_Evaluation_Form__c();
        rev1.TrialPatient__c = tp.Id;
        rev1.CRF__c = crf.Id;
        rev1.Status__c = 'Not Completed';
        
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id); 
        Apexpages.StandardController std1 = new Apexpages.StandardController(rev1);
        ResponseEvaluationFormController rfc1 = new ResponseEvaluationFormController(std1);
            
            //======================finished==============================================================================
        }
    }  
}
    @isTest static void myUnitTest1() {
        // TO DO: implement unit test
        
        List<User> lstSiteUser = [Select u.IsActive, u.Id, SecurityCode__c From User u where IsActive = true and Profile.Name = 'Site User'];
             
        System.runAs(lstSiteUser[0]){ 
        
        Account acc = new Account();
        
        List<Account> lstAccount = [Select a.Id From Account a limit 1];
        
        if(!lstAccount.isEmpty()){
            
        acc = lstAccount[0];
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1950, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; // patient
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        
        insert tp;
        
        Response_Evaluation_Form__c rev = new Response_Evaluation_Form__c();
        rev.TrialPatient__c = tp.Id;
        rev.Clinical_Staging_Period__c = 'Yes';
        rev.Clinically_staging_period_T__c = 'T4';
        rev.Clinically_staging_period_N__c = 'N1a';
        rev.Clinically_staging_period_M__c = 'M1';
        rev.ReasonNotConservationSurgeryCandidate__c = 'Multi-centric disease';
        rev.Palpable_nodes__c = 'Yes';
        rev.Matted_nodes__c = null;  
        rev.Status__c = 'Not Completed'; 
        insert rev;
                  
        rev.Status__c = 'Accepted'; 
        update rev;
            
        Disease_Assessment__c da = new Disease_Assessment__c();
        da.Clip_placed__c = 'No';
        da.O_Clock_Position_To__c = '3';
        da.O_Clock_Position_From__c = '1';
        da.Longest_Diameter__c = 23.0;
        da.Distance_from_nipple__c = 23.0;
        da.Response_Evaluation_Form__c = rev.Id;
        insert da;
        
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        Apexpages.StandardController std = new Apexpages.StandardController(rev);
        ResponseEvaluationFormController rfc = new ResponseEvaluationFormController(std);
        rfc.getTargetLesionSNo();
        rfc.responseEval = rev;
        rfc.currentTab = 'DiseaseAssessmetTab';  // causing error null pointer exception
        rfc.next();  
        rfc.currentTab = 'responseStatus';
        rfc.next();
        rfc.currentTab = 'CommentsAndAttachments';
        rfc.next();
        Apexpages.currentPage().getParameters().put('tabNext','saveAndClose');
        rfc.nextTabName = 'saveAndClose';
        rfc.next();
        
        Apexpages.currentPage().getParameters().put('tabPrevious','CommentsAndAttachments');
        rfc.currentTab = 'Complete';
        rfc.previous();
        
        rfc.currentTab = 'CommentsAndAttachments';
        rfc.previous();
        
        rfc.currentTab = 'responseStatus';
        rfc.previous();
        
        rfc.responseEval = rev;
        
        rfc.respEvalId = rev.Id;
        rfc.editResponseEvaluationForm();
        rfc.signAndSubmit();
        ResponseEvaluationFormController.DiseaseAssessmentWrapper dac = new ResponseEvaluationFormController.DiseaseAssessmentWrapper();
        dac.isReadOnly = true;
        dac.targetLesion = 1;
        dac.diseaseAssessment = da;
               
                
       ResponseEvaluationFormController.DiseaseAssessmentWrapper dac1 = new ResponseEvaluationFormController.DiseaseAssessmentWrapper();
       dac1.isReadOnly = true;
       dac1.diseaseAssessment = da;
       
       dac1.diseaseAssessment.Clip_placed__c = dac.diseaseAssessment.Clip_placed__c;
       dac1.diseaseAssessment.Distance_from_nipple__c = dac.diseaseAssessment.Distance_from_nipple__c;
       dac1.diseaseAssessment.Longest_Diameter__c = dac.diseaseAssessment.Longest_Diameter__c;
       dac1.diseaseAssessment.O_Clock_Position_To__c = dac.diseaseAssessment.O_Clock_Position_To__c;
       dac1.diseaseAssessment.O_Clock_Position_From__c = dac.diseaseAssessment.O_Clock_Position_From__c;
       dac1.targetLesion = dac.targetLesion;
        
       List<ResponseEvaluationFormController.DiseaseAssessmentWrapper> lstDAW = new List<ResponseEvaluationFormController.DiseaseAssessmentWrapper>();
       lstDAW.add(dac1);
       rfc.lstDiseaseAssessmentWrapper = lstDAW;
       rfc.saveDiseaseAssessment();
       system.debug('lstDiseaseAssessmentWrapper-----' +rfc.lstDiseaseAssessmentWrapper[0].diseaseAssessment.Id);
       Apexpages.currentPage().getParameters().put('recordId',rfc.lstDiseaseAssessmentWrapper[0].diseaseAssessment.Id);
       rfc.editDAssessment();
       Apexpages.currentPage().getParameters().put('cancelIndex','1');
       rfc.updateRecord();
       rfc.addLesion();
       
       rfc.respEvalId = null;
      // rfc.saveMainCRF();
       
       rfc.submitCRF();
       //rfc.cancelCRF();
      // rfc.signAndSubmit();
       rfc.editCRF();
       rfc.resendCode();
       rfc.cloneCRF();
       rfc.cancelCRF();
       rfc.cancel(); 
       rfc.remove();
      }
    }  
  }
  @isTest static void ResponseEvaluationAfterTrigger() {
        // TO DO: implement unit test
        
        Account acc = new Account();
        acc.Name = 'test';
        insert acc; 
      
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1950, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; 
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
        
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        insert tp;
        
        Response_Evaluation_Form__c rev1 = new Response_Evaluation_Form__c();
        rev1.TrialPatient__c = tp.Id;
        rev1.Status__c = 'Approval Pending';
        rev1.Reporting__c = 'Inter-regimen';
        insert rev1;
        rev1.Status__c = 'Accepted';
        update rev1;
  }
}