src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Phase_Master__c.object
<CustomObject>
    <label>Phase Master</label>
    <nameField>
        <label>Phase Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phases Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Phase_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Phase Master</label>
        <referenceTo>Phase_Master__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OverdueCRFDrillDown.cls
Public with sharing class OverdueCRFDrillDown{
    public String data{get;set;}
    public OverdueCRFDrillDown(){
        data =  '[\'Phase\',\' CRF Name\',\'Subject ID\'],';
        Set<Id> registrationId= new Set<Id>();
        set<Id> noofpatient = new set<Id>();
        String drilldownfiled = ApexPages.CurrentPage().getParameters().get('drilldown');
        List<Task> alltask = database.query('Select t.CRF_Form_Id__c,t.whatId From Task t where (t.Status = \'In Progress\' OR t.Status = \'Not Started\') AND t.WhatId != null AND t.Original_Due_Date__c = LAST_N_DAYS:15 AND t.CRF_Form_Id__c != null AND t.Object_Name__c != null order by CreatedDate asc ');
        List<AggregateResult> reg;
        Map<String,String> mapSites = new Map<String,String>();
    //System.assert(false,alltask );
        
            for(Task task: alltask){
                registrationId.add(task.whatId);  
            }
            
        List<CRF__c>  registraedPatient;
        if(drilldownfiled  == '')
                registraedPatient = [Select TrialPatient__r.Phase_Master__r.Name, Type__c, TrialPatient__r.Subject_Id__c from CRF__c where Patient__c in:registrationId and TrialPatient__r.site__c != null and TrialPatient__r.Phase_Master__r.Name != null ];
        else
            registraedPatient = [Select TrialPatient__r.Phase_Master__r.Name, Type__c, TrialPatient__r.Subject_Id__c from CRF__c where Patient__c in:registrationId and TrialPatient__r.site__c != null and TrialPatient__r.Phase_Master__r.Name !=null and TrialPatient__r.Site__r.Name = :drilldownfiled];
        integer count=1;
        for(CRF__c c : registraedPatient){
            String type = c.Type__c.replace('__c','');
            String type1 = type.replace('_',' ');
            if(count == registraedPatient.size())
                data += '[\''+c.TrialPatient__r.Phase_Master__r.Name+'\',\''+type1+'\',\''+c.TrialPatient__r.Subject_Id__c+'\']';
            else    
                data += '[\''+c.TrialPatient__r.Phase_Master__r.Name+'\',\''+type1+'\',\''+c.TrialPatient__r.Subject_Id__c+'\'],';   
            count++;     
        }
        
       
       
    }
         
        
}