src/objects/CRF__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>CRFs</relationshipLabel>
        <relationshipName>CRFs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CRF</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>CRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRFs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MammaPrintDetail__c.object
<CustomObject>
    <fields>
        <fullName>CRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRF</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>MammaPrint Details</relationshipLabel>
        <relationshipName>MammaPrint_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tissue_Specimen_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tissue Specimen Detail</label>
        <referenceTo>TissueSpecimenDetail__c</referenceTo>
        <relationshipLabel>MammaPrint Details</relationshipLabel>
        <relationshipName>MammaPrint_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>MammaPrint CRF</relationshipLabel>
        <relationshipName>MammaPrint_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MammaPrint Microarray Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MammaPrint Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TissueSpecimenDetail__c.object
<CustomObject>
    <fields>
        <fullName>CRFId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CRFId</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Point__c</fullName>
        <label>Time Point</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Early Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Treatment Re-Biopsy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Surgery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Tissue Specimen CRF</relationshipLabel>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tissue Specimen Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tissue Specimen Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/pretreatmentCompltMammafilledController.cls
Public with sharing class pretreatmentCompltMammafilledController{
    public String data{get;set;}
    public pretreatmentCompltMammafilledController(){
         data = '[\'Type\',\' Number Of Patients\'],';
         set<Id> patientPreTreatment = new set<Id>();
         set<Id> patientMammaprint = new set<Id>();
         String siteId = ApexPages.CurrentPage().getParameters().get('site');
         if((siteId != '' && siteId != null) ){
            String condition ='';
            if(siteId != '' && siteId != null){
                 condition +='and TrialPatient__r.Site__c IN ('+siteId+')';
            }
            List<TissueSpecimenDetail__c > pretreatment =    database.query('SELECT CRFId__r.Patient__c FROM TissueSpecimenDetail__c where Time_Point__c  = \'Pre-Treatment\' and CRFId__r.Patient__c != null '+condition);  
            for(TissueSpecimenDetail__c  ts : pretreatment )
            patientPreTreatment.add(ts.CRFId__r.Patient__c);
            
            List<MammaPrintDetail__c > mammaprint = database.query('Select CRF__r.Patient__c , Tissue_Specimen_Detail__c From MammaPrintDetail__c where  Status__c = \'Approval Not Required\' and Tissue_Specimen_Detail__c in (SELECT Id  FROM TissueSpecimenDetail__c where Time_Point__c  = \'Pre-Treatment\') '+condition);
               for(MammaPrintDetail__c  ts : mammaprint )
                patientMammaprint.add(ts.CRF__r.Patient__c); 
             
         }    
         else{
              List<TissueSpecimenDetail__c > pretreatment =    database.query('SELECT CRFId__r.Patient__c FROM TissueSpecimenDetail__c where Time_Point__c  = \'Pre-Treatment\' and CRFId__r.Patient__c != null ');  
              for(TissueSpecimenDetail__c  ts : pretreatment )
                  patientPreTreatment.add(ts.CRFId__r.Patient__c);
            List<MammaPrintDetail__c > mammaprint = [Select CRF__r.Patient__c , Tissue_Specimen_Detail__c From MammaPrintDetail__c 
                where  Status__c = 'Approval Not Required' and Tissue_Specimen_Detail__c in (SELECT Id  FROM TissueSpecimenDetail__c where Time_Point__c  = 'Pre-Treatment') ];
           
            for(MammaPrintDetail__c  ts : mammaprint )
                patientMammaprint.add(ts.CRF__r.Patient__c);     
        }
        List<Patient_Custom__c> patientcount1 = [select id from Patient_Custom__c where Id in :patientPreTreatment];         
        List<Patient_Custom__c> patientcount2 = [select id from Patient_Custom__c where Id in :patientMammaprint];     
        if(patientcount1.size() == 0 && patientcount2.size() == 0)
            data += '[\'No Data\',0]';
        else
            data += '[\'Pre-Treatment Completed\','+patientcount1.size()+'],[\'Mamma Print Filled\','+patientcount2.size()+']';
       
       }
    
    
}