src/objects/CRFMaster__c.object
<CustomObject>
    <fields>
        <fullName>CRFType__c</fullName>
        <label>CRFType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CRFMaster</label>
    <nameField>
        <label>CRF Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CRFMasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dummy_Object__c.object
<CustomObject>
    <description>API name of this object is used in the View Failed Registration visualforce page to show From Date and To Date. No records is stored in this object.</description>
    <fields>
        <fullName>From_Date__c</fullName>
        <label>From Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <label>To Date</label>
        <type>DateTime</type>
    </fields>
    <label>Dummy Object</label>
    <nameField>
        <label>Dummy Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dummy Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Failed_Registration__c.object
<CustomObject>
    <description>This is object to store all failed registration transactions. These records will be used by retry scheduled batch job to retry registration.</description>
    <fields>
        <fullName>CRF_Name__c</fullName>
        <label>CRF Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <label>Error Code</label>
        <picklist>
            <picklistValues>
                <fullName>1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1001</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1026</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1027</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1031</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1032</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1033</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1034</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Status__c</fullName>
        <label>Last Status</label>
        <picklist>
            <picklistValues>
                <fullName>Failure</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Failed Registrations</relationshipLabel>
        <relationshipName>Failed_Registrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Retry__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Retry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Failed Registrations</relationshipLabel>
        <relationshipName>Failed_Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Name__c</fullName>
        <label>System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Failed Registrations</relationshipLabel>
        <relationshipName>Failed_Registrations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Failed Registration</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Failed Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Failed Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/InstitutionUser__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Institution Users</relationshipLabel>
        <relationshipName>InstitutionUsers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>This formula shows User&apos;s Last Name.</description>
        <formula>User__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>InstitutionUsers</relationshipLabel>
        <relationshipName>InstitutionUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>InstitutionUsers</relationshipLabel>
        <relationshipName>InstitutionUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>InstitutionUsers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InstitutionUser</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InstitutionUsers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewFailedRegistrationController.cls
public with sharing class ViewFailedRegistrationController {

   
    public String systemName { get; set; }

    public String CRFName { get; set; }

    
    public List<SelectOption> getStatusList() {
        List<SelectOption> options = new List<SelectOption>();
        
        Schema.DescribeFieldResult fieldResult = Failed_Registration__c.Last_Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('All', 'All'));    
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        return options;
    }


    public List<SelectOption> getErrorCodes() {
        List<SelectOption> options = new List<SelectOption>();
        
        Schema.DescribeFieldResult fieldResult = Failed_Registration__c.Error_Code__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('All', 'All'));    
        for( Schema.PicklistEntry f : ple)
        {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
        return options;
    }
    
    public List<SelectOption> getCRFNames() {
        List<SelectOption> options = new List<SelectOption>();
        
        //Schema.DescribeFieldResult fieldResult = Failed_Registration__c.Error_Code__c.getDescribe();
        //List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption('All', 'All'));    
        //for( Schema.PicklistEntry f : ple)
        //{
        //    options.add(new SelectOption(f.getLabel(), f.getValue()));
        //} 
        List<CRFMaster__c> crfList = [Select CRFType__c From CRFMaster__c order by CRFType__c ];
        for( CRFMaster__c cm : crfList){
            options.add(new SelectOption(cm.CRFType__c, cm.CRFType__c));
        }
              
        return options;
    }
    public List<SelectOption> getSystemNames() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('All', 'All'));
        options.add(new SelectOption('caAERS', 'caAERS'));
        options.add(new SelectOption('caTissue', 'caTissue'));
        return options;
    }

    public PageReference doFilter() {
        doSort();
        return null;
    }


    public String lastStatus { get; set; }

    public String errorCode { get; set; }

    //public String toDate { get; set; }

    //public String fromDate { get; set; }

    Public Integer pageSize{get; set;}
    
    Public Dummy_Object__c filter {get; set;}
    
    private String getFilterString(){
        String fltrStr = '';
        if(filter.From_Date__c!=null){
                //try{
                        //Date mydate = Date.parse(fromDate);
                        //Datetime dt = DateTime.parse('10/14/2011 11:46 AM');
                        //String tmpDate = fromDate;
                        //if(tmpDate.length()<=10){
                        //    tmpDate +=' 1:00 AM';
                        //}
                        //Datetime dt = DateTime.parse(tmpDate);
                        Datetime dt = filter.From_Date__c;
                        String strDt = dt.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
                        fltrStr +=' AND CreatedDate>='+strDt;
                //}catch(Exception e){
                //        System.debug('Amit Exception1============================'+e);
                //}
        }
        if(filter.To_Date__c!=null){
                //try{
                        //Date mydate = Date.parse(toDate);
                        //String tmpDate = toDate;
                        //if(tmpDate.length()<=10){
                        //    tmpDate +=' 11:59 PM';
                        //}
                        //Datetime dt = DateTime.parse(tmpDate );
                        Datetime dt = filter.To_Date__c;
                        String strDt = dt.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
                        fltrStr +=' AND CreatedDate<='+strDt;
                //}catch(Exception e){
                //        System.debug('Amit Exception2============================'+e);
                //}
        }
        /*
        if(fromDate!=null&&!fromDate.trim().equals('')){
                try{
                        //Date mydate = Date.parse(fromDate);
                        //Datetime dt = DateTime.parse('10/14/2011 11:46 AM');
                        String tmpDate = fromDate;
                        if(tmpDate.length()<=10){
                            tmpDate +=' 1:00 AM';
                        }
                        Datetime dt = DateTime.parse(tmpDate);
                        String strDt = dt.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
                        fltrStr +=' AND CreatedDate>='+strDt;
                }catch(Exception e){
                        System.debug('Amit Exception1============================'+e);
                }
        }
        if(toDate!=null&&!toDate.trim().equals('')){
                try{
                        //Date mydate = Date.parse(toDate);
                        String tmpDate = toDate;
                        if(tmpDate.length()<=10){
                            tmpDate +=' 11:59 PM';
                        }
                        Datetime dt = DateTime.parse(tmpDate );
                        String strDt = dt.format('yyyy-MM-dd\'T\'hh:mm:ss\'Z\'');
                        fltrStr +=' AND CreatedDate<='+strDt;
                }catch(Exception e){
                        System.debug('Amit Exception2============================'+e);
                }
        }*/
        if(errorCode!=null &&!errorCode.equals('All')){
                fltrStr +=' AND Error_Code__c=\''+errorCode+'\'';
        }
        if(lastStatus!=null &&!lastStatus.equals('All')){
                fltrStr +=' AND Last_Status__c=\''+lastStatus+'\'';
        }
        
        if(CRFName!=null &&!CRFName.equals('All')){
                fltrStr +=' AND CRF_Name__c=\''+CRFName+'\'';
        }
        
        if(systemName!=null &&!systemName.equals('All')){
                fltrStr +=' AND System_Name__c=\''+systemName+'\'';
        }
        
        //Data should be shown based on the site to which the user belongs
        String siteStr = '';
        List<InstitutionUser__c > instUserList = [Select i.User__c, i.Site__c From InstitutionUser__c i where i.User__c= :UserInfo.getUserId()];
        Integer j=0;
        for(Integer i=0;i<instUserList.size();i++ ){
            InstitutionUser__c instUser = instUserList[i];
            if(instUser.Site__c !=null){
                if(j==0){
                    siteStr= '\''+instUser.Site__c +'\'';
                }else{
                    siteStr+= ',\''+instUser.Site__c +'\'';
                }
                j++;
            }
           
        }
        if(!Test.isRunningTest()){
            fltrStr +=' AND Site__c in ('+siteStr+')';
        }
        
        if(fltrStr.length()>0){
                fltrStr = fltrStr.substring(4);
        }
        
        return fltrStr;
    }
     
    public List<FailedRegistrationWrapper> recLst {get{
            
            List<Failed_Registration__c > records = con.getRecords();
    
            recLst = new List<FailedRegistrationWrapper>();
            for(Failed_Registration__c  fr : records ){
    
                recLst.add(new FailedRegistrationWrapper(fr) );
    
            }
            return recLst;
    }
     set;}
    
    
    public String downloadQuery='';
    private String sortDirection = 'DESC';
    private String sortExp = 'CreatedDate';

    public String sortExpression{
        get {
            return sortExp;
        } 
        set{
            if (value == sortExp){
                sortDirection = (sortDirection == 'ASC')? 'DESC' : 'ASC';
            }
            else{
                sortDirection = 'DESC';
            }
            sortExp = value;
        }
    }
    
    
    public String getSortDirection(){
        //if not column is selected 
        if (sortExpression == null || sortExpression == ''){
            return 'ASC';
        }
        else{
            return sortDirection;
        }
    }

    public void setSortDirection(String value){  
        sortDirection = value;
    }



    public ViewFailedRegistrationController (){
        //Id=ApexPages.currentPage().getParameters().get('id');
                pageSize = 10; //TODO
                filter = new Dummy_Object__c();
    }


    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
                String query = 'SELECT ';
                for(Schema.FieldSetMember f : this.getFields()) {
                    query += f.getFieldPath()+',';
                }
                Integer length = query.length();
                                query=query.substring(0,length-1);
                query += ' FROM Failed_Registration__c ';
                //downloadQuery = query;
                String filter = getFilterString();
                if(filter.length()>0){
                        query +=' Where '+filter;
                }
                query = query + ' order by '+ sortExpression  + ' ' + sortDirection;
                System.debug('Amit========'+query);
                con = new ApexPages.StandardSetController(Database.getQueryLocator(query));

                // sets the number of records in each page set
                con.setPageSize(pageSize);
            }
            return con;
            
        }
        set;
    }
    /*
    public List<FailedRegistrationWrapper> getFailedRegistration() {


        List<Failed_Registration__c  > records = con.getRecords();

        recLst.clear();
        for(Failed_Registration__c  fr : records ){

            recLst.add(new FailedRegistrationWrapper(fr) );

        }

        return recLst;
    }*/

    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.Failed_Registration__c.FieldSets.View_Failed_Registration_Field_Set.getFields();
      
    }



    public class FailedRegistrationWrapper
    {
        public Failed_Registration__c failedRegistration{get; set;}
        public Boolean selected {get; set;}
        public Boolean disabled{get; set;}
        public FailedRegistrationWrapper(Failed_Registration__c fr)
        {
            failedRegistration = fr;
            selected = false;
            disabled = false;
        }
    }

    // indicates whether there are more records after the current page set.
    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    // indicates whether there are more records before the current page set.
    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

    // returns the page number of the current page set
    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }

    // returns the first page of records
    public void first() {
        con.first();
        
        List<Failed_Registration__c  > records = con.getRecords();

        recLst.clear();
        for(Failed_Registration__c li : records ){

            recLst.add(new FailedRegistrationWrapper(li) );

        }
    }

    // returns the last page of records
    public void last() {
        con.last();
        List<Failed_Registration__c > records = con.getRecords();

        recLst.clear();
        for(Failed_Registration__c li : records ){

            recLst.add(new FailedRegistrationWrapper(li) );

        }
    }

    // returns the previous page of records
    public void previous() {
        con.previous();
        List<Failed_Registration__c > records = con.getRecords();

        recLst.clear();
        for(Failed_Registration__c li : records ){

            recLst.add(new FailedRegistrationWrapper(li) );

        }
    }

    // returns the next page of records
    public void next() {
        con.next();
        List<Failed_Registration__c > records = con.getRecords();

        recLst.clear();
        for(Failed_Registration__c li : records ){

            recLst.add(new FailedRegistrationWrapper(li) );

        }
    }
    /*
    public Integer getRecordSize(){

        return con.getResultSize();
    }
    */
  

   public void doSort(){
        /*
            List<Failed_Registration__c> recs = con.getRecords();
            List<Failed_Registration__c> dlObjects = recs.deepClone(true,true,true);
            
            sortList(dlObjects,sortExp,sortDirection);
            recLst.clear();
        for(Failed_Registration__c li : dlObjects ){

            recLst.add(new FailedRegistrationWrapper(li) );

        }
        */
        String query = 'SELECT ';
        
        for(Schema.FieldSetMember f : this.getFields()) {
                query += f.getFieldPath()+',';
        }
        Integer length = query.length();
                query=query.substring(0,length-1);
        query += ' FROM Failed_Registration__c ';
        //downloadQuery = query;
        String filter = getFilterString();
        if(filter.length()>0){
                query +=' Where '+filter;
        }
        query += ' order by '+ sortExpression  + ' ' + sortDirection;
        System.debug('Amit query==================='+query );
        con = new ApexPages.StandardSetController(Database.getQueryLocator(query));
        // sets the number of records in each page set
        con.setPageSize(pageSize);
   
        List<Failed_Registration__c> recs = con.getRecords();
        recLst.clear();
        for(Failed_Registration__c li : recs ){

            recLst.add(new FailedRegistrationWrapper(li) );

        }
    
   }
   /*
   public static void sortList(List<Sobject> items, String sortField, String order){


        List<Sobject> resultList = new List<Sobject>();

        //Create a map that can be used for sorting 
        Map<object, List<Sobject>> objectMap = new Map<object, List<Sobject>>();

        for(Sobject ob : items){
            if(objectMap.get(ob.get(sortField)) == null){  // For non Sobject use obj.ProperyName
                objectMap.put(ob.get(sortField), new List<Sobject>()); 
            }
            objectMap.get(ob.get(sortField)).add(ob);
        }       
        //Sort the keys
        List<object> keys = new List<object>(objectMap.keySet());
        keys.sort();

        for(object key : keys){ 
            resultList.addAll(objectMap.get(key)); 
        }

        //Apply the sorted values to the source list
        items.clear();
        if(order.toLowerCase() == 'asc'){
            for(Sobject ob : resultList){
                items.add(ob); 
            }
        }else if(order.toLowerCase() == 'desc'){
            for(integer i = resultList.size()-1; i >= 0; i--){
                items.add(resultList[i]);  
            }
        }
    }*/
    
    @isTest public static void myTest1(){
        Test.startTest();
        Trial__c t = new Trial__c(Name='Test Trial',Start_Date__c=System.today());
        insert t;
        Account a = new Account(Name='Test Account');
        insert a;
        Patient_Custom__c p = new Patient_Custom__c(Name='Test Patient',Institution__c=a.id,Last_Name__c='Last Name',Birthdate__c=System.today(),Race__c='Asian',Gender__c='Male',Ethnicity__c='Hispanic or Latino');
        insert p;
        
        //Select i.User__c, i.Site__c From InstitutionUser__c i where i.User__c= :UserInfo.getUserId()
        Site__c site1 = new Site__c();
        site1.Name = 'test site1';
        site1.Type__c = 'test type';
        site1.Institute__c = a.Id;
        insert site1;
        
        InstitutionUser__c iu = new InstitutionUser__c();
        iu.User__c = UserInfo.getUserId();
        iu.Site__c = site1.Id;
        iu.Institution__c = a.Id;
        insert iu;
        
        
        Failed_Registration__c fr = new Failed_Registration__c(Trial__c=t.id,Patient__c=p.id,Retry__c=true,Last_Status__c='Failure',Site__c=site1.id);
        insert fr;
        
        ViewFailedRegistrationController c = new ViewFailedRegistrationController();
        
        c.getErrorCodes();
        c.getStatusList();
        c.getCRFNames();
        c.getSystemNames();
        //c.recLst;
        c.getFields();
        c.filter = new Dummy_Object__c();
        Dummy_Object__c fil = c.filter;
        c.filter.From_Date__c=DateTime.parse('01/01/2011 11:46 AM');       
        c.filter.To_Date__c=DateTime.parse('01/01/2015 11:46 AM');
       
        c.sortExpression='CreatedDate';
        c.setSortDirection('DESC');
        c.getSortDirection();
        c.errorCode='All';
        String ec = c.errorCode;
        c.lastStatus='All';
        //ApexPages.StandardSetController con1 = c.con;
        String ls = c.lastStatus;
        c.pageSize = 1;
        ApexPages.StandardSetController con = c.con;
        Integer i = c.pageSize;
        Integer i2 = c.pageNumber;
        c.pageNumber = 2; 
        
        List<FailedRegistrationWrapper> recLst = c.recLst;
        c.doFilter();
        Boolean b1 = c.hasNext;
        c.next();
        Boolean b2 = c.hasPrevious;
        c.previous();
        c.first();
        c.last();
        Test.stopTest(); 
    }
    
    @isTest public static void myTest2(){
        ViewFailedRegistrationController c = new ViewFailedRegistrationController();
        c.filter = new Dummy_Object__c();
        Dummy_Object__c fil = c.filter;
        c.filter.From_Date__c=DateTime.parse('01/01/2011 11:46 AM');       
        c.filter.To_Date__c=DateTime.parse('01/01/2015 11:46 AM');
        c.errorCode='ERROR_1';
        c.lastStatus='Success';
        c.sortExpression='ASC';
        String str=c.getFilterString();
    }
    @isTest public static void myTest3(){
        ViewFailedRegistrationController c = new ViewFailedRegistrationController();
        ///c.fromDate='31/33/2099';
        //c.toDate='31/33/2099';
        //c.errorCode='ERROR_1';
        //c.lastStatus='Success';
        c.sortExpression=null;
        String str=c.getSortDirection();
    }
}