src/objects/Dashboard__c.object
<CustomObject>
    <fields>
        <fullName>Profile_Filter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Profile Filter</label>
        <type>Checkbox</type>
    </fields>
    <label>Dashboard</label>
    <nameField>
        <label>Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestProfilesFilter.cls
@isTest
public class TestProfilesFilter{
    static testMethod void test1(){
        Dashboard__c dc = new Dashboard__c(Profile_Filter__c  = false);      
        dc.name='TestDashboard';
        insert dc;
        
        ApexPages.StandardController sc = new ApexPages.standardController(dc);
        ProfilesFilter pf = new ProfilesFilter(sc);
                   
    }
     static testMethod void test2(){
        Dashboard__c dc = new Dashboard__c(Profile_Filter__c  = true);      
        dc.name='TestDashboard';
        
        insert dc;
        
        ApexPages.StandardController sc = new ApexPages.standardController(dc);
        ProfilesFilter pf = new ProfilesFilter(sc);
        pf.validateProfileFilters('System Administrator', dc.Id);
        
        pf = new ProfilesFilter(sc);
        pf.validateProfileFilters('Trial Administrator', dc.Id);
        
        pf = new ProfilesFilter(sc);
        pf.validateProfileFilters('Institute Level Admin', dc.Id);
        
        pf = new ProfilesFilter(sc);
        pf.validateProfileFilters('Site User', dc.Id);
                   
    }
}