src/objects/Dashboard__c.object
<CustomObject>
    <label>Dashboard</label>
    <nameField>
        <label>Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dashboard_View__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dashboard__c</fullName>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Views</relationshipLabel>
        <relationshipName>Dashboard_Views</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <referenceTo>View__c</referenceTo>
        <relationshipLabel>Dashboard Views</relationshipLabel>
        <relationshipName>Dashboard_Views</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dashboard View</label>
    <nameField>
        <displayFormat>DV-{00000}</displayFormat>
        <label>Dashboard View Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dashboard Views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Profile_Right__c.object
<CustomObject>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Widget__c</fullName>
        <label>Widget</label>
        <referenceTo>Widget__c</referenceTo>
        <relationshipLabel>Profile Rights</relationshipLabel>
        <relationshipName>Profile_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Profile Right</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Rights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <fields>
        <fullName>Institute__c</fullName>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sites</relationshipLabel>
        <relationshipName>Sites</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Settings__c.object
<CustomObject>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>View</label>
        <referenceTo>View__c</referenceTo>
        <relationshipLabel>User Settings</relationshipLabel>
        <relationshipName>User_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Widget__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Widget</label>
        <referenceTo>Widget__c</referenceTo>
        <relationshipLabel>User Settings</relationshipLabel>
        <relationshipName>User_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Settings</label>
    <nameField>
        <displayFormat>US-{00000}</displayFormat>
        <label>User Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/View__c.object
<CustomObject>
    <label>View</label>
    <nameField>
        <label>View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/View_Widget__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <label>View</label>
        <referenceTo>View__c</referenceTo>
        <relationshipName>ViewWidgets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Widget__c</fullName>
        <label>Widget</label>
        <referenceTo>Widget__c</referenceTo>
        <relationshipName>ViewWidgets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>View Widget</label>
    <nameField>
        <displayFormat>VW-{00000}</displayFormat>
        <label>View Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>View Widgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Widget__c.object
<CustomObject>
    <fields>
        <fullName>Chart_Fields__c</fullName>
        <label>Chart Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data_Limit__c</fullName>
        <label>Data Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Drill_Down_Field__c</fullName>
        <label>Drill Down Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Query_Type__c</fullName>
        <label>Query Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aggregate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Site_Filter__c</fullName>
        <label>Site Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <picklist>
            <picklistValues>
                <fullName>A Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Half</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Three Quarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Column</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDashboardController.cls
@isTest
public class TestDashboardController{
   public static testMethod void TestDashboardController(){
   
    String strRecordTypeId = [Select Id From RecordType Where  Name = 'Site'].Id;
    List<Profile>  profiles = [SELECT Id, Name FROM Profile ];
    List<User> user = [SELECT Id, Name FROM User];
    
    Account acc = new Account(Name = 'Test acc');
    insert acc;
    
    Site__c site = new Site__c(Name = 'Test Site', recordtypeId = strRecordTypeId, Institute__c = acc.Id);
    insert site;
   
    Dashboard__c db = new  Dashboard__c(Name = 'Test dashboard');
    insert db;
    
    List<Widget__c> widget=new List<Widget__c>();
    widget.add(new Widget__c(name='testing',Site_Filter__c = 'Site__c' , query__c = 'select Site__r.Name SiteName, count(Subject_Id__c) PatientCount from TrialPatient__c group by Site__r.Name',query_type__c ='Normal',Type__c='Bar',Size__c='Small',Data_Limit__c = 5,Chart_Fields__c='name,NumberOfEmployees',Drill_Down_Field__c='test'));
    widget.add(new Widget__c(name='testing',Site_Filter__c = 'Site__c',query__c = 'select Site__r.Name, Subject_Id__c from TrialPatient__c where Site__c != null and Subject_Id__c != null',query_type__c ='Normal',Type__c='Pie',Size__c='Small',Data_Limit__c = 5,Chart_Fields__c='name,NumberOfEmployees',Drill_Down_Field__c='test'));
    widget.add(new Widget__c(name='testing',query__c = 'select Id, name , NumberOfEmployees from Account where  NumberOfEmployees != null ',query_type__c ='Normal',Type__c='Column',Size__c='Small',Data_Limit__c = 5,Chart_Fields__c='name,NumberOfEmployees',Drill_Down_Field__c='test'));
    widget.add(new Widget__c(name='testing',Site_Filter__c = 'Site__c', Data_Source__c = 'EligiblebutPendingRegistration',query_type__c ='Normal',Type__c='Grid',Size__c='Small',Data_Limit__c = 5,Chart_Fields__c='name,NumberOfEmployees',Drill_Down_Field__c='test'));
    widget.add(new Widget__c(name='testing',query__c = 'select Id, name , Count(NumberOfEmployees) from Account where  NumberOfEmployees != null group by Id,name',query_type__c ='Normal',Type__c='Grid',Size__c='Small',Data_Limit__c = 5,Chart_Fields__c='name,NumberOfEmployees',Drill_Down_Field__c='test'));
    insert widget;
    
    
    List<View__c> view=new List<View__c>();
    view.add(new View__c(name='test view'));
    view.add(new View__c(name='test view1'));
    view.add(new View__c(name='test view2'));
    insert view;
    
    
    List<Dashboard_View__c> dbView = new List<Dashboard_View__c>();
    dbView.add(new Dashboard_View__c(View__c = view[0].id, Dashboard__c = db.Id, Active__c = true, Sequence__c = 1));
    dbView.add(new Dashboard_View__c(View__c = view[1].id, Dashboard__c = db.Id, Active__c = true, Sequence__c = 2));
    dbView.add(new Dashboard_View__c(View__c = view[2].id, Dashboard__c = db.Id, Active__c = true, Sequence__c = 3));
    insert dbView;
    
    List<View_Widget__c> vw = new List<View_Widget__c>();
    vw.add(new View_Widget__c(Widget__c = widget[0].id, View__c=view[1].id, Sequence__c=123));
    insert vw;
    
    List<Profile_Right__c> profileRight = new List<Profile_Right__c>();
    profileRight.add(new Profile_Right__c(Profile_Id__c = ''+profiles[0].Id, Widget__c = widget[0].id));
    profileRight.add(new Profile_Right__c(Profile_Id__c = ''+profiles[1].Id, Widget__c = widget[1].id));
    profileRight.add(new Profile_Right__c(Profile_Id__c = ''+profiles[1].Id, Widget__c = widget[2].id));
    profileRight.add(new Profile_Right__c(Profile_Id__c = ''+profiles[1].Id, Widget__c = widget[3].id));
    insert profileRight;
    
     List<View_Widget__c> viewWidget= new List<View_Widget__c>();
     viewWidget.add(new View_Widget__c(Widget__c =widget[0].id, View__c=view[0].id, Sequence__c=1, Active__c=true));
     viewWidget.add(new View_Widget__c(Widget__c =widget[1].id, View__c=view[1].id, Sequence__c=1, Active__c=true));
     viewWidget.add(new View_Widget__c(Widget__c =widget[2].id, View__c=view[2].id, Sequence__c=1, Active__c=true));
     viewWidget.add(new View_Widget__c(Widget__c =widget[3].id, View__c=view[2].id, Sequence__c=1, Active__c=true));
     viewWidget.add(new View_Widget__c(Widget__c =widget[4].id, View__c=view[0].id, Sequence__c=1, Active__c=true));
     insert viewWidget;
     
     List<User_Settings__c> usersetting = new List<User_Settings__c>();
     usersetting .add(new User_Settings__c(User__c = user[0].Id, View__c = view[1].Id, Widget__c = widget[1].Id));
     usersetting .add(new User_Settings__c(User__c = user[0].Id, View__c = view[2].Id, Widget__c = widget[2].Id));
     usersetting .add(new User_Settings__c(User__c = user[0].Id, View__c = view[2].Id, Widget__c = widget[3].Id));
     usersetting .add(new User_Settings__c(User__c = user[0].Id, View__c = view[0].Id, Widget__c = widget[0].Id));
     insert usersetting;
     
     
     
    ApexPages.StandardController controller=new ApexPages.StandardController(db);
    DashboardController2 dc = new  DashboardController2(controller);
    //System.assert(false,dc.viewIds);
    dc.getData(widget[0]);
    dc.getChildWidget();
    dc.fortabelview = 'Yes';
    // dc.saveInSequence();
    dc.dBoardWrapper = new List<DashboardController2.DashBoardViewWrapper>();
    Dashboard_View__c dv  = new Dashboard_View__c();
    dv.View__c=view[0].id;
    dv.Dashboard__c=db.id;
    dv.Active__c=true;
    insert dv;
    DashboardController2.DashBoardViewWrapper  objdashBoardViewWrapper= new DashboardController2.DashBoardViewWrapper(null,null,1);
    DashboardController2.ViewWidgetWrapper  objViewWidgetWrapper= new DashboardController2.ViewWidgetWrapper(vw[0],'selva');
    List<DashboardController2.ViewWidgetWrapper> lstViewWidget = new List<DashboardController2.ViewWidgetWrapper>();
    lstViewWidget.add(objViewWidgetWrapper);
    dc.dBoardWrapper.add(new DashboardController2.DashBoardViewWrapper(dv,lstViewWidget,dc.dBoardWrapper.size()));
    dc.widgetId=vw[0].id;
    dc.loadData();
    //dc.loadWidgetsByUserSettings(usersetting,dc.viewIds);
    dc.widgetId = widget[3].Id;
     dc.loadFilter();
     dc.loadData();
     dc.widgetId = widget[0].Id;
     dc.siteId = '\''+site.Id+'\'';
     dc.value = site.Name;
    dc.getFilterWidget();
    dc.loadFilter();
    dc.widgetId = widget[0].Id;
    dc.loadData();
     dc.widgetId = widget[1].Id;
    dc.getFilterWidget();
    dc.loadData();
    
    DashboardController2.getUserSetting(''+viewWidget[0].id+','+viewWidget[1].id+','+viewWidget[2].id+','+viewWidget[3].id+','+viewWidget[4].id,''+viewWidget[0].id,''+viewWidget[0].id+'##1'+
    ','+viewWidget[2].id+'##2'+','+viewWidget[3].id+'##3'+','+viewWidget[4].id+'##4'+','+viewWidget[0].id+'##5'+','+viewWidget[2].id+'##6'+','+viewWidget[3].id+'##7'+','+viewWidget[4].id+'##8'+
    ','+viewWidget[3].id+'##9'+','+viewWidget[4].id+'##A'+','+viewWidget[0].id+'##B'+','+viewWidget[0].id+'##C');
        
   }
 /*     public static testMethod void TestDashboardController1(){
    Dashboard__c db = new  Dashboard__c();
    db.Name='test';
    insert db;
    Widget__c widget=new Widget__c();
    widget.name='testing';
    widget.query__c = 'select Id, name , NumberOfEmployees from Account where  NumberOfEmployees != null ';
    widget.query_type__c ='Normal';
    widget.Type__c='Bar';
    widget.Size__c='Small';
    widget.Data_Limit__c = 5;
    widget.Chart_Fields__c='name,NumberOfEmployees';
    widget.Drill_Down_Field__c='test';
    insert widget;
    View__c v=new View__c();
    v.name='test';
    insert v;
    View_Widget__c vw=new View_Widget__c();
    vw.Widget__c =widget.id;
    vw.View__c=v.id;
    vw.Sequence__c=123;
    vw.Active__c=true;
    insert vw;
    List<View_Widget__c> listviewWidget= new List<View_Widget__c>();
    listviewWidget.add(vw);
    ApexPages.StandardController controller=new ApexPages.StandardController(db);
    DashboardController2 dc=new  DashboardController2(controller);
    User_Settings__c  usersettingobj= new User_Settings__c();
    usersettingobj.Widget__c=widget.id;
    usersettingobj.View__c=v.id;
    insert usersettingobj;
    List<User_Settings__c> usetlistsetting=    new List<User_Settings__c>();
    usetlistsetting.add(usersettingobj);
   // dc.loadWidgetsByUserSettings(usetlistsetting);
    dc.setInstitute();
    dc.setSite();
    dc.setTrial();
    dc.loadchartProfileFilter();
    DashboardController2.DashBoardViewWrapper  objdashBoardViewWrapper= new DashboardController2.DashBoardViewWrapper(null,null,1);
    DashboardController2.ViewWidgetWrapper  objViewWidgetWrapper= new DashboardController2.ViewWidgetWrapper(vw,'selva');
    dc.getFilterWidget();
    
    dc.dBoardWrapper = new List<DashboardController2.DashBoardViewWrapper>();
    Dashboard_View__c dv  = new Dashboard_View__c();
    dv.View__c=v.id;
    dv.Dashboard__c=db.id;
    dv.Active__c=true;
    insert dv;
    DashboardController2.DashBoardViewWrapper  objdashBoardViewWrapper1= new DashboardController2.DashBoardViewWrapper(null,null,1);
    DashboardController2.ViewWidgetWrapper  objViewWidgetWrapper1= new DashboardController2.ViewWidgetWrapper(vw,'selva');
    List<DashboardController2.ViewWidgetWrapper> lstViewWidget = new List<DashboardController2.ViewWidgetWrapper>();
    lstViewWidget.add(objViewWidgetWrapper);
    dc.dBoardWrapper.add(new DashboardController2.DashBoardViewWrapper(dv,lstViewWidget,dc.dBoardWrapper.size()));
    dc.widgetId=vw.id;
    
    dc.loadFilter();

        
   } */
   
   
   
   
   
}