src/objects/Dashboard__c.object
<CustomObject>
    <label>Dashboard</label>
    <nameField>
        <label>Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dashboard_Profile_Right__c.object
<CustomObject>
    <fields>
        <fullName>Dashboard__c</fullName>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Profile Rights</relationshipLabel>
        <relationshipName>Dashboard_Profile_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Profile_Id__c</fullName>
        <label>Profile Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Dashboard Profile Right</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboard Profile Rights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ViewDashBoard.cls
public with sharing class ViewDashBoard{

    
    public String dashboardId{get;set;}
    public String profileId{get;set;}
    public List<Profile> profile;
    public List<dashboard__c> dashboards { get; set; }
    
    public ViewDashBoard(){
        try{
        dashboards  = new  List<dashboard__c>();
        profile = new List<Profile>();
        profile = [select id from Profile where id = :userinfo.getProfileId()];
        profileId = profile[0].Id;
        List<String> dashboardIds = new List<String>();
        for(Dashboard_Profile_Right__c dbright : [select Dashboard__c From Dashboard_Profile_Right__c where Profile_Id__c = :profileId ]) 
               dashboardIds.add(dbright.Dashboard__c);
        if(dashboardIds.size()>0)
            dashboards = [select id,name from dashboard__c where id in :dashboardIds];
        }
        catch(Exception e){
        
            System.assert(false,e.getstacktracestring());
        }    
    }
    
}