src/objects/Dashboard__c.object
<CustomObject>
    <label>Dashboard</label>
    <nameField>
        <label>Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dashboard_Profile_Right__c.object
<CustomObject>
    <fields>
        <fullName>Dashboard__c</fullName>
        <label>Dashboard</label>
        <referenceTo>Dashboard__c</referenceTo>
        <relationshipLabel>Dashboard Profile Rights</relationshipLabel>
        <relationshipName>Dashboard_Profile_Rights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Dashboard Profile Right</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dashboard Profile Rights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDBProfileRightController.cls
@isTest
public class TestDBProfileRightController{
   public static testMethod void TestDBProfileRightController(){
     
        List<Profile> profiles = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
       
        Dashboard__c widget=new  Dashboard__c ();


  
        Dashboard_Profile_Right__c pr=new Dashboard_Profile_Right__c();
        
        ApexPages.StandardController controller= new ApexPages.StandardController(pr);
        DBProfileRightController prc=new  DBProfileRightController(controller);
        pr.Name='test';
        pr.Dashboard__c =profiles[0].id;
       
        List<String> leftselected = new List<String>();
        leftselected.add(profiles[0].id);
        prc.leftselected=leftselected;
        
        List<String> rightselected = new List<String>();
        rightselected.add(profiles[0].id);
        prc.rightselected=rightselected;    
       
       
        prc.selectclick();
        prc.unselectclick();
        prc.getunSelectedValues();
        prc.getSelectedValues();
        prc.Save(); 
    
    }

}