src/objects/Followup_Form__c.object
<CustomObject>
    <fields>
        <fullName>Dose_per_FX_cGy__c</fullName>
        <inlineHelpText>Enter Dose per FX( cGY )</inlineHelpText>
        <label>Dose per FX (cGy)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Enters the end dates from the reporting period.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Menopausal_status__c</fullName>
        <label>Menopausal status</label>
        <picklist>
            <picklistValues>
                <fullName>Premenopausal(&lt;6 months)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perimenopausal(6-12months)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postmenopausal(&gt;12 months)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>age &lt; 50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abv Catg not Aplicable &amp; age &gt; 50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infraclavicular Nodes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chest Wall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local-regional skin and Subcutaneous tissue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <inlineHelpText>Enter the start date from the reporting period.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survival_Status__c</fullName>
        <inlineHelpText>Select the Survival Status.</inlineHelpText>
        <label>Survival Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_dose_cGy_AP__c</fullName>
        <label>Total dose (cGy)  AP</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Followup Forms</relationshipLabel>
        <relationshipName>Followup_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>patient_diagnosed_distant_progression__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select Yes or NO</inlineHelpText>
        <label>patient diagnosed distant progression</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>patient_diagnosed_local_progression__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select Yes or NO</inlineHelpText>
        <label>patient diagnosed  local progression</label>
        <type>Checkbox</type>
    </fields>
    <label>Followup Form</label>
    <nameField>
        <displayFormat>FF-{00000}</displayFormat>
        <label>Followup Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Followup Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Irradiated_Site__c.object
<CustomObject>
    <fields>
        <fullName>Dose_per_FX_cGy__c</fullName>
        <inlineHelpText>Enter Dose per FX( cGY )</inlineHelpText>
        <label>Dose per FX (cGy)</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Followup_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Followup Form</label>
        <referenceTo>Followup_Form__c</referenceTo>
        <relationshipLabel>Irradiated Sites</relationshipLabel>
        <relationshipName>Irradiated_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_dose_cGy_AP__c</fullName>
        <label>Total dose (cGy)  AP</label>
        <precision>8</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Irradiated Site</label>
    <nameField>
        <label>Irradiated Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Irradiated Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is need for SignAndSubmit button which is using this id for approval.</description>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Therapy_Received__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Followup_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Followup Form</label>
        <referenceTo>Followup_Form__c</referenceTo>
        <relationshipLabel>Therapy Receiveds</relationshipLabel>
        <relationshipName>Therapy_Receiveds</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Therapy Received</label>
    <nameField>
        <label>Therapy Received Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Therapy Receiveds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient_Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/TestFollowupFormController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *  
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestFollowupFormController {

    	@isTest
    	static void myUnitTest1() 
    	{ 
        List<User> lstSiteUser = [Select u.IsActive, u.Id From User u where IsActive = true];
        System.runAs ( lstSiteUser[0] ) { 
            
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
            
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1980, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; 
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
            
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        insert tp;
        
        //============================== "Followup_Form__c" = NULL to satisfy "saveMainCRF()"==============
            
        Followup_Form__c followObject1 = new Followup_Form__c(); 
        followObject1.TrialPatient__c = tp.Id;
        followObject1.Survival_Status__c = 'Dead';
        followObject1.Start_Date__c = date.newInstance(2012, 7, 7);
        followObject1.End_Date__c = date.newInstance(2012, 8, 8);
        followObject1.patient_diagnosed_local_progression__c = true;
        followObject1.patient_diagnosed_distant_progression__c = false;
        followObject1.Menopausal_status__c = 'Menopaus';
        
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        Apexpages.currentPage().getParameters().put('fupformId',null);
            
        ApexPages.StandardController std1 = new ApexPages.StandardController(followObject1);
        FollowupFormController ffObject1 = new FollowupFormController(std1);
            
        ffObject1.saveMainCRF();
            
        ffObject1.next();
            
        ffObject1.previous();
        ffObject1.currentTab = 'completeTab';
        ffObject1.previous();
        ffObject1.currentTab = 'attachmentTab';
        ffObject1.previous();
        ffObject1.cloneCRF(); 
            
        //=============================finished=========================================================
            
        Followup_Form__c followObject = new Followup_Form__c(); 
        followObject.TrialPatient__c = tp.Id;
        followObject.Survival_Status__c = 'Alive';
        followObject.Start_Date__c = date.newInstance(2012, 7, 7);
        followObject.End_Date__c = date.newInstance(2012, 8, 8);
        followObject.patient_diagnosed_local_progression__c = true;
        followObject.patient_diagnosed_distant_progression__c = true;
        followObject.Status__c = 'Approval Pending';
        insert followObject;
        update followObject;
            
        Therapy_Received__c tr = new Therapy_Received__c();
        tr.Followup_Form__c = followObject.Id;
        insert tr;
        
        Irradiated_Site__c ir = new Irradiated_Site__c();
        ir.Followup_Form__c  = followObject.Id;
        ir.Total_dose_cGy_AP__c = 1.0;
        ir.Dose_per_FX_cGy__c = 2.0;
        ir.Total_FX__c = 5.0;
        insert ir; 
         
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        Apexpages.currentPage().getParameters().put('fupformId',followObject.Id);
            
        ApexPages.StandardController std = new ApexPages.StandardController(followObject);
        FollowupFormController ffObject = new FollowupFormController(std);
            
        Apexpages.currentPage().getParameters().put('nextTab','saveAndClose');
        ffObject.next();
        
            
        //==========================method "TherapyReceived()" begins here =============================
        ffObject.addTherapyReceived();
        ffObject.editTherapyReceived();
        ffObject.updateTherapyReceived();
        ffObject.saveTherapyReceived();
        Apexpages.currentPage().getParameters().put('recordId',tr.Id);
        ffObject.cancelTherapyReceived();
        Apexpages.currentPage().getParameters().put('recordId',tr.Id);
        ffObject.removeTherapyReceived();
        //==========================method "TherapyReceived()" ends here ===============================
            
        //==========================method "addIrradiatedSite()" begins here ===========================
            
        ffObject.addIrradiatedSite();
        ffObject.editIrradiatedSite();
        ffObject.updateIrradiatedSite();
        ffObject.saveIrradiatedSite();
        Apexpages.currentPage().getParameters().put('recordId',null);
        ffObject.cancelIrradiatedSite();
        Apexpages.currentPage().getParameters().put('recordId',ir.Id);
        ffObject.cancelIrradiatedSite();
        Apexpages.currentPage().getParameters().put('recordId',ir.Id);
        ffObject.removeIrradiatedSite(); 
            
        //==========================method "addIrradiatedSite()" ends here =============================
            
        //ffObject.attachPdf();
   }
 }
    @isTest static void myUnitTest2() { 
        List<User> lstSiteUser = [Select u.IsActive, u.Id From User u where IsActive = true];
        System.runAs ( lstSiteUser[0] ) { 
            
        Account acc = new Account();
        acc.Name = 'test';
        insert acc;
            
        Trial__c trial = new Trial__c();
        trial.Name = 'test';
        insert trial;
        
        Patient_Custom__c p = new Patient_Custom__c();
        p.Birthdate__c = date.newInstance(1980, 08, 05);
        p.Institution__c = acc.Id;
        p.Last_Name__c = 'test'; 
        p.Gender__c = 'Male';
        p.Race__c = 'White';
        p.Ethnicity__c = 'Not Hispanic or Latino';
        insert p;
            
        TrialPatient__c tp = new TrialPatient__c();
        tp.Patient_Id__c = p.Id;
        insert tp;
        
        Registration__c reg = new Registration__c(); 
        reg.Patient__c = p.Id;
        reg.TrialPatient__c = tp.Id;
        reg.Trial__c = trial.Id;
        reg.Last_Name__c = p.Last_Name__c;
        reg.Gender__c = p.Gender__c;
        reg.Registration_Date__c = system.today();
        reg.Ethnicity__c = p.Ethnicity__c;
        reg.Race__c =  p.Race__c;
        reg.Institution__c = acc.Id;
        reg.IRB_Approval_Date__c = system.today();
        reg.HIPPA_Consent_Date__c = system.today();
        reg.Screening_Informed_Consent_Date__c = system.today();
        reg.Effective_Time__c = system.now();
        reg.ISPY2_Subject_Id__c = ''+123; 
        insert reg;
        
        Followup_Form__c followObject = new Followup_Form__c(); 
        followObject.TrialPatient__c = tp.Id;
        followObject.Survival_Status__c = 'Dead';
        followObject.Start_Date__c = date.newInstance(2012, 7, 7);
        followObject.End_Date__c = date.newInstance(2012, 8, 8);
        followObject.patient_diagnosed_local_progression__c = true;
        followObject.patient_diagnosed_distant_progression__c = false;
        followObject.Menopausal_status__c = 'Menopaus';
        followObject.Status__c = 'Accepted';
        insert followObject;
        update followObject;
            
        Therapy_Received__c tr = new Therapy_Received__c();
        tr.Followup_Form__c = followObject.Id;
        insert tr;
        
        Irradiated_Site__c ir = new Irradiated_Site__c();
        ir.Followup_Form__c  = followObject.Id;
        ir.Total_dose_cGy_AP__c = 1.0;
        ir.Dose_per_FX_cGy__c = 2.0;
        ir.Total_FX__c = 5.0;
        insert ir; 
     
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);  
        Apexpages.currentPage().getParameters().put('fupformId',followObject.Id);
            
        ApexPages.StandardController std = new ApexPages.StandardController(followObject);
        FollowupFormController ffObject = new FollowupFormController(std);
        
        ffObject.currentTab = 'MPStatusTab';    
        ffObject.next();
        
        ffObject.editCRF();
        
        Apexpages.currentPage().getParameters().put('recordId',null);
        ffObject.cancelTherapyReceived();
            
        ffObject.recurrenceProgressChoice = new List<String>{'Test'};
        ffObject.progressionLocalChoice = new List<String>{'Test1'};
        ffObject.progressionDistantChoice = new List<String>{'Test2'};
        ffObject.menopausalStatusChoice = new List<String>{'Test3'};
        
        ffObject.resendCode();
        ffObject.signAndSubmit();
        Apexpages.currentPage().getParameters().put('trialPat',tp.Id);
        ffObject.cancelCRF();
    } 
  }
}