src/objects/Invasive_Tumor_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Mitotic_Count__c</fullName>
        <label>Mitotic Count</label>
        <picklist>
            <picklistValues>
                <fullName>1pt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2pt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3pt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indeterminate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nuclear_Grade__c</fullName>
        <label>Nuclear Grade</label>
        <picklist>
            <picklistValues>
                <fullName>Grade I (low)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grade II (Intermediate)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grade III (high)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indeterminate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>On_Study_Pathology_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>On-Study Pathology Form</label>
        <referenceTo>On_Study_Pathology_Form__c</referenceTo>
        <relationshipLabel>Invasive Tumor Details</relationshipLabel>
        <relationshipName>Invasive_Tumor_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Surgery_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Surgery Summary</label>
        <referenceTo>Post_Surgaory_Summary__c</referenceTo>
        <relationshipLabel>Invasive Tumor Details</relationshipLabel>
        <relationshipName>Invasive_Tumor_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tubule_Papilla_formation__c</fullName>
        <label>Tubule/Papilla formation</label>
        <picklist>
            <picklistValues>
                <fullName>1pt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2pt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3pt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indeterminate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not reported</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invasive Tumor Detail</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invasive Tumor Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LCIS__c.object
<CustomObject>
    <fields>
        <fullName>LCIS__c</fullName>
        <label>LCIS</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>On_Study_Pathology_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>On-Study Pathology Form</label>
        <referenceTo>On_Study_Pathology_Form__c</referenceTo>
        <relationshipLabel>LCIS</relationshipLabel>
        <relationshipName>LCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Surgery_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Post Surgery Summary</label>
        <referenceTo>Post_Surgaory_Summary__c</referenceTo>
        <relationshipLabel>LCIS</relationshipLabel>
        <relationshipName>LCIS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LCIS</label>
    <nameField>
        <displayFormat>LCIS-{000000}</displayFormat>
        <label>LCIS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LCIS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/On_Study_Pathology_Form__c.object
<CustomObject>
    <fields>
        <fullName>Does_the_patient_have_bilateral_breast_c__c</fullName>
        <inlineHelpText>Does the patient have bilateral breast cancer?</inlineHelpText>
        <label>Patient have bilateral breast cancer?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>On-Study Pathology Form</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>On-Study Pathology Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>On-Study Pathology Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Post_Surgaory_Summary__c.object
<CustomObject>
    <label>Post Surgery Summary</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Surgery Summaries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestInvasiveTumor.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the 
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestInvasiveTumor {

    @isTest static void myUnitTest() {
        // TO DO: implement unit test
        
        
        InvasiveTumor invTum1 = new InvasiveTumor(); // else part line 23
        
        On_Study_Pathology_Form__c osp = new On_Study_Pathology_Form__c();
        osp.Does_the_patient_have_bilateral_breast_c__c = 'Yes';
        insert osp;
        
        Invasive_Tumor_Detail__c objITD = new Invasive_Tumor_Detail__c();
        objITD.Nuclear_Grade__c = 'Grade II (Intermediate)';
        objITD.Mitotic_Count__c = '1pt';
        objITD.Tubule_Papilla_formation__c = '1pt'; 
        objITD.On_Study_Pathology_Form__c = osp.Id;
        insert objITD;
        
        Post_Surgaory_Summary__c pss = new Post_Surgaory_Summary__c();
        insert pss;
        
        LCIS__c lc = new LCIS__c();
        lc.Post_Surgery_Summary__c = pss.Id;
        insert lc;
        
        ComponentControllerBase ccb = new ComponentControllerBase(); // VIRTUAL CLASS "ComponentControllerBase"
        ccb.key = '1';
        
        PageControllerBase pcb = new PageControllerBase();   // VIRTUAL CLASS "PageControllerBase" BEGINS HERE
        pcb.getComponentControllerMap(); // "get"
        pcb.getIvtComponentController(); // "get"
        pcb.getThis();
        
        pcb.setComponentControllerMap('1', ccb);        // "set"
        pcb.setIvtComponentController(ccb);           // "set" and VIRTUAL CLASS "PageControllerBase" ENDS HERE
        
        Apexpages.currentPage().getParameters().put('PathologyId',osp.Id);
        Apexpages.currentPage().getParameters().put('postid',pss.Id);
        InvasiveTumor invTum = new InvasiveTumor();
        
        invTum.getKey();
        invTum.setPageController(pcb);
        invTum.getPageController();
        invTum.setKey('1');
        
        
        invTum.objITD = objITD;
       // invTum.invasiveId = osp.Id;
        invTum.invasivePostId = pss.Id;
        invTum.saveInvasiveTumor(osp.Id);
        //invTum.sumGrade();
        invTum.savePostInvasiveTumor(pss.Id);
        invTum.setObjId(pss.Id);
    }
    @isTest static void myUnitTest1() {
        // TO DO: implement unit test
        
        InvasiveTumor invTum1 = new InvasiveTumor(); // else part line 23
        
        On_Study_Pathology_Form__c osp = new On_Study_Pathology_Form__c();
        osp.Does_the_patient_have_bilateral_breast_c__c = 'Yes';
        insert osp;
        
        Post_Surgaory_Summary__c pss = new Post_Surgaory_Summary__c();
        insert pss;
        
        Invasive_Tumor_Detail__c objITD = new Invasive_Tumor_Detail__c();
        objITD.Nuclear_Grade__c = 'Grade II (Intermediate)';
        objITD.Mitotic_Count__c = '1pt';
        objITD.Tubule_Papilla_formation__c = '1pt'; 
        objITD.On_Study_Pathology_Form__c = osp.Id;
        insert objITD;
        
        Invasive_Tumor_Detail__c objITD1 = new Invasive_Tumor_Detail__c();
        objITD1.Nuclear_Grade__c = 'Grade II (Intermediate)';
        objITD1.Mitotic_Count__c = '1pt';
        objITD1.Tubule_Papilla_formation__c = '1pt'; 
        objITD1.Post_Surgery_Summary__c = pss.Id;
        insert objITD1;
        
        LCIS__c lc = new LCIS__c();
        lc.Post_Surgery_Summary__c = pss.Id;
        insert lc;
        
       Apexpages.currentPage().getParameters().put('PathologyId',osp.Id);
        InvasiveTumor invTum = new InvasiveTumor();
        invTum.objITD = objITD;
       // invTum.invasiveId = osp.Id;
        invTum.invasivePostId = pss.Id;
        invTum.saveInvasiveTumor(osp.Id);
        //invTum.sumGrade();
        invTum.savePostInvasiveTumor(pss.Id);
        invTum.setObjId(osp.Id);
    }
}