src/objects/LabUser__c.object
<CustomObject>
    <fields>
        <fullName>Lab__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lab</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipName>Lab_Trial_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>LabUser</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LabUser</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LabUser</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MammaPrintDetail__c.object
<CustomObject>
    <fields>
        <fullName>OriginalCRF__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OriginalCRF</label>
        <referenceTo>MammaPrintDetail__c</referenceTo>
        <relationshipLabel>MammaPrint Details</relationshipLabel>
        <relationshipName>MammaPrint_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tissue_Specimen_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tissue Specimen Detail</label>
        <referenceTo>TissueSpecimenDetail__c</referenceTo>
        <relationshipLabel>MammaPrint Details</relationshipLabel>
        <relationshipName>MammaPrint_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>MammaPrint CRF</relationshipLabel>
        <relationshipName>MammaPrint_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MammaPrint Microarray Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MammaPrint Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <label>Medical Record Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Registered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligibility Check Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>pg_patient_id__c</fullName>
        <label>pg_patient_id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Site_Trial__c.object
<CustomObject>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>Site Trials</relationshipLabel>
        <relationshipName>Site_Trials</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>Site Trials</relationshipLabel>
        <relationshipName>Site_Trials</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <picklist>
            <picklistValues>
                <fullName>Site</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Site Trial</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Trials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TissueSpecimenDetail__c.object
<CustomObject>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Tissue Specimen CRF</relationshipLabel>
        <relationshipName>TissueSpecimenDetail</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tissue Specimen Detail</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tissue Specimen Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Trial__c.object
<CustomObject>
    <label>Trial</label>
    <nameField>
        <label>Trial Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRandomized__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsRandomized</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <description>This formula field display MRN as a related list of trial patient.</description>
        <formula>Patient_Id__r.Medical_Record_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Medical Record Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject_Id__c</fullName>
        <label>Subject Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>pg_patient_Id__c</fullName>
        <label>pg_patient_Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/mammaPrintView.cls
public with sharing class mammaPrintView {
	public List<WrapperList> wrapList{get;set;}
	public List<TrialPatient__c> trailPatientList{get;set;}
	public String mmaprintid{get;set;}
	public String trailPatiId{get;set;}
	
	public mammaPrintView(){
		
		String userId = Userinfo.getUserId();
		system.debug('-----userId------'+userId);
		List<LabUser__c> labUserList = [Select l.User__c, l.SystemModstamp, l.OwnerId, l.Name, l.LastModifiedDate, l.LastModifiedById, l.Lab__c, l.IsDeleted, l.Id, l.CreatedDate, l.CreatedById From LabUser__c l where User__c =:userId];
		system.debug('----labUserList--'+labUserList);
		set<id> labIds = new Set<id>();
		for(LabUser__c labU : labUserList){
			labIds.add(labU.Lab__c);
		}
		List<Site_Trial__c> siteTrialList = [Select s.User__c, s.Trial__c, s.SystemModstamp, s.Site__c, s.Name, s.LastModifiedDate, s.LastModifiedById, s.IsDeleted, s.Id, s.CreatedDate, s.CreatedById From Site_Trial__c s where Site__c IN :labIds];
		set<Id> trialId = new Set<id>();
		for(Site_Trial__c siteTra: siteTrialList){
			trialId.add(siteTra.Trial__c);
		}
		
		List<TrialPatient__c> trailPatientList = [Select t.pg_patient_Id__c, t.Trial_Id__c,t.Trial_Id__r.Name, t.SystemModstamp, t.Subject_Id__c, t.Stage__c, t.Site__c,t.Site__r.Name, t.Patient_Id__c, t.Patient_Id__r.Last_Name__c, t.Name, t.Medical_Record_Number__c, t.LastName__c, t.LastModifiedDate, t.LastModifiedById, t.LastActivityDate, t.IsRandomized__c, t.IsDeleted, t.Institution__c, t.Id, t.FirstName__c, t.CreatedDate, t.CreatedById, (Select Id, Status__c From TissueSpecimenDetail__r where Status__c = 'Approval Not Required'),(Select Id, Name, Status__c From MammaPrint_Details__r) From TrialPatient__c t where Trial_Id__c IN :trialId];
		wrapList = new List<WrapperList>();
		
		for(TrialPatient__c trailp : trailPatientList){
			WrapperList wrap = new WrapperList();
			List<MammaPrintDetail__c> mamaprintList = trailp.MammaPrint_Details__r;
			List<TissueSpecimenDetail__c> tissueSpeaci = trailp.TissueSpecimenDetail__r;
			system.debug('-----tissueSpeaci-----'+tissueSpeaci.size());
			if(tissueSpeaci.size() > 0){
				system.debug('-----tissueSpeaci-----'+tissueSpeaci);
				wrap.trailpationId = trailp.id;
				wrap.patientName = trailp.Patient_Id__r.Last_Name__c; 
				wrap.subjectid = trailp.Subject_Id__c;
				wrap.instituteName = trailp.Institution__c;
				wrap.trialname = trailp.Trial_Id__r.Name;
				wrap.siteName = trailp.Site__r.Name;
			
				if(mamaprintList.size() > 0){
					wrap.mamaPrintId = mamaprintList[0].Id;
					wrap.issubmitTrue = true;	
				}else{
					wrap.issubmitTrue = false;
				}
				wrapList.add(wrap);
			} 
		}
	}
	public class WrapperList{
		public String trailpationId{get;set;}
		public String mamaPrintId{get;set;}
		public String subjectid{get;set;}
		public String trialname{get;set;}
		public String siteName{get;set;}
		public String instituteName{get;set;}
		public String patientName{get;set;} 
		public boolean issubmitTrue{get;set;}
		
		public WrapperList(){
			issubmitTrue = false;
		}
		
	}

}