src/objects/Off_Study_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Off Study Details</relationshipLabel>
        <relationshipName>Off_Study_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Off Study Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Off Study Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Off Study Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Randomization_Form__c.object
<CustomObject>
    <fields>
        <fullName>Did_Patient_Sign_Treatment_Consent_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Did Patient Sign Treatment Consent Form?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Randomization_Result__c</fullName>
        <defaultValue>&apos;Not Randomized&apos;</defaultValue>
        <label>Randomization Result</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrialPatient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TrialPatient</label>
        <referenceTo>TrialPatient__c</referenceTo>
        <relationshipLabel>Randomization Forms</relationshipLabel>
        <relationshipName>Randomization_Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Randomization Form</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Randomization Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientsContinueOptedOut_Site.cls
public with sharing class PatientsContinueOptedOut_Site{
    public String data {get;set;}
     public String siteId;
    public String condition ;
    public PatientsContinueOptedOut_Site(){
      data = ''; 
      siteId = ApexPages.CurrentPage().getParameters().get('site');
      List<Profile> profiles = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
      String profileName = profiles[0].Name;
      siteUserData();
      
    }
    
    public void siteUserData(){
         
        List<AggregateResult> randomizationpatientlist = new List<AggregateResult>();
        List<AggregateResult> randomizationpatientlist1 = new List<AggregateResult>();
        if(siteId != '' && siteId != null){
             condition ='and TrialPatient__r.Site__c IN ('+siteId+')';
             randomizationpatientlist = database.query('SELECT Count(TrialPatient__r.Patient_Id__c) countPatient,TrialPatient__r.Site__c siteId FROM Randomization_Form__c where Randomization_Result__c != \'Not Randomized\' and Status__c = \'Approval Not Required\' '+condition+' and Did_Patient_Sign_Treatment_Consent_Form__c = true and TrialPatient__c not in (SELECT TrialPatient__c   FROM Off_Study_Detail__c where  status__c = \'Accepted\') group by TrialPatient__r.Site__c');
             randomizationpatientlist1 = database.query('SELECT Count(TrialPatient__r.Patient_Id__c) countPatient,TrialPatient__r.Site__c siteId FROM Randomization_Form__c where Randomization_Result__c != \'Not Randomized\' and Status__c = \'Approval Not Required\' '+condition+' and Did_Patient_Sign_Treatment_Consent_Form__c = true and TrialPatient__c  in (SELECT TrialPatient__c   FROM Off_Study_Detail__c where  status__c = \'Accepted\') group by TrialPatient__r.Site__c');
        }
        else{
            randomizationpatientlist = database.query('SELECT Count(TrialPatient__r.Patient_Id__c) countPatient,TrialPatient__r.Site__c siteId FROM Randomization_Form__c where Randomization_Result__c != \'Not Randomized\' and Status__c = \'Approval Not Required\' and Did_Patient_Sign_Treatment_Consent_Form__c = true and TrialPatient__c not in (SELECT TrialPatient__c   FROM Off_Study_Detail__c where  status__c = \'Accepted\') group by TrialPatient__r.Site__c');
            randomizationpatientlist1 = database.query('SELECT Count(TrialPatient__r.Patient_Id__c) countPatient,TrialPatient__r.Site__c siteId FROM Randomization_Form__c where Randomization_Result__c != \'Not Randomized\' and Status__c = \'Approval Not Required\' and Did_Patient_Sign_Treatment_Consent_Form__c = true and TrialPatient__c  in (SELECT TrialPatient__c   FROM Off_Study_Detail__c where  status__c = \'Accepted\') group by TrialPatient__r.Site__c');
        }
        Map<String,String> mapsite = new Map<String,String>();
        List<String> siteId = new List<String>();
        for(AggregateResult agr : randomizationpatientlist ){
            siteId.add(String.valueOf(agr.get('siteId')));    
        }
        for(AggregateResult agr : randomizationpatientlist1 ){
            siteId.add(String.valueOf(agr.get('siteId')));    
        }
        
        List<Site__c> site = [select Name from Site__c where id in :siteId] ;
        for(Site__c st : site ){
              mapsite.put(st.id, st.Name);
        }
            
        
        if (randomizationpatientlist.size() > 0 || randomizationpatientlist1.size()>0) {
            data += '[\'Site Name\',';
            Map<String, List<String>> mapdata = new Map<String, List<String>>();
            Set<String> types = new Set<String>();
            for(AggregateResult agr : randomizationpatientlist){
                if(agr.get('siteId') != null){
                    if(!mapdata.containskey(mapsite.get(String.valueOf(agr.get('siteId'))))){
                        mapdata.put(mapsite.get(String.valueOf(agr.get('siteId'))), new List<String>());
                    }  
                    mapdata.get(mapsite.get(String.valueOf(agr.get('siteId')))).add('Continued##'+agr.get('countPatient'));
                  
                }
            }
             for(AggregateResult agr : randomizationpatientlist1){
                if(agr.get('siteId') != null){
                    if(!mapdata.containskey(mapsite.get(String.valueOf(agr.get('siteId'))))){
                        mapdata.put(mapsite.get(String.valueOf(agr.get('siteId'))), new List<String>());
                    }  
                    mapdata.get(mapsite.get(String.valueOf(agr.get('siteId')))).add('optedout##'+agr.get('countPatient'));
                  
                }
            }
           data += '\'Continued Patient\',\'Opted Out Patient\'],';    
           if(mapdata.size()>0){
                for(String st : mapdata.keySet()){
                    data += '[\''+st+'\',';
                    List<String> temp = mapdata.get(st);
                    temp.sort();
                    
                    Integer continued = 0, optedout = 0;
                    for(String phase : mapdata.get(st)){
                        List<String> pasecount = phase.split('##');
                        if(pasecount[0] ==  'Continued')
                            continued    = Integer.valueOf(pasecount[1]); 
                        if(pasecount[0] ==  'optedout')
                            optedout  = Integer.valueOf(pasecount[1]);  
                    }        
                    data += continued+','+optedout+',';     
                    data = data.subString(0,data.length()-1)+'],'; 
                   
               }  
             data = data.subString(0,data.length()-1);
            }
            else{
                data = '[\'Site Name\', \'Type1\',\'Type2\'], [\'No Data\',0,0]';    
            }   
       }
       else {
           data = '[\'Site Name\', \'Type1\',\'Type2\'], [\'No Data\',0,0]';
       } 
    }
 }