src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Age_Group__c</fullName>
        <label>Age Group</label>
        <picklist>
            <picklistValues>
                <fullName>under 20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>over 90</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientByAgeRaceController.cls
public with sharing Class PatientByAgeRaceController{
    public String data{get;set;}
    public PatientByAgeRaceController(){
        
        Map<String, List<String>> mapRacePatients = new Map<String, LIst<String>>();
        set<String> allethnicity = new set<String>();
        String instituteId = ApexPages.CurrentPage().getParameters().get('institute');
        String siteId = ApexPages.CurrentPage().getParameters().get('site');
        String trialId = ApexPages.CurrentPage().getParameters().get('trial');
        if((siteId != '' && siteId != null) || (instituteId != '' && instituteId != null) || (trialId != '' && trialId != null)){    
            String condition ='';
            if(instituteId != '' && instituteId != null){
                condition ='and Patient_Id__r.Institution__c=\''+instituteId+'\'' ;
            }
            if(siteId != '' && siteId != null){
                 condition +='and Site__c IN ('+siteId+')';
            }
            if(trialId != '' && trialId != null){
               condition +='and Trial_Id__c=\''+trialId+'\'';
             } 
             List<TrialPatient__c> patients = database.query('select Patient_Id__r.Race__c , Patient_Id__r.Age_Group__c  from TrialPatient__c  where Patient_Id__r.Ethnicity__c != null and  Patient_Id__r.Age_Group__c != null '+condition);
           // System.debug('Query=========='+'select Patient_Id__r.Race__c , Patient_Id__r.Age_Group__c  from TrialPatient__c  where Patient_Id__r.Ethnicity__c != null and  Patient_Id__r.Age_Group__c != null '+condition);     
            for (TrialPatient__c   pc: patients ) {
                allethnicity.add(pc.Patient_Id__r.Age_Group__c);
                for (String race : String.valueof(pc.Patient_Id__r.Race__c).split(';')) {
                    if (!mapRacePatients.containskey(race+'##'+pc.Patient_Id__r.Age_Group__c)) {
                        mapRacePatients.put(race+'##'+pc.Patient_Id__r.Age_Group__c, new LIst<String>());
                    }
                    mapRacePatients.get(race+'##'+pc.Patient_Id__r.Age_Group__c ).add(pc.Patient_Id__r.id);
                }
            }
        }    
        else{ 
             List<Patient_Custom__c> patients = [select Race__c , Age_Group__c  from Patient_Custom__c
              where Ethnicity__c != null and  Age_Group__c != null ];
             for (Patient_Custom__c   pc: patients ) {
                allethnicity.add(pc.Age_Group__c);
                for (String race : String.valueof(pc.Race__c).split(';')) {
                    if (!mapRacePatients.containskey(race+'##'+pc.Age_Group__c)) {
                        mapRacePatients.put(race+'##'+pc.Age_Group__c, new LIst<String>());
                    }
                mapRacePatients.get(race+'##'+pc.Age_Group__c ).add(pc.id);
                }
             }
        }
       
        
        Map<String,List<String>> ethnicity = new Map<String,List<String>>();
        
        for(String keyq : mapRacePatients.keyset()){
            list<String> splitrace = keyq.split('##');
            if(!ethnicity.containsKey(splitrace[0])){
                ethnicity.put(splitrace[0], new List<String>());
            }
            ethnicity.get(splitrace[0]).add(splitrace[1]+'##'+mapRacePatients.get(keyq).size());
        }
        List<String> allethnicitysorted = new List<String>();
        for(String eth : allethnicity)
            allethnicitysorted.add(eth);
        allethnicitysorted.sort();    
       data = '[\'Race\',\' under 20\',\'20-30\',\'30-40\',\'40-50\',\'50-60\',\'60-70\',\'70-80\',\'80-90\',\'over 90\'],';
       if(ethnicity.keyset().size() == 0){
           data = '[\'Race\',\' under 20\',\'20-30\',\'30-40\',\'40-50\',\'50-60\',\'60-70\',\'70-80\',\'80-90\',\'over 90\'],[\'No Data\',0,0,0,0,0,0,0,0,0]';
       }
       else{ 
            for(String race : ethnicity.keyset()){
                 data += '[\''+race+'\',';
                 integer countlast = 1;
                 Integer a1=0, a2=0, a3=0, a4=0, a5=0, a6=0, a7=0, a8=0, a9=0;
                 for(String ethnicitycount : ethnicity.get(race)){
                   List<String> arr =    ethnicitycount.split('##');
                      if (arr[0] == 'under 20') {
                           a1 = Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '20-30') {
                            a2 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '30-40') {
                            a3 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '40-50') {
                            a4 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '50-60') {
                           a5 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '60-70') {
                           a6 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '70-80') {
                            a7 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == '80-90') {
                             a8 =  Integer.valueOf(arr[1]);
                        }
                        else if (arr[0] == 'over 90') {
                             a9 = Integer.valueOf(arr[1]);
                        }
                     } 
                     data += a1+','+a2+','+a3+','+a4+','+a5+','+a6+','+a7+','+a8+','+a9+'],';
            
            }
        }
        System.debug('Race & Age======'+data);
    }
}