src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Ethnicity__c</fullName>
        <label>Ethnicity</label>
        <picklist>
            <picklistValues>
                <fullName>Hispanic or Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Hispanic or Latino</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientByEthinicityAndRaceController.cls
public with sharing Class PatientByEthinicityAndRaceController{
    Public String data{get;set;}
    public void getData() {
        Map<String, List<String>> mapRacePatients = new Map<String, LIst<String>>();
        set<String> allethnicity = new set<String>();
        String instituteId = ApexPages.CurrentPage().getParameters().get('institute');
        String siteId = ApexPages.CurrentPage().getParameters().get('site');
        String trialId = ApexPages.CurrentPage().getParameters().get('trial');
        if((siteId != '' && siteId != null) || (instituteId != '' && instituteId != null) || (trialId != '' && trialId != null)){    
            String condition ='';
            if(instituteId != '' && instituteId != null){
                condition ='and Patient_Id__r.Institution__c=\''+instituteId+'\'' ;
            }
            if(siteId != '' && siteId != null){
                 condition +='and Site__c IN ('+siteId+')';
            }
            if(trialId != '' && trialId != null){
               condition +='and Trial_Id__c=\''+trialId+'\'';
             } 
             List<TrialPatient__c> patients = database.query('select Patient_Id__r.Race__c , Patient_Id__r.Ethnicity__c  from TrialPatient__c  where Patient_Id__r.Ethnicity__c != null and  Patient_Id__r.Race__c != null '+condition);
              for (TrialPatient__c     pc: patients ) {
                  allethnicity.add(pc.Patient_Id__r.Ethnicity__c);
                  for (String race : String.valueof(pc.Patient_Id__r.race__c).split(';')) {
                        if (!mapRacePatients.containskey(race+'##'+pc.Patient_Id__r.Ethnicity__c )) {
                            mapRacePatients.put(race+'##'+pc.Patient_Id__r.Ethnicity__c, new LIst<String>());
                        }
                        mapRacePatients.get(race+'##'+pc.Patient_Id__r.Ethnicity__c).add(pc.Patient_Id__c);
                  }
              }
        }    
        else{ 
            List<Patient_Custom__c  > patients = [select Ethnicity__c , Race__c  from Patient_Custom__c 
          where Ethnicity__c != null and Race__c != null];
          for (Patient_Custom__c   pc: patients ) {
              allethnicity.add(pc.Ethnicity__c);
              for (String race : String.valueof(pc.race__c).split(';')) {
                    if (!mapRacePatients.containskey(race+'##'+pc.Ethnicity__c )) {
                        mapRacePatients.put(race+'##'+pc.Ethnicity__c, new LIst<String>());
                    }
                    mapRacePatients.get(race+'##'+pc.Ethnicity__c).add(pc.id);
              }
          }
        
        }
        
        Map<String,Map<String,Integer>> ethnicity = new Map<String,Map<String,Integer>>();
        
        for(String keyq : mapRacePatients.keyset()){
            list<String> splitrace = keyq.split('##');
            if(!ethnicity.containsKey(splitrace[0])){
                ethnicity.put(splitrace[0], new Map<String,Integer>());
            }
            ethnicity.get(splitrace[0]).put(splitrace[1],mapRacePatients.get(keyq).size());
        }
        
        List<String> allethnicitysorted = new List<String>();
        for(String eth : allethnicity)
            allethnicitysorted.add(eth);
        allethnicitysorted.sort();    
        data = '[\'Race\',\' Hispanic or latino \',\' Not Hispanic or Latino\'],';
        if(ethnicity.size() > 0){
            for(String race : ethnicity.keyset()){
                 data += '[\''+race+'\',';
                 integer countlast = 1;
                 Integer Hisanic =0, NHisanic =0;
                 for(String  eth : ethnicity.get(race).keyset()){
                     if(eth == 'Hispanic or Latino'){
                         Hisanic =  ethnicity.get(race).get(eth);
                      }    
                     else
                         NHisanic = ethnicity.get(race).get(eth);      
                     countlast++; 
                     } 
               data += Hisanic +','+NHisanic+'],';       
               
            }
        }
        else{
             data += '[\'No Data\',0,0],';    
        }     
       //System.assert(false,data );
    }
    
    public PatientByEthinicityAndRaceController(){
        getData();
    
    }    
}