src/objects/Patient_Custom__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Institution</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Race__c</fullName>
        <label>Race</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Site__c.object
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <recordTypes>
        <fullName>Site</fullName>
        <active>true</active>
        <label>Site</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Institution__c</fullName>
        <description>Formula field to show Institution in related list of trial patient.</description>
        <formula>Patient_Id__r.Institution__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Institution</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Site</label>
        <referenceTo>Site__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Trial Name</label>
        <referenceTo>Trial__c</referenceTo>
        <relationshipLabel>TrialPatients</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PatientByRaceController.cls
public with sharing Class PatientByRaceController{
    public String data{get;set;}
    public PatientByRaceController(){
         data = '[\'Race\',\' Number Of Patients\'],';
         Map<String, List<String>> mapRacePatients = new Map<String, LIst<String>>();
        /* ['Race',' Number Of Patients'],['American Indian or Alaska Native',155],['Asian',169],
         ['Black or African American',42],['Native Hawaiian or Pacific Islander',9],['White',9]
          ['Race',' Number Of Patients'],['Native Hawaiian or Pacific Islander',10],['White',10],
          ['Asian',178],['Black or African American',45],['American Indian or Alaska Native',157]
         */
        String instituteId = ApexPages.CurrentPage().getParameters().get('institute');
        String siteId = ApexPages.CurrentPage().getParameters().get('site');
        String trialId = ApexPages.CurrentPage().getParameters().get('trial');
        if((siteId != '' && siteId != null) || (instituteId != '' && instituteId != null) || (trialId != '' && trialId != null)){    
            String condition ='';
            if(instituteId != '' && instituteId != null){
                condition ='and Patient_Id__r.Institution__c=\''+instituteId+'\'' ;
            }
            if(siteId != '' && siteId != null){
                 condition +='and Site__c IN ('+siteId+')';
            }
            if(trialId != '' && trialId != null){
               condition +='and Trial_Id__c=\''+trialId+'\'';
             } 
             List<TrialPatient__c> patients = database.query('select Patient_Id__r.Race__c   from TrialPatient__c  where   Patient_Id__r.Race__c != null '+condition);
              for (TrialPatient__c   pc: patients ) {
                   for (String race : String.valueof(pc.Patient_Id__r.Race__c).split(';')) {
                       if (!mapRacePatients.containskey(race)) {
                           mapRacePatients.put(race, new LIst<String>());
                       }
                       mapRacePatients.get(race).add(pc.id);
                    }
                }
      }    
        else{  
        List<Patient_Custom__c  > patients = [select  Race__c  from Patient_Custom__c 
          where  Race__c != null ];
        
        
        for (Patient_Custom__c   pc: patients ) {
            for (String race : String.valueof(pc.Race__c).split(';')) {
                if (!mapRacePatients.containskey(race)) {
                    mapRacePatients.put(race, new LIst<String>());
                }
                mapRacePatients.get(race).add(pc.id);
            }
        }
       }
       
        if(mapRacePatients.size() > 0){
            Integer count = 1 ;
            for(String str : mapRacePatients.keyset()){
                if(mapRacePatients.keyset().size() == count)
                    data += '[\''+str+'\','+mapRacePatients.get(str).size()+']';
                else
                    data += '[\''+str+'\','+mapRacePatients.get(str).size()+'],';
                
            
            }
        }
        else{
             data += '[\'No Data\',0]';    
        }        
       //System.assert(false,data); 
    }
}