src/objects/PreEligibility_Checklist__c.object
<CustomObject>
    <fields>
        <fullName>CRF_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>CRF Id</label>
        <referenceTo>CRF__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clinically_radiologically_measurable__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has clinically or radiologically measurable or non-measurable disease in breast defined as longest diameter ≥ 2.5cm, per protocol 4.1.1 B.</inlineHelpText>
        <label>Clinically/radiologically measurable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cytotoxic_Regiments__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has not had prior cytotoxic regimens or other targeted anticancer therapies to the ipsilateral breast for this malignancy, per protocol 4.1.1 C.</inlineHelpText>
        <label>Cytotoxic Regiments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ECOG_Score__c</fullName>
        <label>ECOG Score</label>
        <picklist>
            <picklistValues>
                <fullName>0-Asymptomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-Symptomatic but ambulatory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-Symptomatic, &lt;50% in bed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3-Symptomatic, &gt;= 50% in bed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4-Bedbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5-Death</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ferromegnatic_Prostheses__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has no ferromagnetic prostheses that are not compatible with an MRI machine, per protocol 4.1.1 H.</inlineHelpText>
        <label>No ferromagnetic prostheses</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Had_prior_cytotoxic_regimens_anticancer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has not had prior cytotoxic regimens or other targeted anticancer therapies to the ipsilateral breast for this malignancy, per protocol 4.1.1 C.</inlineHelpText>
        <label>Not had prior cytotoxic regimens</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Histologically_confirmed_invasive_cancer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has histologically confirmed invasive cancer of the female breast as confirmed by core needle, fine needle aspirate, or incisional biopsy*(*Incisional biopsy is allowed if residual tumor after biopsy measures at least 2.5cm), per protocol 4.1.1 A.</inlineHelpText>
        <label>Histologically confirmed invasive cancer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Non_Pregnant_Not_Lactating__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient is non-pregnant and non-lactating, per protocol 4.1.1 G.</inlineHelpText>
        <label>Non-Pregnant and Not-Lactating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Not_had_prior_RT__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has not had prior RT to the ipsilateral breast for this malignancy, per protocol 4.1.1 C.</inlineHelpText>
        <label>Not had prior RT</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_investigational_agents__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has not had other investigational agents within 30 days of study enrollment, per protocol 4.2 A.</inlineHelpText>
        <label>Not had other investigational agents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Patient</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>PreEligibility Checklists</relationshipLabel>
        <relationshipName>PreEligibility_Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_is_18_years_or_older__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient is 18 years or older, per protocol 4.1.1 D.</inlineHelpText>
        <label>Patient is 18 years or older</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_is_eligible_to_be_screened_for_t__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient is eligible to be screened for the study.</inlineHelpText>
        <label>Patient is eligible to be screened</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_is_willin_to_have_study_MRI__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient is willing to have study MRI.</inlineHelpText>
        <label>Patient is willing to have study MRI</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_is_willing_to_have_core_biospy__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient is willing to have study core biopsy.</inlineHelpText>
        <label>Patient is willing to have core biospy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_signed_up_for_I_SPY2_screening__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient signed up for I-SPY2 screening form.</inlineHelpText>
        <label>Patient signed up for I-SPY2 screening</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Screening</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_for_not_signing_screening_consent__c</fullName>
        <inlineHelpText>Reason for not signing screening consent?</inlineHelpText>
        <label>Reason for not signing screening consent</label>
        <picklist>
            <controllingField>Patient_signed_up_for_I_SPY2_screening__c</controllingField>
            <picklistValues>
                <fullName>Patient does not want to participate in a clinical trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient is not willing to be treated with an investigational agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient decided to be treated with a different neoadjuvant regimen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient decided to have surgery before treatment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Patient decided to be treated at another clinic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance will not cover cost of standard care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Completed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Not Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted by Lab</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>X30_Days_Investigational_Agents__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Patient has not had other investigational agents within 30 days of study enrollment, per protocol 4.2 A.</inlineHelpText>
        <label>30 Days Investigational Agents</label>
        <type>Checkbox</type>
    </fields>
    <label>PreEligibility Checklist</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>PreEligibility Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PreEligibility Checklists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PreEligibilityChecklistPdf.cls
public with sharing class PreEligibilityChecklistPdf{
   
    public PreEligibility_Checklist__c preObj {get; set;}
    string preEligibilityId;
   
    public PreEligibilityChecklistPdf(Apexpages.StandardController std) {
        preEligibilityId = Apexpages.currentPage().getParameters().get('id');
        if(preEligibilityId != null && preEligibilityId != '')
            preObj = [Select p.X30_Days_Investigational_Agents__c, p.Status__c, p.RecordTypeId, p.Reason_for_not_signing_screening_consent__c, p.Phase__c, p.Patient_signed_up_for_I_SPY2_screening__c, p.Patient_is_willing_to_have_core_biospy__c, p.Patient_is_willin_to_have_study_MRI__c, p.Patient_is_eligible_to_be_screened_for_t__c, p.Patient_is_18_years_or_older__c, p.Patient__c, p.Other_investigational_agents__c, p.Not_had_prior_RT__c, p.Non_Pregnant_Not_Lactating__c, p.Name, p.Histologically_confirmed_invasive_cancer__c, p.Had_prior_cytotoxic_regimens_anticancer__c, p.Ferromegnatic_Prostheses__c, p.ECOG_Score__c, p.Cytotoxic_Regiments__c, p.CreatedDate, p.CreatedById, p.CompletedDate__c, p.Clinically_radiologically_measurable__c, p.CRF_Id__c From PreEligibility_Checklist__c p where id = : preEligibilityId];
            
    }
     
}