src/objects/TrialPatient__c.object
<CustomObject>
    <fields>
        <fullName>Patient_Id__c</fullName>
        <label>Patient Name</label>
        <referenceTo>Patient_Custom__c</referenceTo>
        <relationshipLabel>Trial Associations</relationshipLabel>
        <relationshipName>TrialPatients</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrialPatient</label>
    <nameField>
        <label>Record Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrialPatients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrialPatientFormController.cls
public with sharing class TrialPatientFormController {
	string trialPatientFrmId;
	public TrialPatientFormController(Apexpages.standardcontroller std){
		System.debug('TrialPatientForm-------'+std.getId());
        trialPatientFrmId = std.getId();
	}
	
	public Pagereference showPatientView(){
		List<TrialPatient__c> trialPatientList = [Select t.Patient_Id__c From TrialPatient__c t where id = :trialPatientFrmId];
		if(!trialPatientList.isEmpty()){
			pagereference pg = new pagereference('/'+trialPatientList[0].Patient_Id__c);
        	pg.setRedirect(true);
        	return pg;
		}
		return null;
	}
}