src/objects/Widget__c.object
<CustomObject>
    <fields>
        <fullName>Chart_Fields__c</fullName>
        <label>Chart Fields</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Data_Limit__c</fullName>
        <label>Data Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Query_Type__c</fullName>
        <label>Query Type</label>
        <picklist>
            <picklistValues>
                <fullName>Aggregate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Query__c</fullName>
        <label>Query</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <picklist>
            <picklistValues>
                <fullName>A Quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Half</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Three Quarters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Column</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Widget</label>
    <nameField>
        <label>Widget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestChart.cls
@isTest
global class TestChart{
   
   public static testMethod void TestChart(){
         Widget__c widget=new  Widget__c();
         widget.query__c = 'select name , NumberOfEmployees from account where  NumberOfEmployees != null ';
         widget.query_type__c ='normal';
         widget.Type__c='Bar';
         widget.Size__c='Small';
         widget.Data_Limit__c = 5;
         widget.Chart_Fields__c=('name,NumberOfEmployees');
         Chart chart = new Chart( new BarChart());
         chart.widget = widget;
         chart.getChartData();
       }
}